### ISSUE TITLE
bad block type after pkill -9 -f influxdb

### ISSUE THREAD

**Issue by dreampuf** [influxdb/influxdb#1404]
After a force kill the influxdb process (`/etc/init.d/influxdb stop` not working). When I restart this service and try write some points, it's throw a `bad block type` error.

```python
Traceback (most recent call last):
  File "ads_collect.py", line 79, in <module>
    for server_name, insert_ok, result in executor.map(fetcher, jobs):
  File "/home/ops/.pyenv/versions/scripts/lib/python2.7/site-packages/concurrent/futures/_base.py", line 580, in map
    yield future.result()
  File "/home/ops/.pyenv/versions/scripts/lib/python2.7/site-packages/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/home/ops/.pyenv/versions/scripts/lib/python2.7/site-packages/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/home/ops/.pyenv/versions/scripts/lib/python2.7/site-packages/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/home/ops/.pyenv/versions/scripts/lib/python2.7/site-packages/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "ads_collect.py", line 66, in fetcher
    return server, client.write_points(json_body), r
  File "/home/ops/.pyenv/versions/scripts/lib/python2.7/site-packages/influxdb/client.py", line 220, in write_points
    return self._write_points(data=data, time_precision=time_precision)
  File "/home/ops/.pyenv/versions/scripts/lib/python2.7/site-packages/influxdb/client.py", line 258, in _write_points
    expected_response_code=200
  File "/home/ops/.pyenv/versions/scripts/lib/python2.7/site-packages/influxdb/client.py", line 174, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.client.InfluxDBClientError: 400: Corruption: bad block type
```

Do you guys know how to fix this ? I just rename the latest db folder of `shared/data/db/shard_db_v2/` to do this with one kind of workaround.

```bash
root@/export/data/influxdb/shared $ ll data/db/shard_db_v2/
total 1.8M
drwxr--r-- 9 influxdb influxdb 4.0K Jan 28 19:02 ./
drwxr--r-- 3 influxdb influxdb 4.0K Jan 23 20:08 ../
drwxr-xr-x 2 influxdb influxdb  36K Jan 28 19:02 00001/
drwxr-xr-x 2 influxdb influxdb 260K Jan 28 19:02 00002/
drwxr-xr-x 2 influxdb influxdb 260K Jan 28 19:02 00003/
drwxr-xr-x 2 influxdb influxdb 284K Jan 28 19:02 00004/
drwxr-xr-x 2 influxdb influxdb 612K Jan 28 19:02 00005/
drwxr-xr-x 2 influxdb influxdb 4.0K Jan 28 19:07 00006/
drwxr-xr-x 2 influxdb influxdb 324K Jan 28 19:00 _00006/   <--- this should be the broken block
```

**Comment by otoolep** [comment]
The new 0.9.0 implementation based on BoltDB is crash-safe, so this is no longer an issue.
