### ISSUE TITLE
Panic on top-level timestamp key

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1499]
Sending this into a server:
```
{
    "database": "foo",
    "retentionPolicy": "bar",
    "points": [
        {
            "name": "cpu_load_short",
            "values": {
                "value": 0.64
            }
        },
        {
            "name": "cpu_load_short",
            "values": {
                "value": 0.55
            },
            "timestamp": "2009-11-10T23:00:10Z"
        },
        {
            "name": "network",
            "tags": {
                "direction": "in"
            },
            "values": {
                "value": 23422
            }
        }
    ],
    "tags": {
        "host": "server01",
        "region": "us-west"
    },
    "timestamp": "2009-11-10T23:00:00Z"
}
```
results in this panic:
```
[http] 127.0.0.1 - - [03/Feb/2015:09:20:16 -0800] GET /query?q=CREATE%20DATABASE%20foo HTTP/1.1 200 16 - curl/7.35.0 eba1a110-abc8-11e4-8083-54ee75168d03
[http] 127.0.0.1 - - [03/Feb/2015:09:20:16 -0800] GET /query?q=CREATE%20RETENTION%20POLICY%20bar%20ON%20foo%20DURATION%201h%20REPLICATION%201%20DEFAULT HTTP/1.1 200 16 - curl/7.35.0 ebac85b2-abc8-11e4-8083-54ee75168d03
[influxd] 2015/02/03 09:20:16 http: panic serving 127.0.0.1:47016: assignment to entry in nil map
goroutine 27 [running]:
net/http.func·011()
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb/httpd.(*Handler).serveWrite(0xc2080c2210, 0x7f0539956ba0, 0xc2080fc500, 0xc20806cdd0, 0x0)
        /home/philip/build/src/github.com/influxdb/influxdb/httpd/handler.go:257 +0xac8
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveWrite)·fm(0x7f0539956ba0, 0xc2080fc500, 0xc20806cdd0, 0x0)
        /home/philip/build/src/github.com/influxdb/influxdb/httpd/handler.go:60 +0x4f
github.com/influxdb/influxdb/httpd.func·003(0x7f0539956ba0, 0xc2080fc500, 0xc20806cdd0)
        /home/philip/build/src/github.com/influxdb/influxdb/httpd/handler.go:436 +0x77
net/http.HandlerFunc.ServeHTTP(0xc20801e7c0, 0x7f0539956ba0, 0xc2080fc500, 0xc20806cdd0)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·004(0x7f0539956ba0, 0xc2080fc500, 0xc20806cdd0)
        /home/philip/build/src/github.com/influxdb/influxdb/httpd/handler.go:468 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc20801e7e0, 0x7f0539956ba0, 0xc2080fc500, 0xc20806cdd0)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0x7f0539956ba0, 0xc2080fc500, 0xc20806cdd0)
        /home/philip/build/src/github.com/influxdb/influxdb/httpd/handler.go:501 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc2080ec420, 0x7f0539956ba0, 0xc2080fc500, 0xc20806cdd0)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x7f0539956ba0, 0xc2080fc500, 0xc20806cdd0)
        /home/philip/build/src/github.com/influxdb/influxdb/httpd/handler.go:511 +0x164
net/http.HandlerFunc.ServeHTTP(0xc2080ec460, 0x7f0539956ba0, 0xc2080fc500, 0xc20806cdd0)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0x7f0539956ba0, 0xc2080fc4e0, 0xc20806cdd0)
        /home/philip/build/src/github.com/influxdb/influxdb/httpd/handler.go:519 +0x123
net/http.HandlerFunc.ServeHTTP(0xc20801e800, 0x7f0539956ba0, 0xc2080fc4e0, 0xc20806cdd0)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·008(0x7f0539956878, 0xc20805f2c0, 0xc20806cdd0)
        /home/philip/build/src/github.com/influxdb/influxdb/httpd/handler.go:529 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc20801e840, 0x7f0539956878, 0xc20805f2c0, 0xc20806cdd0)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208038060, 0x7f0539956878, 0xc20805f2c0, 0xc20806cdd0)
        /home/philip/build/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc2080c2210, 0x7f0539956878, 0xc20805f2c0, 0xc20806cdd0)
        /home/philip/build/src/github.com/influxdb/influxdb/httpd/handler.go:110 +0x4a
main.(*Handler).ServeHTTP(0xc20801f0e0, 0x7f0539956878, 0xc20805f2c0, 0xc20806cdd0)
        /home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:41 +0x1f5
net/http.serverHandler.ServeHTTP(0xc208058120, 0x7f0539956878, 0xc20805f2c0, 0xc20806cdd0)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20805f220)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1751 +0x35e
```

**Comment by otoolep** [comment]
Fixed by PR 1503.
