### ISSUE TITLE
Panic on `SHOW TAG KEYS` for non-existent measurement

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1510]
`SHOW TAG KEYS FROM cpuxxx WHERE host='sxxx'`

results in:

```
[influxd] 2015/02/04 12:17:57 http: panic serving 127.0.0.1:36812: runtime error: invalid memory address or nil pointer dereference
goroutine 60 [running]:
net/http.func·011()
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb.(*Measurement).tagKeys(0x0, 0x0, 0x0, 0x0)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/database.go:1202 +0x4e
github.com/influxdb/influxdb.(*Server).executeShowTagKeysStatement(0xc2080587e0, 0xc2080523c0, 0xc2080d534e, 0x3, 0x0, 0x0)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/server.go:2001 +0x381
github.com/influxdb/influxdb.(*Server).ExecuteQuery(0xc2080587e0, 0xc20801ee40, 0xc2080d534e, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/server.go:1734 +0x531
github.com/influxdb/influxdb/httpd.(*Handler).serveQuery(0xc2080c3ce0, 0x7f7a0b6c8c58, 0xc20801ed00, 0xc208113450, 0x0)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/httpd/handler.go:137 +0x43c
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveQuery)·fm(0x7f7a0b6c8c58, 0xc20801ed00, 0xc208113450, 0x0)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/httpd/handler.go:55 +0x4f
github.com/influxdb/influxdb/httpd.func·002(0x7f7a0b6c8c58, 0xc20801ed00, 0xc208113450)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/httpd/handler.go:352 +0x77
net/http.HandlerFunc.ServeHTTP(0xc20801fde0, 0x7f7a0b6c8c58, 0xc20801ed00, 0xc208113450)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·003(0x7f7a0b6c8c58, 0xc20801ed00, 0xc208113450)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/httpd/handler.go:384 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc20801fe00, 0x7f7a0b6c8c58, 0xc20801ed00, 0xc208113450)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·004(0x7f7a0b6c8c58, 0xc20801ed00, 0xc208113450)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/httpd/handler.go:417 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc208068940, 0x7f7a0b6c8c58, 0xc20801ed00, 0xc208113450)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0x7f7a0b6c8c58, 0xc20801ed00, 0xc208113450)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/httpd/handler.go:427 +0x164
net/http.HandlerFunc.ServeHTTP(0xc208068960, 0x7f7a0b6c8c58, 0xc20801ed00, 0xc208113450)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x7f7a0b6c8c58, 0xc20801ece0, 0xc208113450)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/httpd/handler.go:435 +0x123
net/http.HandlerFunc.ServeHTTP(0xc20801fe20, 0x7f7a0b6c8c58, 0xc20801ece0, 0xc208113450)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0x7f7a0b6c8878, 0xc208056780, 0xc208113450)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/httpd/handler.go:445 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc20801fe40, 0x7f7a0b6c8878, 0xc208056780, 0xc208113450)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208038348, 0x7f7a0b6c8878, 0xc208056780, 0xc208113450)
        /home/philip/Dropbox/repos/influxdb/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc2080c3ce0, 0x7f7a0b6c8878, 0xc208056780, 0xc208113450)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/httpd/handler.go:109 +0x4a
main.(*Handler).ServeHTTP(0xc20801f0e0, 0x7f7a0b6c8878, 0xc208056780, 0xc208113450)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:41 +0x1f5
net/http.serverHandler.ServeHTTP(0xc208050120, 0x7f7a0b6c8878, 0xc208056780, 0xc208113450)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208056640)
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /home/philip/.gvm/gos/go1.4/src/net/http/server.go:1751 +0x35e
```

**Comment by otoolep** [comment]
cc @dgnorton
