### ISSUE TITLE
Panic in HTTP handler -- user nil?

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1568]
Seen with RC2:
```
[srvr] 2015/02/11 17:34:21 http: panic serving 127.0.0.1:33670: runtime error: invalid memory address or nil pointer dereference
goroutine 1313427 [running]:
net/http.func·011()
    /root/.gvm/gos/go1.4/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb/httpd.(*Handler).serveWrite(0xc208090ae0, 0x7f306eb68850, 0xc2083d3560, 0xc2082b60d0, 0x0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:180 +0x51a
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveWrite)·fm(0x7f306eb68850, 0xc2083d3560, 0xc2082b60d0, 0x0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:67 +0x4f
github.com/influxdb/influxdb/httpd.func·002(0x7f306eb68850, 0xc2083d3560, 0xc2082b60d0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:412 +0x2a3
net/http.HandlerFunc.ServeHTTP(0xc2080cad00, 0x7f306eb68850, 0xc2083d3560, 0xc2082b60d0)
    /root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·003(0x7f306eb68350, 0xc2083d3480, 0xc2082b60d0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:436 +0x288
net/http.HandlerFunc.ServeHTTP(0xc20808ae60, 0x7f306eb68350, 0xc2083d3480, 0xc2082b60d0)
    /root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·004(0x7f306eb68350, 0xc2083d3480, 0xc2082b60d0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:445 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc2080cad20, 0x7f306eb68350, 0xc2083d3480, 0xc2082b60d0)
    /root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0x7f306eb68350, 0xc2083d3480, 0xc2082b60d0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:478 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc20808aeb0, 0x7f306eb68350, 0xc2083d3480, 0xc2082b60d0)
    /root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x7f306eb68350, 0xc2083d3480, 0xc2082b60d0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:488 +0x164
net/http.HandlerFunc.ServeHTTP(0xc20808aed0, 0x7f306eb68350, 0xc2083d3480, 0xc2082b60d0)
    /root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0x7f306eb68350, 0xc2083d3460, 0xc2082b60d0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:496 +0x123
net/http.HandlerFunc.ServeHTTP(0xc2080cad40, 0x7f306eb68350, 0xc2083d3460, 0xc2082b60d0)
    /root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·008(0x7f306eb67ab0, 0xc2083a9860, 0xc2082b60d0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:506 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc2080cad60, 0x7f306eb67ab0, 0xc2083a9860, 0xc2082b60d0)
    /root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208036150, 0x7f306eb67ab0, 0xc2083a9860, 0xc2082b60d0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc208090ae0, 0x7f306eb67ab0, 0xc2083a9860, 0xc2082b60d0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:124 +0x4a
main.(*Handler).ServeHTTP(0xc2080ca520, 0x7f306eb67ab0, 0xc2083a9860, 0xc2082b60d0)
    /root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:41 +0x1f5
net/http.serverHandler.ServeHTTP(0xc208052060, 0x7f306eb67ab0, 0xc2083a9860, 0xc2082b60d0)
    /root/.gvm/gos/go1.4/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2083a9680)
    /root/.gvm/gos/go1.4/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /root/.gvm/gos/go1.4/src/net/http/server.go:1751 +0x35e
```

**Comment by otoolep** [comment]
@corylanou
