### ISSUE TITLE
InfluxDB v0.8.3 fails to start after a shutdown

### ISSUE THREAD

**Issue by francispereira** [influxdb/influxdb#1601]
When attempting to start, InfluxDB panics

sudo  -uinfluxdb  /usr/bin/influxdb -pidfile /opt/influxdb/shared/influxdb.pid -config /opt/influxdb/shared/config.toml

[02/14/15 10:14:37] [INFO] Loading configuration file /opt/influxdb/shared/config.toml
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6782aa]

goroutine 27 [running]:
runtime.panic(0xbfc980, 0x120f153)
	/.gvm/gos/go1.3.1/src/pkg/runtime/panic.c:279 +0xf5
github.com/influxdb/influxdb/cluster.(*ShardData).SetServers(0xc2080b4000, 0xc208096020, 0x1, 0x1)
	/gocodez/src/github.com/influxdb/influxdb/cluster/shard.go:157 +0x10a
github.com/influxdb/influxdb/cluster.(*ClusterConfiguration).AddShards(0xc2080d2000, 0xc2081bce80, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gocodez/src/github.com/influxdb/influxdb/cluster/cluster_configuration.go:1036 +0x8ca
github.com/influxdb/influxdb/coordinator.(*CreateShardsCommand).Apply(0xc2080b38c0, 0x7fc72cc68550, 0xc20808f440, 0x0, 0x0, 0x0, 0x0)
	/gocodez/src/github.com/influxdb/influxdb/coordinator/command.go:359 +0xd5
github.com/influxdb/influxdb/_vendor/raft.func·006(0xc2080bf200, 0x7fc72cc63a20, 0xc2080b38c0, 0x0, 0x0, 0x0, 0x0)
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:206 +0x422
github.com/influxdb/influxdb/_vendor/raft.(*Log).setCommitIndex(0xc208095340, 0xf0, 0x0, 0x0)
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/log.go:375 +0x3e5
github.com/influxdb/influxdb/_vendor/raft.(*server).processCommand(0xc20808f440, 0x7fc72cc689c0, 0x0, 0xc2080ae180)
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:922 +0x4dc
github.com/influxdb/influxdb/_vendor/raft.(*server).leaderLoop(0xc20808f440)
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:846 +0x4d7
github.com/influxdb/influxdb/_vendor/raft.(*server).loop(0xc20808f440)
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:609 +0x3d1
github.com/influxdb/influxdb/_vendor/raft.func·007()
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:470 +0x5d
created by github.com/influxdb/influxdb/_vendor/raft.(*server).Start
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:471 +0x3b8

goroutine 16 [chan receive]:
github.com/influxdb/influxdb/server.(*Server).ListenAndServe(0xc208040480, 0x0, 0x0)
	/gocodez/src/github.com/influxdb/influxdb/server/server.go:92 +0x114
main.main()
	/gocodez/src/github.com/influxdb/influxdb/daemon/influxd.go:166 +0xec7

goroutine 19 [finalizer wait]:
runtime.park(0x4f7bc0, 0x1227900, 0x1211ec9)
	/.gvm/gos/go1.3.1/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x1227900, 0x1211ec9)
	/.gvm/gos/go1.3.1/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/.gvm/gos/go1.3.1/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/.gvm/gos/go1.3.1/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
	/.gvm/gos/go1.3.1/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/.gvm/gos/go1.3.1/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [chan receive]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc208070000, 0x7fc72cc63440, 0xc208030008)
	/gocodez/src/code.google.com/p/log4go/termlog.go:27 +0x79
created by code.google.com/p/log4go.NewConsoleLogWriter
	/gocodez/src/code.google.com/p/log4go/termlog.go:19 +0x68

goroutine 17 [syscall]:
runtime.goexit()
	/.gvm/gos/go1.3.1/src/pkg/runtime/proc.c:1445

goroutine 22 [runnable]:
code.google.com/p/log4go.func·002()
	/gocodez/src/code.google.com/p/log4go/filelog.go:84 +0x8ac
created by code.google.com/p/log4go.NewFileLogWriter
	/gocodez/src/code.google.com/p/log4go/filelog.go:116 +0x2c4

goroutine 23 [chan receive]:
github.com/influxdb/influxdb/wal.(*WAL).processEntries(0xc20802a8c0)
	/gocodez/src/github.com/influxdb/influxdb/wal/wal.go:252 +0x64
created by github.com/influxdb/influxdb/wal.NewWAL
	/gocodez/src/github.com/influxdb/influxdb/wal/wal.go:103 +0xa53

goroutine 24 [chan receive]:
main.waitForSignals(0x7fc72cc67310, 0xc208040480)
	/gocodez/src/github.com/influxdb/influxdb/daemon/null_profiler.go:23 +0x14c
created by main.startProfiler
	/gocodez/src/github.com/influxdb/influxdb/daemon/null_profiler.go:15 +0x4b

goroutine 25 [IO wait]:
net.runtime_pollWait(0x7fc72cc68338, 0x72, 0x0)
	//.gvm/gos/go1.3.1/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208094060, 0x72, 0x0, 0x0)
	/.gvm/gos/go1.3.1/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208094060, 0x0, 0x0)
	/.gvm/gos/go1.3.1/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc208094000, 0xd94c70, 0x0, 0x7fc72cc632b8, 0xb)
	/.gvm/gos/go1.3.1/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc208096000, 0xc2080985a8, 0x0, 0x0)
	/.gvm/gos/go1.3.1/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc208096000, 0x0, 0x0, 0x0, 0x0)
	/.gvm/gos/go1.3.1/src/pkg/net/tcpsock_posix.go:244 +0x4b
net/http.(*Server).Serve(0xc208004480, 0x7fc72cc67390, 0xc208096000, 0x0, 0x0)
	/.gvm/gos/go1.3.1/src/pkg/net/http/server.go:1698 +0x91
github.com/influxdb/influxdb/coordinator.func·008()
	/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:578 +0x3a
created by github.com/influxdb/influxdb/coordinator.(*RaftServer).Serve
	/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:582 +0x44c

goroutine 28 [select]:
github.com/influxdb/influxdb/coordinator.(*RaftServer).CompactLog(0xc208072580)
	/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:347 +0x332
created by github.com/influxdb/influxdb/coordinator.(*RaftServer).startRaft
	/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:401 +0x487

goroutine 30 [select]:
github.com/influxdb/influxdb/coordinator.(*RaftServer).raftLeaderLoop(0xc208072580, 0xc2080981c0, 0xc208098180)
	/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:460 +0x34c
created by github.com/influxdb/influxdb/coordinator.(*RaftServer).raftEventHandler
	/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:448 +0x268

goroutine 31 [select]:
github.com/influxdb/influxdb/_vendor/raft.(*server).send(0xc20808f440, 0xc0a4a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:630 +0x279
github.com/influxdb/influxdb/_vendor/raft.(*server).Do(0xc20808f440, 0x7fc72cc689c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:897 +0x7c
github.com/influxdb/influxdb/_vendor/raft.func·010()
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:828 +0xab
created by github.com/influxdb/influxdb/_vendor/raft.(*server).leaderLoop
	/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:829 +0x257

**Comment by francispereira** [comment]
Looks like something in the raft directory is causing the start up failure.

**Comment by francispereira** [comment]
If i move the raft directory away - InfluxDB starts up but all shards and databases are lost.
