### ISSUE TITLE
Panic when SELECTing and specifying two tag pairs

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdb/influxdb#1604]
We haven't been able to reproduce this reliably yet, but here's the query we're making from the shell:

`SELECT * FROM random_measurement_9 WHERE host = 'server0' AND region = 'west'`

which returns with: 

> ERR: Get http://localhost:8086/query?db=seedDatabase&q=SELECT+%2A+FROM+random_measurement_9+WHERE+host+%3D+%27server0%27+AND+region+%3D+%27west%27: EOF

The stack trace is:

```
[http] 127.0.0.1 - - [13/Feb/2015:17:40:11 -0500] GET /query?db=seedDatabase&q=SELECT+value+FROM+random_measurement_9+WHERE+host+%3D+%27server0%27 HTTP/1.1 200 402 - Go 1.1 package http 4525ff33-b3d1-11e4-936e-04013bd36401
[srvr] 2015/02/13 17:40:23 http: panic serving 127.0.0.1:60472: runtime error: index out of range
goroutine 24970 [running]:
net/http.func·011()
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb.seriesIDs.intersect(0xc20a4c8d08, 0x2, 0x2, 0xc2086f2480, 0xa, 0x10, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/database.go:691 +0x29a
github.com/influxdb/influxdb.(*Measurement).walkWhereForSeriesIds(0xc20a313620, 0x7f44ad415e00, 0xc20c58a450, 0xc20c58a480, 0x0, 0x0, 0x0, 0x14, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/database.go:333 +0x375
github.com/influxdb/influxdb.(*Measurement).seriesIDsAndFilters(0xc20a313620, 0xc208052780, 0x0, 0x0, 0x0, 0x4151b8)
        /home/mark/go/src/github.com/influxdb/influxdb/database.go:239 +0xd5
github.com/influxdb/influxdb.(*Measurement).tagSets(0xc20a313620, 0xc208052780, 0x0, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/database.go:256 +0x43
github.com/influxdb/influxdb.(*tx).CreateIterators(0xc20c1641e0, 0xc208052780, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/tx.go:130 +0xa8b
github.com/influxdb/influxdb/influxql.(*Planner).planRawQuery(0xc20a4ea7a0, 0xc20c164230, 0xc20c25a900, 0x0, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/influxql/engine.go:140 +0x109
github.com/influxdb/influxdb/influxql.(*Planner).planExpr(0xc20a4ea7a0, 0xc20c164230, 0x7f44ad415d10, 0xc20c25a900, 0x0, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/influxql/engine.go:110 +0xd3c
github.com/influxdb/influxdb/influxql.(*Planner).planField(0xc20a4ea7a0, 0xc20c164230, 0xc20a4ea7c0, 0x0, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/influxql/engine.go:104 +0x70
github.com/influxdb/influxdb/influxql.(*Planner).Plan(0xc20a4ea7a0, 0xc208052700, 0xc208044820, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/influxql/engine.go:93 +0x49c
github.com/influxdb/influxdb.(*Server).planSelectStatement(0xc208044820, 0xc208052680, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/server.go:2002 +0xadc
github.com/influxdb/influxdb.(*Server).executeSelectStatement(0xc208044820, 0xc208052680, 0xc20bfa812e, 0xc, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/server.go:1943 +0x40
github.com/influxdb/influxdb.(*Server).ExecuteQuery(0xc208044820, 0xc20a4ea640, 0xc20bfa812e, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/server.go:1876 +0x9da
github.com/influxdb/influxdb/httpd.(*Handler).serveQuery(0xc20808f410, 0x7f44ad4156f0, 0xc20a4ea5a0, 0xc2080e88f0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:142 +0x36e
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveQuery)·fm(0x7f44ad4156f0, 0xc20a4ea5a0, 0xc2080e88f0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:59 +0x4f
github.com/influxdb/influxdb/httpd.func·002(0x7f44ad4156f0, 0xc20a4ea5a0, 0xc2080e88f0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:394 +0x77
net/http.HandlerFunc.ServeHTTP(0xc208098d00, 0x7f44ad4156f0, 0xc20a4ea5a0, 0xc2080e88f0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·003(0x7f44b5026d40, 0xc20a4ea4e0, 0xc2080e88f0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:441 +0x288
net/http.HandlerFunc.ServeHTTP(0xc208092d10, 0x7f44b5026d40, 0xc20a4ea4e0, 0xc2080e88f0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·004(0x7f44b5026d40, 0xc20a4ea4e0, 0xc2080e88f0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:450 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc208098d20, 0x7f44b5026d40, 0xc20a4ea4e0, 0xc2080e88f0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0x7f44b5026d40, 0xc20a4ea4e0, 0xc2080e88f0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:483 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc208092d50, 0x7f44b5026d40, 0xc20a4ea4e0, 0xc2080e88f0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x7f44b5026d40, 0xc20a4ea4e0, 0xc2080e88f0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:493 +0x164
net/http.HandlerFunc.ServeHTTP(0xc208092d70, 0x7f44b5026d40, 0xc20a4ea4e0, 0xc2080e88f0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0x7f44b5026d40, 0xc20a4ea4c0, 0xc2080e88f0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:501 +0x123
net/http.HandlerFunc.ServeHTTP(0xc208098d40, 0x7f44b5026d40, 0xc20a4ea4c0, 0xc2080e88f0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·008(0x7f44b5026810, 0xc208045720, 0xc2080e88f0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:511 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc208098d60, 0x7f44b5026810, 0xc208045720, 0xc2080e88f0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc2080361e8, 0x7f44b5026810, 0xc208045720, 0xc2080e88f0)
        /home/mark/go/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc20808f410, 0x7f44b5026810, 0xc208045720, 0xc2080e88f0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:124 +0x4a
main.(*Handler).ServeHTTP(0xc20801f3a0, 0x7f44b5026810, 0xc208045720, 0xc2080e88f0)
        /home/mark/go/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:41 +0x1f5
net/http.serverHandler.ServeHTTP(0xc2080406c0, 0x7f44b5026810, 0xc208045720, 0xc2080e88f0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208045680)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1751 +0x35e
```

We were surprised to see this panic because, according to this snippet from the columnar output of `show series`, it looks like random_measurement_9 contains points matching both the tags host:server0 and region:west.

```
random_measurement_9            server2 west
random_measurement_9            server7 west
random_measurement_9            server8 west
random_measurement_9            server0 west
random_measurement_9            server9 west
random_measurement_9            server3 west
random_measurement_9            server5 west
random_measurement_9            server6 west
random_measurement_9            server4 west
random_measurement_9            server3 east
random_measurement_9            server1 west
random_measurement_9            server0 east
```

Other SELECT statements using multiple tags seems to complete correctly.

**Comment by mark-rushakoff** [comment]
Also, this was observed on commit 1fd766df955b70ffdb8149f3045fd39d9a1d6a23, and the server recovers from the panic and continues to fulfill later requests.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/commit/f4c9147d07eef5aa9862be929e33e3628abe6828 shows this issue has been fixed.
