### ISSUE TITLE
`SELECT * FROM $YOUR_MEASUREMENT WHERE time > now()` should return an empty result set, panics with a nil dereference

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdb/influxdb#1741]
When I run this query (substituting a real measurement), the server panics (but continues to run) with:

```
[srvr] 2015/02/25 14:49:50 http: panic serving 127.0.0.1:40451: runtime error: invalid memory address or nil pointer dereference
goroutine 3102 [running]:
net/http.func·011()
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb.(*Measurement).FieldByName(0x0, 0xc2080de110, 0x5, 0xc2080c3dc8)
        /home/mark/go/src/github.com/influxdb/influxdb/database.go:179 +0x10f
github.com/influxdb/influxdb.(*tx).FieldIDs(0xc20811fe00, 0xc208039c90, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/tx.go:233 +0x199
github.com/influxdb/influxdb/influxql.(*Planner).planRawQuery(0xc2080e7c60, 0xc20802e9b0, 0xc2080c3ec0, 0x0, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/influxql/engine.go:157 +0x163
github.com/influxdb/influxdb/influxql.(*Planner).Plan(0xc2080e7c60, 0xc20811a2d0, 0xc208032dd0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/influxql/engine.go:99 +0x4ab
github.com/influxdb/influxdb.(*Server).planSelectStatement(0xc208032dd0, 0xc20811a240, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/server.go:1850 +0x13a
github.com/influxdb/influxdb.(*Server).executeSelectStatement(0xc208032dd0, 0xc20811a240, 0xc208136e7e, 0xc, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/server.go:1788 +0xf2
github.com/influxdb/influxdb.(*Server).ExecuteQuery(0xc208032dd0, 0xc2080e7a80, 0xc208136e7e, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/server.go:1715 +0x9da
github.com/influxdb/influxdb/httpd.(*Handler).serveQuery(0xc2080ab560, 0x7fccbcdfa608, 0xc2080e79e0, 0xc2081189c0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:162 +0x36e
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveQuery)·fm(0x7fccbcdfa608, 0xc2080e79e0, 0xc2081189c0, 0x0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:61 +0x4f
github.com/influxdb/influxdb/httpd.func·003(0x7fccbcdfa608, 0xc2080e79e0, 0xc2081189c0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:483 +0x77
net/http.HandlerFunc.ServeHTTP(0xc20801f300, 0x7fccbcdfa608, 0xc2080e79e0, 0xc2081189c0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·004(0x7fccbcdf9db8, 0xc2080e78e0, 0xc2081189c0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:530 +0x288
net/http.HandlerFunc.ServeHTTP(0xc2080c2dd0, 0x7fccbcdf9db8, 0xc2080e78e0, 0xc2081189c0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0x7fccbcdf9db8, 0xc2080e78e0, 0xc2081189c0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:539 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc20801f320, 0x7fccbcdf9db8, 0xc2080e78e0, 0xc2081189c0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x7fccbcdf9db8, 0xc2080e78e0, 0xc2081189c0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:572 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc2080c2e10, 0x7fccbcdf9db8, 0xc2080e78e0, 0xc2081189c0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0x7fccbcdf9db8, 0xc2080e78e0, 0xc2081189c0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:582 +0x164
net/http.HandlerFunc.ServeHTTP(0xc2080c2e30, 0x7fccbcdf9db8, 0xc2080e78e0, 0xc2081189c0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·008(0x7fccbcdf9db8, 0xc2080e78c0, 0xc2081189c0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:590 +0x123
net/http.HandlerFunc.ServeHTTP(0xc20801f360, 0x7fccbcdf9db8, 0xc2080e78c0, 0xc2081189c0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·009(0x7fccbcdf97b0, 0xc208044dc0, 0xc2081189c0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:600 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc20801f380, 0x7fccbcdf97b0, 0xc208044dc0, 0xc2081189c0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208038170, 0x7fccbcdf97b0, 0xc208044dc0, 0xc2081189c0)
        /home/mark/go/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc2080ab560, 0x7fccbcdf97b0, 0xc208044dc0, 0xc2081189c0)
        /home/mark/go/src/github.com/influxdb/influxdb/httpd/handler.go:144 +0x4a
main.(*Handler).ServeHTTP(0xc20801f1e0, 0x7fccbcdf97b0, 0xc208044dc0, 0xc2081189c0)
        /home/mark/go/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:41 +0x1f5
net/http.serverHandler.ServeHTTP(0xc20802c600, 0x7fccbcdf97b0, 0xc208044dc0, 0xc2081189c0)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208044d20)
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /home/mark/.gvm/gos/go1.4/src/net/http/server.go:1751 +0x35e
```

I observed this behavior on both v0.9.0-rc4 and the more recent  241a514fbbef7ff2b2267eaea58d0291b469e301.

**Comment by kylezh** [comment]
I have a similar error. However,  the difference is that the result is not expected to be empty.

I noticed that the problem may be caused by "time >" and "time >=".

I tested with v0.9.0-rc4 by a query includes ```time > '2015-02-26T04:50:10Z'```

Does the patch c6bdd39 solves this problem too?
