### ISSUE TITLE
influxd will panic for corrupted data dir

### ISSUE THREAD

**Issue by sanga** [influxdb/influxdb#1753]
This is from running the tmux/3_shard test. I guess I had an unclear /tmp, for a previous run. Influx assumed that it's data dir existed, when it didn't and it paniced. So there's a missing check for the existence of config.Data.Dir somewhere apparently (it seems). It would be nicer to, log "dataDir missing" as opposed to panicing.

```
[srvr] 2015/02/26 08:11:23 influxdb started, version 0.9, commit unknown
[raft]  2015/02/26 08:11:23 log open: created at /tmp/influxdb/8086/broker/raft, with ID 1, term 1, last applied index of 1
[raft]  2015/02/26 08:11:23 log open: promoting to leader immediately
[raft]  2015/02/26 08:11:23 log state change: stopped => leader
[srvr] 2015/02/26 08:11:23 broker listening on :8086
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x90 pc=0x4041c6]

goroutine 1 [running]:
main.Run(0xc2080a6000, 0x0, 0x0, 0x8ecde0, 0x3, 0xc208044010, 0x0, 0xc20802b480)
        /home/sampti/Code/go/src/github.com/influxdb/influxdb/cmd/influxd/run.go:68 +0x8e6
main.execRun(0xc20800a010, 0x2, 0x2)
        /home/sampti/Code/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:118 +0x75e
main.main()
        /home/sampti/Code/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:70 +0x35b

goroutine 5 [chan receive]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc20803c060, 0x7fb177188c98, 0xc208044008)
        /home/sampti/Code/go/src/code.google.com/p/log4go/termlog.go:27 +0x7a
created by code.google.com/p/log4go.NewConsoleLogWriter
        /home/sampti/Code/go/src/code.google.com/p/log4go/termlog.go:19 +0x6b

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.func·002()
        /home/sampti/Code/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:199 +0xed
created by main.startProfiling
        /home/sampti/Code/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:202 +0x2dc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [select]:
github.com/influxdb/influxdb/raft.(*Log).applier(0xc20807a000, 0xc20803c2a0)
        /home/sampti/Code/go/src/github.com/influxdb/influxdb/raft/log.go:1124 +0x2f0
created by github.com/influxdb/influxdb/raft.(*Log).Open
        /home/sampti/Code/go/src/github.com/influxdb/influxdb/raft/log.go:276 +0x55e

goroutine 9 [runnable]:
sync.(*Mutex).Lock(0xc20807a000)
        /usr/local/go/src/sync/mutex.go:66 +0xd3
github.com/influxdb/influxdb/raft.(*Log).leaderLoop(0xc20807a000, 0xc20803c2a0, 0x0)
        /home/sampti/Code/go/src/github.com/influxdb/influxdb/raft/log.go:867 +0x161
github.com/influxdb/influxdb/raft.(*Log).stateLoop(0xc20807a000, 0xc20803c2a0, 0x3)
        /home/sampti/Code/go/src/github.com/influxdb/influxdb/raft/log.go:664 +0x28f
created by github.com/influxdb/influxdb/raft.(*Log).startStateLoop

...
```

**Comment by sanga** [comment]
And this is most likely because we have /tmp mounted as noexec - this bites me in the bum so many times... In any case, influxd shouldn't panic in this case, it should fail with some user understandable error.

So I changed the config to use a directory different to /tmp and it worked fine.

**Comment by sanga** [comment]
Apparently, influx assumes in this case influxd assumes it has created it's data directory when actually, this has failed

```
4312 11:30:21.863963789 5 influxd (7007) < stat res=-2(ENOENT) path=/tmp/influxdb/8086/data
```

**Comment by rothrock** [comment]
I'll look into this today.
