### ISSUE TITLE
error if replication number smaller than number of cluster nodes

### ISSUE THREAD

**Issue by kylezh** [influxdb/influxdb#1790]
Way to reproduce the problem:

1. Start nodes A,B,C to construct a cluster.
2. Create a database.
3. Create a policy on the database with replication 1.
4. Write a record to nodeA
5. Execute ```select * from xxx``` on nodeA

NodeA will produce the following error:

```
[srvr] 2015/02/28 18:01:23 http: panic serving 127.0.0.1:41975: runtime error: invalid memory address or nil pointer dereference
goroutine 21125 [running]:
net/http.func·011()
	/root/.gvm/gos/go1.4/src/net/http/server.go:1130 +0xbb
github.com/boltdb/bolt.(*DB).beginTx(0x0, 0x644083, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/db.go:356 +0x34c
github.com/boltdb/bolt.(*DB).Begin(0x0, 0x0, 0xc2084cc890, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/db.go:349 +0x6d
github.com/influxdb/influxdb.(*shardIterator).open(0xc2084a0b00, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tx.go:280 +0x57
github.com/influxdb/influxdb.(*tx).Open(0xc2084d0c00, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tx.go:50 +0xd2
github.com/influxdb/influxdb/influxql.(*Executor).Execute(0xc208031810, 0xc208495dd0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/influxql/engine.go:286 +0x67
github.com/influxdb/influxdb.(*Server).executeSelectStatement(0xc208034f70, 0xc208495dd0, 0xc2080f164e, 0x4, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/server.go:1842 +0x18f
github.com/influxdb/influxdb.(*Server).ExecuteQuery(0xc208034f70, 0xc2084c7400, 0xc2080f164e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/server.go:1761 +0xa6d
github.com/influxdb/influxdb/httpd.(*Handler).serveQuery(0xc20803ce10, 0x7f79be6ef4c0, 0xc2084c7360, 0xc2084b5790, 0x0)
	/root/go/src/github.com/influxdb/influxdb/httpd/handler.go:162 +0x36e
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveQuery)·fm(0x7f79be6ef4c0, 0xc2084c7360, 0xc2084b5790, 0x0)
	/root/go/src/github.com/influxdb/influxdb/httpd/handler.go:61 +0x4f
github.com/influxdb/influxdb/httpd.func·003(0x7f79be6ef4c0, 0xc2084c7360, 0xc2084b5790)
	/root/go/src/github.com/influxdb/influxdb/httpd/handler.go:483 +0x77
net/http.HandlerFunc.ServeHTTP(0xc2080b8020, 0x7f79be6ef4c0, 0xc2084c7360, 0xc2084b5790)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·004(0x7f79be6ef250, 0xc2084c7260, 0xc2084b5790)
	/root/go/src/github.com/influxdb/influxdb/httpd/handler.go:530 +0x288
net/http.HandlerFunc.ServeHTTP(0xc2080aa130, 0x7f79be6ef250, 0xc2084c7260, 0xc2084b5790)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0x7f79be6ef250, 0xc2084c7260, 0xc2084b5790)
	/root/go/src/github.com/influxdb/influxdb/httpd/handler.go:539 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc2080b8060, 0x7f79be6ef250, 0xc2084c7260, 0xc2084b5790)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x7f79be6ef250, 0xc2084c7260, 0xc2084b5790)
	/root/go/src/github.com/influxdb/influxdb/httpd/handler.go:572 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc2080aa170, 0x7f79be6ef250, 0xc2084c7260, 0xc2084b5790)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0x7f79be6ef250, 0xc2084c7260, 0xc2084b5790)
	/root/go/src/github.com/influxdb/influxdb/httpd/handler.go:582 +0x164
net/http.HandlerFunc.ServeHTTP(0xc2080aa190, 0x7f79be6ef250, 0xc2084c7260, 0xc2084b5790)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·008(0x7f79be6ef250, 0xc2084c7240, 0xc2084b5790)
	/root/go/src/github.com/influxdb/influxdb/httpd/handler.go:590 +0x123
net/http.HandlerFunc.ServeHTTP(0xc2080b8080, 0x7f79be6ef250, 0xc2084c7240, 0xc2084b5790)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·009(0x7f79be6eebf0, 0xc2084ce3c0, 0xc2084b5790)
	/root/go/src/github.com/influxdb/influxdb/httpd/handler.go:600 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc2080b80a0, 0x7f79be6eebf0, 0xc2084ce3c0, 0xc2084b5790)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc20803e038, 0x7f79be6eebf0, 0xc2084ce3c0, 0xc2084b5790)
	/root/go/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc20803ce10, 0x7f79be6eebf0, 0xc2084ce3c0, 0xc2084b5790)
	/root/go/src/github.com/influxdb/influxdb/httpd/handler.go:144 +0x4a
main.(*Handler).ServeHTTP(0xc2080b8a00, 0x7f79be6eebf0, 0xc2084ce3c0, 0xc2084b5790)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:41 +0x1f5
net/http.serverHandler.ServeHTTP(0xc20802e8a0, 0x7f79be6eebf0, 0xc2084ce3c0, 0xc2084b5790)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2084ce320)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/root/.gvm/gos/go1.4/src/net/http/server.go:1751 +0x35e
```

**Comment by otoolep** [comment]
As called out in the blog post announcing 0.9.0 testing builds, replication factor must equal the number of nodes in your cluster. 

This restriction will be addressed soon, however.

**Comment by kylezh** [comment]
Which version will this restriction be removed? Can it be solved in 0.9.x?

And what do you mean by ```the number of nodes```? Does it mean the number of ```broker node``` or the number of ```data node```?

And is it possible to have a different number of ```broker node``` and ```data node```?

**Comment by otoolep** [comment]
Please read the blog post if you have not done so already. It will most certainly be addressed soon, and in 0.9. The build you are running is an early release, just for testing.

**Comment by otoolep** [comment]
Please read the 0.9 docs to learn more about clustering and the different node types.

**Comment by otoolep** [comment]
I should hare included the links: 

http://influxdb.com/docs/v0.9/introduction/getting_started.html

http://influxdb.com/docs/v0.9/advanced_topics/clustering.html

It would probably be best if you direct further general questions about the design to the Google Groups. 

https://groups.google.com/forum/m/#!forum/influxdb

**Comment by kylezh** [comment]
I see. Thanks a lot :)

**Comment by beckettsean** [comment]
should be fixed with recent distributed query work
