### ISSUE TITLE
WHERE integration test failing occasionally 

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1922]
```
TEST: 23: where on a tag, field and time
[http] 2015/03/11 20:00:47 127.0.0.1 - - [11/Mar/2015:20:00:47 +0000] POST /write HTTP/1.1 200 23 - Go 1.1 package http 4f20c4b8-c829-11e4-9586-b20dda235800
BODY:  
panic: test timed out after 1m0s

goroutine 11993 [running]:
testing.func·008()
	/usr/local/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0x9cc010, 0xdad7a0, 0x7, 0x7, 0xc20802b401)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc2080363c0, 0xdb96e0)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/influxdb/influxdb/cmd/influxd/_test/_testmain.go:66 +0x1d5

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 11 [sleep]:
github.com/influxdb/influxdb/cmd/influxd_test.write(0xc20805a1b0, 0xc2080ab760, 0xc20806f440, 0x226)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/cmd/influxd/server_integration_test.go:172 +0x6fc
github.com/influxdb/influxdb/cmd/influxd_test.runTestsData(0xc20805a1b0, 0x9525b0, 0x19, 0xc2080442e8, 0x1, 0x1, 0x8e3380, 0x4, 0x8e33a0, 0x4, ...)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/cmd/influxd/server_integration_test.go:739 +0x9bd
github.com/influxdb/influxdb/cmd/influxd_test.TestSingleServer(0xc20805a1b0)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/cmd/influxd/server_integration_test.go:767 +0x38d
testing.tRunner(0xc20805a1b0, 0xdad800)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 12 [select]:
github.com/influxdb/influxdb/raft.(*Log).applier(0xc2080623c0, 0xc208032660)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:1137 +0x2f0
created by github.com/influxdb/influxdb/raft.(*Log).Open
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:277 +0x561

goroutine 13 [select]:
github.com/influxdb/influxdb/raft.(*Log).leaderLoop(0xc2080623c0, 0xc208032660, 0x0)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:881 +0x625
github.com/influxdb/influxdb/raft.(*Log).stateLoop(0xc2080623c0, 0xc208032660, 0x3, 0xc2080326c0)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:666 +0x3ea
created by github.com/influxdb/influxdb/raft.(*Log).startStateLoop
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:632 +0x98

goroutine 11991 [sleep]:
github.com/influxdb/influxdb/raft.func·001()
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/clock.go:66 +0x33
created by github.com/influxdb/influxdb/raft.newClockChan
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/clock.go:66 +0xfb

goroutine 18 [IO wait]:
net.(*pollDesc).Wait(0xc208010fb0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010fb0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010f50, 0x0, 0x7f8ec1b2ebe0, 0xc2083ca038)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208044688, 0xc208054e08, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208044688, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc208032300, 0x7f8ec1b2f7e0, 0xc208044688, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f8ec1b2f7e0, 0xc208044688, 0x7f8ec1b30920, 0xc2080abba0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/cmd/influxd.func·003()
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/cmd/influxd/run.go:68 +0x77
created by github.com/influxdb/influxdb/cmd/influxd.Run
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/cmd/influxd/run.go:68 +0x782

goroutine 19 [select]:
github.com/influxdb/influxdb.(*Broker).continuousQueryLoop(0xc2080b0210, 0xc2080329c0)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/broker.go:75 +0x10a
created by github.com/influxdb/influxdb.(*Broker).RunContinuousQueryLoop
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/broker.go:55 +0x78

goroutine 11992 [sleep]:
github.com/influxdb/influxdb/raft.(*Log).heartbeater(0xc2080623c0, 0x1, 0xc2083c70a0, 0xc2080ab1e0, 0xc2080327e0)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:938 +0xe28
created by github.com/influxdb/influxdb/raft.(*Log).leaderLoop
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/raft/log.go:878 +0x20a

goroutine 23 [select]:
github.com/influxdb/influxdb/messaging.(*Client).streamFromURL(0xc208032420, 0xc208011dc0, 0xc208032540, 0x0, 0x0)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/client.go:455 +0x829
github.com/influxdb/influxdb/messaging.(*Client).streamer(0xc208032420, 0xc208032540)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/client.go:407 +0x150
created by github.com/influxdb/influxdb/messaging.(*Client).Open
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/client.go:161 +0x27e

goroutine 48 [select]:
net/http.(*persistConn).writeLoop(0xc2080ae9a0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 47 [IO wait]:
net.(*pollDesc).Wait(0xc208011d40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011d40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208011ce0, 0xc2080eb000, 0x1000, 0x1000, 0x0, 0x7f8ec1b2ebe0, 0xc2083ca128)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208044370, 0xc2080eb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f8ec1b30b10, 0xc208044370, 0xc2080ae9f8, 0xc2080eb000, 0x1000, 0x1000, 0x7fb6c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080abce0, 0xc2080eb000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208033e00)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208033e00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080ae9a0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 36 [select]:
net/http.(*persistConn).readLoop(0xc2080ae2c0)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 43 [select]:
github.com/influxdb/influxdb.func·009()
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/server.go:297 +0x109
created by github.com/influxdb/influxdb.(*Server).StartRetentionPolicyEnforcement
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/server.go:304 +0x1dd

goroutine 29 [chan receive]:
github.com/influxdb/influxdb/messaging.(*Replica).WriteTo(0xc20802ed80, 0x7f8ec1b30f28, 0xc208030fa0, 0x7f8ec1b30f28, 0x0, 0x0)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/broker.go:1041 +0x6d3
github.com/influxdb/influxdb/messaging.(*Handler).stream(0xc2080b6100, 0x7f8ec1b30df8, 0xc208030fa0, 0xc208035e10)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/handler.go:101 +0x1c5
github.com/influxdb/influxdb/messaging.(*Handler).ServeHTTP(0xc2080b6100, 0x7f8ec1b30df8, 0xc208030fa0, 0xc208035e10)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/handler.go:54 +0x1c8
github.com/influxdb/influxdb/cmd/influxd.(*Handler).ServeHTTP(0xc2080abba0, 0x7f8ec1b30df8, 0xc208030fa0, 0xc208035e10)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:32 +0x248
net/http.serverHandler.ServeHTTP(0xc208032300, 0x7f8ec1b30df8, 0xc208030fa0, 0xc208035e10)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080305a0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 41 [select]:
github.com/influxdb/influxdb/messaging.(*Client).streamFromURL(0xc208032ae0, 0xc2080ec380, 0xc208032d20, 0x0, 0x0)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/client.go:455 +0x829
github.com/influxdb/influxdb/messaging.(*Client).streamer(0xc208032ae0, 0xc208032d20)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/client.go:407 +0x150
created by github.com/influxdb/influxdb/messaging.(*Client).Open
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/client.go:161 +0x27e

goroutine 31 [IO wait]:
net.(*pollDesc).Wait(0xc2080113a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080113a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208011340, 0xc2080c4000, 0x1000, 0x1000, 0x0, 0x7f8ec1b2ebe0, 0xc2080b7df8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208044198, 0xc2080c4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc208030868, 0xc2080c4000, 0x1000, 0x1000, 0xc20805c858, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080aabe0, 0xc2080c4000, 0x1000, 0x1000, 0x4044d4, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc208033440)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208033440, 0xc20809f90a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc208033440, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080b0180, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080b0180, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc208033440, 0xc2080f6000, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc208030820, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc208030820)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 32 [select]:
net/http.(*persistConn).readLoop(0xc2080ae420)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 33 [select]:
net/http.(*persistConn).writeLoop(0xc2080ae420)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 42 [select]:
github.com/influxdb/influxdb.(*Server).processor(0xc2080b8000, 0x7f8ec1b30948, 0xc208032ae0, 0xc208032d80)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/server.go:2816 +0x2aa
created by github.com/influxdb/influxdb.(*Server).setClient
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/server.go:447 +0x132

goroutine 37 [select]:
net/http.(*persistConn).writeLoop(0xc2080ae2c0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 44 [select]:
github.com/influxdb/influxdb.func·011()
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/server.go:356 +0x116
created by github.com/influxdb/influxdb.(*Server).StartShardGroupsPreCreate
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/server.go:363 +0x1dd

goroutine 49 [IO wait]:
net.(*pollDesc).Wait(0xc2080ec140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080ec140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080ec0e0, 0xc2080c2000, 0x1000, 0x1000, 0x0, 0x7f8ec1b2ebe0, 0xc2083ca078)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208044378, 0xc2080c2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc208030c28, 0xc2080c2000, 0x1000, 0x1000, 0xc00000000000000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2080abd00, 0xc2080c2000, 0x1000, 0x1000, 0x81, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2080333e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2080333e0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2080333e0, 0x0, 0x0, 0x0, 0xc207fef400, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20810b080, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20810b080, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2080333e0, 0xc20829a5b0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc208030be0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc208030be0)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 51 [chan send]:
github.com/influxdb/influxdb/messaging.func·012()
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/client.go:450 +0x1a4
created by github.com/influxdb/influxdb/messaging.(*Client).streamFromURL
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/client.go:452 +0x64a

goroutine 52 [IO wait]:
net.(*pollDesc).Wait(0xc208011170, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011170, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208011110, 0xc2080d2000, 0x1000, 0x1000, 0x0, 0x7f8ec1b2ebe0, 0xc2083ca210)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080441b8, 0xc2080d2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f8ec1b30b10, 0xc2080441b8, 0xc2080ae318, 0xc2080d2000, 0x1000, 0x1000, 0x74, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080aad60, 0xc2080d2000, 0x1000, 0x1000, 0x74, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208033620)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208033620, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
net/http/internal.readLine(0xc208033620, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/internal/chunked.go:110 +0x5a
net/http/internal.(*chunkedReader).beginChunk(0xc20800ba10)
	/usr/local/go/src/net/http/internal/chunked.go:47 +0x46
net/http/internal.(*chunkedReader).Read(0xc20800ba10, 0xc208126200, 0x16, 0x16, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/internal/chunked.go:77 +0xbb
net/http.(*body).readLocked(0xc208084c00, 0xc208126200, 0x16, 0x16, 0xffffffff, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:584 +0x7a
net/http.(*body).Read(0xc208084c00, 0xc208126200, 0x16, 0x16, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:579 +0x115
net/http.(*bodyEOFSignal).Read(0xc208084c40, 0xc208126200, 0x16, 0x16, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1193 +0x285
io.ReadAtLeast(0x7f8ec1b310d0, 0xc208084c40, 0xc208126200, 0x16, 0x16, 0x16, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f8ec1b310d0, 0xc208084c40, 0xc208126200, 0x16, 0x16, 0x58, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
github.com/influxdb/influxdb/messaging.(*MessageDecoder).Decode(0xc2080b7e80, 0xc20810b200, 0x0, 0x0)
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/broker.go:1161 +0xa4
github.com/influxdb/influxdb/messaging.func·012()
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/client.go:442 +0x113
created by github.com/influxdb/influxdb/messaging.(*Client).streamFromURL
	/home/ubuntu/.go_project/src/github.com/influxdb/influxdb/messaging/client.go:452 +0x64a

goroutine 7179 [IO wait]:
net.(*pollDesc).Wait(0xc2083a4990, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2083a4990, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2083a4930, 0xc2083e9000, 0x1000, 0x1000, 0x0, 0x7f8ec1b2ebe0, 0xc2083cbcd8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20813fa70, 0xc2083e9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f8ec1b30b10, 0xc20813fa70, 0xc2080af028, 0xc2083e9000, 0x1000, 0x1000, 0xc208084340, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2083c2540, 0xc2083e9000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2081259e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2081259e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080aefd0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 7087 [IO wait]:
net.(*pollDesc).Wait(0xc2083c72c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2083c72c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2083c7260, 0xc208122000, 0x1000, 0x1000, 0x0, 0x7f8ec1b2ebe0, 0xc2083ca0c0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20813f558, 0xc208122000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f8ec1b30b10, 0xc20813f558, 0xc2080aeec8, 0xc208122000, 0x1000, 0x1000, 0xc20816e540, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208127b80, 0xc208122000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2080c13e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2080c13e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080aee70)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 7180 [select]:
net/http.(*persistConn).writeLoop(0xc2080aefd0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 7086 [IO wait]:
net.(*pollDesc).Wait(0xc2083c7330, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2083c7330, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2083c72d0, 0xc208082000, 0x1000, 0x1000, 0x0, 0x7f8ec1b2ebe0, 0xc20812df18)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20813f550, 0xc208082000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc208150408, 0xc208082000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc208127b20, 0xc208082000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2080c1380)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2080c1380, 0xc208167b0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2080c1380, 0x0, 0x0, 0x0, 0xc207fea100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20815e5a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20815e5a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2080c1380, 0xc208035380, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc2081503c0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc2081503c0)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 7181 [IO wait]:
net.(*pollDesc).Wait(0xc2083a4060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2083a4060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2083a4000, 0xc2083d3000, 0x1000, 0x1000, 0x0, 0x7f8ec1b2ebe0, 0xc2083cbc78)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20813e008, 0xc2083d3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc208150048, 0xc2083d3000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2083c2000, 0xc2083d3000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc208124000)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208124000, 0xc20816db0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc208124000, 0x0, 0x0, 0x0, 0xc2080a8600, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20815e090, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20815e090, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc208124000, 0xc20829be10, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc208150000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc208150000)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 7088 [select]:
net/http.(*persistConn).writeLoop(0xc2080aee70)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
FAIL	github.com/influxdb/influxdb/cmd/influxd	60.009s
```

**Comment by otoolep** [comment]
@pauldix

**Comment by beckettsean** [comment]
@otoolep test still failing intermittently or can we close this issue?

**Comment by otoolep** [comment]
This can be closed, haven't seen it in quite a while.

**Comment by otoolep** [comment]
Thanks @beckettsean
