### ISSUE TITLE
Delete from <foo> panics

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#1933]
Issuing a command like:

`delete from foo`

results in the following panic:

```sh
[srvr] 2015/03/12 15:03:58 http: panic serving 127.0.0.1:50454: unsupported statement type: *influxql.DeleteStatement
goroutine 966 [running]:
net/http.func·011()
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb.(*Server).ExecuteQuery(0xc2080a8000, 0xc20801ede0, 0xc20803bc2e, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/server.go:1975 +0x7e6
github.com/influxdb/influxdb/httpd.(*Handler).serveQuery(0xc2080c4c40, 0xa63ee8, 0xc20801ed80, 0xc208033110, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/httpd/handler.go:172 +0x36e
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveQuery)·fm(0xa63ee8, 0xc20801ed80, 0xc208033110, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/httpd/handler.go:66 +0x4f
github.com/influxdb/influxdb/httpd.func·004(0xa63ee8, 0xc20801ed80, 0xc208033110)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/httpd/handler.go:516 +0x77
net/http.HandlerFunc.ServeHTTP(0xc20801f2a0, 0xa63ee8, 0xc20801ed80, 0xc208033110)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0xa63d98, 0xc20801ec40, 0xc208033110)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/httpd/handler.go:563 +0x288
net/http.HandlerFunc.ServeHTTP(0xc2080bcd40, 0xa63d98, 0xc20801ec40, 0xc208033110)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0xa63d98, 0xc20801ec40, 0xc208033110)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/httpd/handler.go:572 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc20801f2c0, 0xa63d98, 0xc20801ec40, 0xc208033110)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0xa63d98, 0xc20801ec40, 0xc208033110)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/httpd/handler.go:605 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc2080bcd80, 0xa63d98, 0xc20801ec40, 0xc208033110)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·008(0xa63d98, 0xc20801ec40, 0xc208033110)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/httpd/handler.go:615 +0x164
net/http.HandlerFunc.ServeHTTP(0xc2080bcda0, 0xa63d98, 0xc20801ec40, 0xc208033110)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·009(0xa63d98, 0xc20801ec20, 0xc208033110)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/httpd/handler.go:623 +0x123
net/http.HandlerFunc.ServeHTTP(0xc20801f2e0, 0xa63d98, 0xc20801ec20, 0xc208033110)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·010(0xa63880, 0xc208070960, 0xc208033110)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/httpd/handler.go:633 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc20801f300, 0xa63880, 0xc208070960, 0xc208033110)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc2080381b0, 0xa63880, 0xc208070960, 0xc208033110)
        /Users/corylanou/go/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc2080c4c40, 0xa63880, 0xc208070960, 0xc208033110)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/httpd/handler.go:154 +0x4a
main.(*Handler).ServeHTTP(0xc20801ee00, 0xa63880, 0xc208070960, 0xc208033110)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:41 +0x1f5
net/http.serverHandler.ServeHTTP(0xc208072540, 0xa63880, 0xc208070960, 0xc208033110)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208070780)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e
```

**Comment by nemesisdesign** [comment]
Same here, (rc11):
```
> select * from test_metric where object_id = '8'
name: test_metric
-----------------
time				value
2015-03-13T11:40:21.10873548Z	1
2015-03-13T11:40:23.09119752Z	2
2015-03-13T11:40:24.9824534Z	3
2015-03-13T11:40:26.34074356Z	4

> delete from test_metric where object_id = '8'
ERR: Get http://localhost:8086/query?db=nodeshot&q=delete+from+test_metric+where+object_id+%3D+%278%27: EOF
```
