### ISSUE TITLE
InfluxDB doesn't appear to respond after init.d start

### ISSUE THREAD

**Issue by betandr** [influxdb/influxdb#2013]
I seem to be having an issue on an EC2 instance, starting Influx on that box. 

Full uname output is:
```
Linux i-1f4137fb 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
Running `sudo /etc/init.d/influxdb start` gives:

```
Setting ulimit -n 65536
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
```

Running `nc -vz localhost 8086` on that local box yields:

```connect to localhost port 8086 (tcp) failed: Connection refused```

When I try to start using `sudo influxdb -config=/opt/influxdb/shared/config.toml`

I get:

```
panic: mkdir /opt/influxdb/shared/data: file exists

goroutine 1 [running]:
main.start(0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/daemon/influxd.go:183 +0x1165
main.main()
	/root/go/src/github.com/influxdb/influxdb/daemon/influxd.go:73 +0x1f

goroutine 5 [syscall]:
os/signal.loop()
	/root/.gvm/gos/go1.4/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/root/.gvm/gos/go1.4/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc20804e060, 0x7fc2d34dfdb8, 0xc20802a008)
	/root/go/src/code.google.com/p/log4go/termlog.go:27 +0x7a
created by code.google.com/p/log4go.NewConsoleLogWriter
	/root/go/src/code.google.com/p/log4go/termlog.go:19 +0x6b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/root/.gvm/gos/go1.4/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [select]:
code.google.com/p/log4go.func·002()
	/root/go/src/code.google.com/p/log4go/filelog.go:84 +0xa53
created by code.google.com/p/log4go.NewFileLogWriter
	/root/go/src/code.google.com/p/log4go/filelog.go:116 +0x3da
```

What should I try?

**Comment by betandr** [comment]
Turned out it was me, creating the data directory with restrictive permissions and Influx was failing to start, although it wasn't reporting that...
