### ISSUE TITLE
panic when swapping the order of AND expressions

### ISSUE THREAD

**Issue by dstrek** [influxdb/influxdb#2043]
```
> select count(value) from impressions where app = 'testapp' and time > now() - 1d
ERR: Get http://localhost:8086/query?db=test&q=select+count%28value%29+from+impressions+where+app+%3D+%27testapp%27+and+time+%3E+now%28%29+-+1d: EOF

> select count(value) from impressions where time > now() - 1d and app = 'testapp'
name: impressions
-----------------
time				count
2015-03-20T00:00:00.037222556Z   11698
```

panic log
```
[srvr] 2015/03/21 16:25:55 http: panic serving 127.0.0.1:61859: runtime error: invalid memory address or nil pointer dereference
goroutine 8110344 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb.(*Measurement).idsForExpr(0xc20806c600, 0xc237f842d0, 0x0, 0x0, 0x0, 0x958beb01, 0x0, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/database.go:365 +0x70e
github.com/influxdb/influxdb.(*Measurement).walkWhereForSeriesIds(0xc20806c600, 0xb67d88, 0xc237f842d0, 0xc237f84390, 0x0, 0x0, 0x0, 0x958bea01, 0x0, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/database.go:480 +0x167
github.com/influxdb/influxdb.(*Measurement).walkWhereForSeriesIds(0xc20806c600, 0xb67d88, 0xc237f84300, 0xc237f84390, 0x0, 0x0, 0x0, 0x2435138, 0x0, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/database.go:418 +0x29f
github.com/influxdb/influxdb.(*Measurement).filters(0xc20806c600, 0xc208096cc0, 0xc237f885e8)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/database.go:292 +0xac
github.com/influxdb/influxdb.(*Measurement).tagSets(0xc20806c600, 0xc208096cc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/database.go:313 +0x67
github.com/influxdb/influxdb.(*tx).CreateMapReduceJobs(0xc210e6e000, 0xc208096cc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/tx.go:120 +0xe28
github.com/influxdb/influxdb/influxql.(*Planner).Plan(0xc20d9fdac0, 0xc208096cc0, 0xc20807c0e0, 0x0, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/influxql/engine.go:590 +0x2e4
github.com/influxdb/influxdb.(*Server).planSelectStatement(0xc20807c0e0, 0xc208096cc0, 0x0, 0x0, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/server.go:2236 +0x13a
github.com/influxdb/influxdb.(*Server).executeSelectStatement(0xc20807c0e0, 0xc208096cc0, 0xc2380f9f0e, 0x4, 0x0, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/server.go:2073 +0xf2
github.com/influxdb/influxdb.(*Server).ExecuteQuery(0xc20807c0e0, 0xc20d9fd980, 0xc2380f9f0e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/server.go:1992 +0xade
github.com/influxdb/influxdb/httpd.(*Handler).serveQuery(0xc20d57e4c0, 0x2430f80, 0xc20d9fd8e0, 0xc2112ba410, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/httpd/handler.go:189 +0x3dc
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveQuery)·fm(0x2430f80, 0xc20d9fd8e0, 0xc2112ba410, 0x0)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/httpd/handler.go:66 +0x4f
github.com/influxdb/influxdb/httpd.func·005(0x2430f80, 0xc20d9fd8e0, 0xc2112ba410)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/httpd/handler.go:655 +0x77
net/http.HandlerFunc.ServeHTTP(0xc20a7156c0, 0x2430f80, 0xc20d9fd8e0, 0xc2112ba410)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x2430e30, 0xc20d9fd7e0, 0xc2112ba410)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/httpd/handler.go:702 +0x288
net/http.HandlerFunc.ServeHTTP(0xc20d672900, 0x2430e30, 0xc20d9fd7e0, 0xc2112ba410)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0x2430e30, 0xc20d9fd7e0, 0xc2112ba410)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/httpd/handler.go:711 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc20a715700, 0x2430e30, 0xc20d9fd7e0, 0xc2112ba410)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·008(0x2430e30, 0xc20d9fd7e0, 0xc2112ba410)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/httpd/handler.go:744 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc20d672970, 0x2430e30, 0xc20d9fd7e0, 0xc2112ba410)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·009(0x2430e30, 0xc20d9fd7e0, 0xc2112ba410)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/httpd/handler.go:754 +0x164
net/http.HandlerFunc.ServeHTTP(0xc20d6729b0, 0x2430e30, 0xc20d9fd7e0, 0xc2112ba410)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·010(0x2430e30, 0xc20d9fd7c0, 0xc2112ba410)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/httpd/handler.go:762 +0x123
net/http.HandlerFunc.ServeHTTP(0xc20a715720, 0x2430e30, 0xc20d9fd7c0, 0xc2112ba410)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·011(0x23dbc08, 0xc23352cb40, 0xc2112ba410)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/httpd/handler.go:772 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc20a715740, 0x23dbc08, 0xc23352cb40, 0xc2112ba410)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208039718, 0x23dbc08, 0xc23352cb40, 0xc2112ba410)
	/Users/dstrek/www/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc20d57e4c0, 0x23dbc08, 0xc23352cb40, 0xc2112ba410)
	/Users/dstrek/www/src/github.com/influxdb/influxdb/httpd/handler.go:163 +0x4a
main.(*Handler).ServeHTTP(0xc2080ea4c0, 0x23dbc08, 0xc23352cb40, 0xc2112ba410)
	/Users/dstrek/www/src/github.com/fancysupport/influxdb/cmd/influxd/handler.go:41 +0x1f5
net/http.serverHandler.ServeHTTP(0xc20806c540, 0x23dbc08, 0xc23352cb40, 0xc2112ba410)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc23352caa0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e
```

**Comment by otoolep** [comment]
I cannot reproduce this. Can you please show this happening with a sequence of curl commands? Start by showing creation of a new database, insertion of a single point, and the query that causes the panic.

**Comment by neonstalwart** [comment]
#2184, #2268 dupes???

**Comment by dgnorton** [comment]
@dstrek I think #2268 fixed this one.  Can you retest?
