### ISSUE TITLE
Metastore Panic

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#2083]
```
[server] 2015/03/26 09:42:48 unauthorized request | user: "user" | query: "DROP DATABASE foo" | database ""\n
[server] 2015/03/26 09:42:48 unauthorized request | user: "user" | query: "CREATE CONTINUOUS QUERY myquery ON foo BEGIN SELECT count() INTO measure1 ON bar FROM myseries END" | database ""\n
[server] 2015/03/26 09:42:49 unauthorized request | user: "user" | query: "SELECT count() FROM cpu;\nSELECT count() INTO tmp FROM cpu" | database "foo"\n
2015/03/26 09:42:49 Loading metadata index for foo
2015/03/26 09:42:49 Loading metadata index for foo
2015/03/26 09:42:49 Loading metadata index for bar
2015/03/26 09:42:49 Loading metadata index for foo
panic: assert failed: metastore index replay: meta=3, index=3

goroutine 57 [running]:
github.com/influxdb/influxdb.assert(0xc2080a1c00, 0x526b90, 0x29, 0xc2080a1c40, 0x2, 0x2)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/influxdb.go:183 +0xcf
github.com/influxdb/influxdb.funcÂ·006(0xc20803e090, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/metastore.go:80 +0x1ce
github.com/influxdb/influxdb.funcÂ·004(0xc20801eb60, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/metastore.go:59 +0x7f
github.com/boltdb/bolt.(*DB).Update(0xc208036b60, 0xc2080a1d20, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/boltdb/bolt/db.go:505 +0xde
github.com/influxdb/influxdb.(*metastore).update(0xc20803e1b0, 0xc2080a1d98, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/metastore.go:59 +0x5d
github.com/influxdb/influxdb.(*metastore).mustUpdate(0xc20803e1b0, 0x3, 0xc2080a1e30, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/metastore.go:92 +0x99
github.com/influxdb/influxdb.(*Server).applyCreateUser(0xc208066800, 0xc20808f380, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/server.go:1230 +0x2e4
github.com/influxdb/influxdb.funcÂ·044()
        /Users/corylanou/go/src/github.com/influxdb/influxdb/server.go:3266 +0x383
github.com/influxdb/influxdb.(*Server).processor(0xc208066800, 0x7ae6c0, 0xc20800bf00, 0xc208042540)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/server.go:3304 +0x163
created by github.com/influxdb/influxdb.(*Server).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/server.go:224 +0x8fa

goroutine 1 [chan receive]:
testing.RunTests(0x576368, 0x6c8d80, 0x56, 0x56, 0x40d01)
        /usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc2080403c0, 0x6d33c0)
        /usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:485 +0x6c
main.main()
        github.com/influxdb/influxdb/_test/_testmain.go:224 +0x1d5

goroutine 55 [runnable]:
sync.(*RWMutex).RLock(0xc208066800)
        /usr/local/Cellar/go/1.4.2/libexec/src/sync/rwmutex.go:36 +0x5f
github.com/influxdb/influxdb.(*Server).Path(0xc208066800, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/server.go:151 +0x41
github.com/influxdb/influxdb_test.(*Server).Close(0xc20803e1b8)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/server_test.go:1944 +0x2b
github.com/influxdb/influxdb_test.TestServer_AdminUserExists(0xc208052cf0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/server_test.go:474 +0x463
testing.tRunner(0xc208052cf0, 0x6c8ff0)
        /usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:555 +0xa8b

goroutine 58 [select]:
github.com/influxdb/influxdb.(*Server).processor(0xc208066800, 0x7ae6c0, 0xc20800ab20, 0xc208042360)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/server.go:3232 +0x176
created by github.com/influxdb/influxdb.(*Server).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/server.go:224 +0x8fa
FAIL    github.com/influxdb/influxdb    2.044s
```

**Comment by otoolep** [comment]
Not applicable in new clustering implementation.

@corylanou -- please re-open if I am mistaken.
