### ISSUE TITLE
InfluxDB panic after DROP SERIES WHERE

### ISSUE THREAD

**Issue by lburg** [influxdb/influxdb#2138]
I used curl to POST some data into InfluxDB like so:

```
curl -XPOST -v 'http://localhost:8086/write' -d '
{
    "database": "mydb",
    "tags": {"quality": "2", "version": "v1"},
    "points": [
        {
            "name": "test_value",
            "timestamp": 1428071525000, "precision": "ms",
            "fields": {
                "value": 0.64
            }
        },
        {
            "name": "test_value",
            "timestamp": 1428071526000, "precision": "ms",
            "fields": {
                "value": 0.17
            }
        },
        {
            "name": "test_value",
            "timestamp": 1428071527000, "precision": "ms",
            "fields": {
                "value": 0.68
            }
        }
    ]
}
'
```

This worked well and I could see my data from the web interface using `select * from test_value;`. I then decided to drop the serie by issuing the query `DROP SERIES WHERE quality = '2'`, and now InfluxDB stopped responding.

Looking into `/var/log/influxdb/influxdb.log`, here is the panic log:

```
[srvr] 2015/04/01 17:03:35 http: panic serving [::1]:33622: unsupported value type: <nil>
goroutine 17427096 [running]:
net/http.func·011()
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb.(*FieldCodec).EncodeFields(0xc20fcc2e90, 0xc208aaf0b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/database.go:798 +0xae4
github.com/influxdb/influxdb.func·035(0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:1727 +0x5fd
github.com/influxdb/influxdb.(*Server).WriteSeries(0xc208062800, 0xc208891c40, 0x9, 0xc20809b320, 0x7, 0xc216b60000, 0x2b368, 0x2e124, 0x0, 0x0, ...)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:1745 +0xa80
github.com/influxdb/influxdb/httpd.(*Handler).serveWrite(0xc208037340, 0x7fa887cf6880, 0xc208dd75e0, 0xc208530410, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:375 +0xc20
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveWrite)·fm(0x7fa887cf6880, 0xc208dd75e0, 0xc208530410, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:73 +0x4f
github.com/influxdb/influxdb/httpd.func·004(0x7fa887cf6880, 0xc208dd75e0, 0xc208530410)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:649 +0x77
net/http.HandlerFunc.ServeHTTP(0xc2080c6640, 0x7fa887cf6880, 0xc208dd75e0, 0xc208530410)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0x7fa887cf6880, 0xc208dd75e0, 0xc208530410)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:689 +0xd9
net/http.HandlerFunc.ServeHTTP(0xc20809b680, 0x7fa887cf6880, 0xc208dd75e0, 0xc208530410)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x7fa887cf6880, 0xc208dd75e0, 0xc208530410)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:705 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc2080c6660, 0x7fa887cf6880, 0xc208dd75e0, 0xc208530410)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0x7fa887cf6880, 0xc208dd75e0, 0xc208530410)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:738 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc20809b6c0, 0x7fa887cf6880, 0xc208dd75e0, 0xc208530410)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·008(0x7fa887cf6880, 0xc208dd75e0, 0xc208530410)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:748 +0x164
net/http.HandlerFunc.ServeHTTP(0xc20809b6e0, 0x7fa887cf6880, 0xc208dd75e0, 0xc208530410)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·009(0x7fa887cf6880, 0xc208dd75c0, 0xc208530410)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:756 +0x123
net/http.HandlerFunc.ServeHTTP(0xc2080c6680, 0x7fa887cf6880, 0xc208dd75c0, 0xc208530410)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·010(0x7fa887ce93c8, 0xc2088fc280, 0xc208530410)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:766 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc2080c66a0, 0x7fa887ce93c8, 0xc2088fc280, 0xc208530410)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208038220, 0x7fa887ce93c8, 0xc2088fc280, 0xc208530410)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc208037340, 0x7fa887ce93c8, 0xc2088fc280, 0xc208530410)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:157 +0x4a
main.(*Handler).ServeHTTP(0xc20801f8e0, 0x7fa887ce93c8, 0xc2088fc280, 0xc208530410)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:41 +0x1f5
net/http.serverHandler.ServeHTTP(0xc20800c6c0, 0x7fa887ce93c8, 0xc2088fc280, 0xc208530410)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2088fc1e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e
```

I restarted InfluxDB using `service` and I can see it's running because I can connect to the web interface, I see it when running the command `lsof -i | grep influxdb`, and running `service influxdb status` says that the process is running.

However if I try to issue any query through the web interface and check the network tab of my browser's console, I can't see a response. Trying to use curl again to POST the same data also hangs waiting for a response. Also, I don't get any more log info written, it's as if the process wasn't running.

I had to remove the package and reinstall it to "fix" this issue.

**Comment by otoolep** [comment]
What version are you running?

**Comment by lburg** [comment]
I'm running version 0.9 RC16, installed using the package `influxdb_0.9.0-rc16_amd64.deb` (sorry I forgot such a basic info!)

**Comment by toddboom** [comment]
I just tested on master (pre-RC30) and this is no longer happening.
