### ISSUE TITLE
Raft unit test failure "not leader"

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#2205]
https://circleci.com/gh/influxdb/influxdb/1165

```
[raft] box436:8191 2015/04/09 02:59:59 changing term: 4 => 4
[raft] box436:8191 2015/04/09 02:59:59 log state change: leader => follower (term=4)
[raft] box436:8190 2015/04/09 02:59:59 send req vote(term=4, candidateID=1, lastLogIndex=22, lastLogTerm=1) (term=4, err=<nil>)
[raft] box436:8190 2015/04/09 02:59:59 send req vote(term=4, candidateID=1, lastLogIndex=22, lastLogTerm=1) (term=4, err=<nil>)
[raft] box436:8190 2015/04/09 02:59:59 log state change: candidate => leader (term=4)
[raft] box436:8191 2015/04/09 02:59:59 connect stream: not leader
panic: test timed out after 10m0s

goroutine 291542 [running]:
testing.func·008()
	/usr/local/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0xc02a70, 0x19bafe0, 0x18, 0x18, 0x1)
	/usr/local/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc2080360f0, 0x19c6600)
	/usr/local/go/src/testing/testing.go:485 +0xe1
main.main()
	github.com/influxdb/influxdb/cmd/influxd/_test/_testmain.go:100 +0x28d

goroutine 5 [syscall, 9 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x2d
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x43
```

**Comment by otoolep** [comment]
@benbjohnson

**Comment by otoolep** [comment]
No longer applicable in new design.
