### ISSUE TITLE
influxdb 0.9.0-rc19 panic

### ISSUE THREAD

**Issue by s7v7nislands** [influxdb/influxdb#2206]
brew install --devel influxdb

after some operation, then restart the server, it  panic. 
dig the code, seems the data node is 0. 

[messaging] 2015/04/08 17:57:22 connected to broker: http://bing-s-macbook-pro.local:8086/messaging/messages?index=8&streaming=true&topicID=0
panic: runtime error: integer divide by zero
[signal 0x8 code=0x7 addr=0xeeea1 pc=0xeeea1]

goroutine 11 [running]:
github.com/influxdb/influxdb.(*Server).applyCreateShardGroupIfNotExists(0xc2080f6000, 0xc20800b530, 0x0, 0x0)
	/private/tmp/influxdb20150408-26558-vjtpqp/influxdb-0.9.0-rc19/src/github.com/influxdb/influxdb/server.go:1032 +0x621
github.com/influxdb/influxdb.func·044()
	/private/tmp/influxdb20150408-26558-vjtpqp/influxdb-0.9.0-rc19/src/github.com/influxdb/influxdb/server.go:3224 +0x443
github.com/influxdb/influxdb.(*Server).processor(0xc2080f6000, 0xc15b70, 0xc2080d8f70, 0xc2080ee180)
	/private/tmp/influxdb20150408-26558-vjtpqp/influxdb-0.9.0-rc19/src/github.com/influxdb/influxdb/server.go:3250 +0x163
created by github.com/influxdb/influxdb.(*Server).Open
	/private/tmp/influxdb20150408-26558-vjtpqp/influxdb-0.9.0-rc19/src/github.com/influxdb/influxdb/server.go:213 +0x8fa

**Comment by toddboom** [comment]
@s7v7nislands can you give us any more detail on what data you sent to the server before this happened?

**Comment by JC-85** [comment]
Having the same issue on rc20. So far I have only sent the example data from the doc's. Going to do a clean install and see if I can recreate.

````
GET /query?q=CREATE%20DATABASE%20mydb HTTP/1.1
User-Agent: curl/7.38.0
Host: datalogger:8086
Accept: */*


HTTP/1.1 200 OK
Content-Type: application/json
Request-Id: 95b1d9c8-dea3-11e4-8002-000000000000
X-Influxdb-Version: 0.9.0-rc20
Date: Thu, 09 Apr 2015 10:31:30 GMT
Content-Length: 16

{"results":[{}]}
POST /write HTTP/1.1
User-Agent: curl/7.38.0
Host: datalogger:8086
Accept: */*
Content-Length: 369
Content-Type: application/x-www-form-urlencoded


{
    "database": "mydb",
    "retentionPolicy": "default",
    "points": [
        {
            "name": "cpu_load_short",
            "tags": {
                "host": "server01",
                "region": "us-west"
            },
            "timestamp": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.64
            }
        }
    ]
}
````

````

[srvr] 2015/04/09 12:43:20 GOMAXPROCS set to 8
[srvr] 2015/04/09 12:43:20 influxdb started, version 0.9.0-rc20, commit 475cdef884d7172def6d2a4198d105d562a8574e
[srvr] 2015/04/09 12:43:21 broker opened at /var/opt/influxdb/raft
[raft] entize1:8086 2015/04/09 12:43:21 log open: created at /var/opt/influxdb/raft/raft, with ID 1, term 1, last applied index of 887
[raft] entize1:8086 2015/04/09 12:43:21 log open: promoting to leader immediately
[raft] entize1:8086 2015/04/09 12:43:21 log state change: stopped => leader (term=1)
[srvr] 2015/04/09 12:43:21 TCP server listening on 0.0.0.0:8086
[srvr] 2015/04/09 12:43:21 Loading metadata index for mydb
[srvr] 2015/04/09 12:43:21 data server opened at /var/opt/influxdb/db
[srvr] 2015/04/09 12:43:21 broker enforcing retention policies with check interval of 10m0s
[srvr] 2015/04/09 12:43:21 shard group pre-create with check interval of 45m0s
[srvr] 2015/04/09 12:43:21 snapshot endpoint listening on 127.0.0.1:8087
[srvr] 2015/04/09 12:43:21 starting admin server on :8083
[srvr] 2015/04/09 12:43:21 Sending anonymous usage statistics to m.influxdb.com
[messaging] 2015/04/09 12:43:21 connected to broker: http://entize1:8086/messaging/messages?index=886&streaming=true&topicID=0
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x4ed6a1 pc=0x4ed6a1]

goroutine 14 [running]:
github.com/influxdb/influxdb.(*Server).applyCreateShardGroupIfNotExists(0xc20806a200, 0xc208136150, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:1039 +0x621
github.com/influxdb/influxdb.funcÂ·045()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:3247 +0x443
github.com/influxdb/influxdb.(*Server).processor(0xc20806a200, 0x7f06d1c2e9a8, 0xc2080fe000, 0xc20808c5a0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:3273 +0x163
created by github.com/influxdb/influxdb.(*Server).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:220 +0x8fa

goroutine 1 [chan receive (nil chan)]:
main.execRun(0xc20800a010, 0x4, 0x4)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:137 +0x6f7
main.main()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:77 +0x410

goroutine 5 [syscall]:
os/signal.loop()
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.initÂ·1
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
main.funcÂ·004()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:241 +0xed
created by main.startProfiling
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:244 +0x2dc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [select]:
github.com/influxdb/influxdb/raft.(*Log).applier(0xc20803a4e0, 0xc20808c060)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:1357 +0x2a8
created by github.com/influxdb/influxdb/raft.funcÂ·002
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:361 +0x786

goroutine 8 [select]:
github.com/influxdb/influxdb/raft.(*Log).leaderLoop(0xc20803a4e0, 0xc20808c060, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:1090 +0x634
github.com/influxdb/influxdb/raft.(*Log).stateLoop(0xc20803a4e0, 0xc20808c060, 0x3, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:834 +0x164
created by github.com/influxdb/influxdb/raft.(*Log).startStateLoop
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:792 +0x98

goroutine 18 [runnable]:
github.com/influxdb/influxdb/raft.funcÂ·001()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/clock.go:66 +0x33
created by github.com/influxdb/influxdb/raft.newClockChan
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/clock.go:66 +0xfb

goroutine 9 [runnable]:
github.com/influxdb/influxdb/raft.(*Log).heartbeater(0xc20803a4e0, 0x1, 0xc208010540, 0xc20801e680)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:1147 +0xe3c
created by github.com/influxdb/influxdb/raft.(*Log).leaderLoop
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:1087 +0x1e3

goroutine 10 [IO wait]:
net.(*pollDesc).Wait(0xc208010610, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010610, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080105b0, 0x0, 0x7f06d1c27c30, 0xc2081460a8)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208038048, 0xc208110de0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208038048, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc2080f4000, 0x7f06d1c2d720, 0xc208038048, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f06d1c2d720, 0xc208038048, 0x7f06d1c2e768, 0xc20801e6a0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
main.funcÂ·007()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:63 +0x80
created by main.Run
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:67 +0x857

goroutine 11 [select]:
github.com/influxdb/influxdb/messaging.(*Client).pinger(0xc2080d82c0, 0xc20808c300)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/client.go:364 +0x15e
created by github.com/influxdb/influxdb/messaging.(*Client).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/client.go:154 +0x1ec

goroutine 12 [chan receive]:
github.com/influxdb/influxdb/messaging.(*Conn).streamer(0xc2080fe000, 0xc20808c540)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/client.go:641 +0x1ec
created by github.com/influxdb/influxdb/messaging.(*Conn).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/client.go:510 +0x1ca

goroutine 13 [select]:
github.com/influxdb/influxdb/messaging.(*Conn).heartbeater(0xc2080fe000, 0xc20808c540)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/client.go:554 +0x15e
created by github.com/influxdb/influxdb/messaging.(*Conn).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/client.go:511 +0x1f0

goroutine 15 [select]:
github.com/influxdb/influxdb.funcÂ·012()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:420 +0x109
created by github.com/influxdb/influxdb.(*Server).StartRetentionPolicyEnforcement
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:427 +0x1dd

goroutine 16 [select]:
github.com/influxdb/influxdb.funcÂ·014()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:479 +0x116
created by github.com/influxdb/influxdb.(*Server).StartShardGroupsPreCreate
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:486 +0x1dd

goroutine 34 [IO wait]:
net.(*pollDesc).Wait(0xc208010ca0, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010ca0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010c40, 0x0, 0x7f06d1c27c30, 0xc20802bd18)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080380e0, 0x4a8e34, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc2080380e0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20808c780, 0x7f06d1c2ea28, 0xc2080380e0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20808c780, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc20802bd20, 0xe, 0x7f06d1c2e9d8, 0xc2080380d8, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1808 +0xba
main.funcÂ·008()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:108 +0x129
created by main.Run
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:109 +0x1017

goroutine 35 [IO wait]:
net.(*pollDesc).Wait(0xc20811c060, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20811c060, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20811c000, 0x0, 0x7f06d1c27c30, 0xc208146040)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208134000, 0xc208020380, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208134000, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc20813c060, 0x7f06d1c2d720, 0xc208134000, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f06d1c2d720, 0xc208134000, 0x7f06d1c2eb80, 0xc208146030, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/admin.(*Server).ListenAndServe(0xc2080e6120)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/admin/admin.go:43 +0x1d8
created by main.Run
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:120 +0x13f0

goroutine 36 [chan receive]:
github.com/influxdb/influxdb.(*Server).StartReportingLoop(0xc20806a200, 0x115208a7d53ae728, 0xc2080e3c18)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:3839 +0x83
created by main.Run
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:198 +0x23b8

goroutine 50 [IO wait]:
net.(*pollDesc).Wait(0xc20811a220, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20811a220, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20811a1c0, 0xc208152000, 0x1000, 0x1000, 0x0, 0x7f06d1c27c30, 0xc2080f0060)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080d0048, 0xc208152000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f06d1c2ec08, 0xc2080d0048, 0xc2080de268, 0xc208152000, 0x1000, 0x1000, 0x3e, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080f81c0, 0xc208152000, 0x1000, 0x1000, 0x49, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2080f4540)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2080f4540, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:295 +0x257
net/http/internal.readLine(0xc2080f4540, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/internal/chunked.go:110 +0x5a
net/http/internal.(*chunkedReader).beginChunk(0xc20810e0f0)
        /root/.gvm/gos/go1.4.2/src/net/http/internal/chunked.go:47 +0x46
net/http/internal.(*chunkedReader).Read(0xc20810e0f0, 0xc2080dc140, 0x16, 0x16, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/internal/chunked.go:77 +0xbb
net/http.(*body).readLocked(0xc2080360c0, 0xc2080dc140, 0x16, 0x16, 0xffffffff, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transfer.go:584 +0x7a
net/http.(*body).Read(0xc2080360c0, 0xc2080dc140, 0x16, 0x16, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transfer.go:579 +0x115
net/http.(*bodyEOFSignal).Read(0xc208036200, 0xc2080dc140, 0x16, 0x16, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:1193 +0x285
github.com/influxdb/influxdb/messaging.(*nopSeeker).Read(0xc2080d2040, 0xc2080dc140, 0x16, 0x16, 0xc2080dc140, 0x0, 0x0)
        <autogenerated>:26 +0x89
io.ReadAtLeast(0x7f06d1c2f1f8, 0xc2080d2040, 0xc2080dc140, 0x16, 0x16, 0x16, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/io/io.go:298 +0xf1
io.ReadFull(0x7f06d1c2f1f8, 0xc2080d2040, 0xc2080dc140, 0x16, 0x16, 0xc2080f24c0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/io/io.go:316 +0x6d
github.com/influxdb/influxdb/messaging.(*MessageDecoder).Decode(0xc2080d2050, 0xc20810e120, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/broker.go:1297 +0xe9
github.com/influxdb/influxdb/messaging.(*Conn).stream(0xc2080fe000, 0xc208128000, 0xc20808c540, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/client.go:671 +0x49a
github.com/influxdb/influxdb/messaging.funcÂ·014()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/client.go:633 +0x556
created by github.com/influxdb/influxdb/messaging.(*Conn).streamer
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/client.go:638 +0x1c4

goroutine 55 [select]:
github.com/influxdb/influxdb/messaging.funcÂ·016()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/handler.go:92 +0x134
created by github.com/influxdb/influxdb/messaging.(*Handler).getMessages
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/handler.go:98 +0x56c

goroutine 53 [select]:
net/http.(*persistConn).readLoop(0xc2080de210)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:660 +0xc9f

goroutine 20 [select]:
net/http.(*Transport).getConn(0xc208072090, 0xc20810c0d0, 0x0, 0x9ccad0, 0x4, 0x9ccad7, 0x13, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:525 +0x608
net/http.(*Transport).RoundTrip(0xc208072090, 0xc20810c0d0, 0xc208148000, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:228 +0x4d4
net/http.send(0xc20810c0d0, 0x7f06d1c27e00, 0xc208072090, 0x44, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc208136000, 0xc20810c0d0, 0x44, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc208136000, 0xc20810c0d0, 0xa06290, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/client.go:367 +0xb25
net/http.(*Client).Post(0xc208136000, 0x9ccad0, 0x44, 0x94f5b0, 0x10, 0x7f06d1c2ea60, 0xc208132000, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/client.go:441 +0x10d
created by github.com/influxdb/influxdb.(*Server).reportServer
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:3869 +0x6fe

goroutine 21 [select]:
net.lookupIPDeadline(0x9ccad7, 0xe, 0xeccb84ee7, 0x614916, 0xdf1520, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/lookup.go:82 +0x6cb
net.resolveInternetAddr(0x91a540, 0x3, 0x9ccad7, 0x13, 0xeccb84ee7, 0x614916, 0xdf1520, 0x0, 0x0, 0x0, ...)
        /root/.gvm/gos/go1.4.2/src/net/ipsock.go:285 +0x49b
net.resolveAddr(0x913880, 0x4, 0x91a540, 0x3, 0x9ccad7, 0x13, 0xeccb84ee7, 0x614916, 0xdf1520, 0x0, ...)
        /root/.gvm/gos/go1.4.2/src/net/dial.go:110 +0x378
net.(*Dialer).Dial(0xc208036180, 0x91a540, 0x3, 0x9ccad7, 0x13, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/dial.go:158 +0xf6
net.*Dialer.DialÂ·fm(0x91a540, 0x3, 0x9ccad7, 0x13, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:38 +0x79
net/http.(*Transport).dial(0xc208072090, 0x91a540, 0x3, 0x9ccad7, 0x13, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:479 +0x84
net/http.(*Transport).dialConn(0xc208072090, 0x0, 0x9ccad0, 0x4, 0x9ccad7, 0x13, 0xc208136000, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:564 +0x1678
net/http.funcÂ·019()
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:520 +0x42
created by net/http.(*Transport).getConn
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:522 +0x335

goroutine 22 [syscall, locked to thread]:
net._C2func_getaddrinfo(0x7f06c40008c0, 0x0, 0xc2080cb5c8, 0xc2080cb518, 0xc200000000, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/:26 +0x55
net.cgoLookupIPCNAME(0x9ccad7, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd52350f9088a900)
        /root/.gvm/gos/go1.4.2/src/net/cgo_unix.go:96 +0x1c5
net.cgoLookupIP(0x9ccad7, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc208142000)
        /root/.gvm/gos/go1.4.2/src/net/cgo_unix.go:148 +0x65
net.lookupIP(0x9ccad7, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/lookup_unix.go:64 +0x5f
net.funcÂ·026(0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/lookup.go:79 +0x55
net.(*singleflight).doCall(0xdf0af0, 0xc20800c660, 0x9ccad7, 0xe, 0xc2080d2110)
        /root/.gvm/gos/go1.4.2/src/net/singleflight.go:91 +0x2f
created by net.(*singleflight).DoChan
        /root/.gvm/gos/go1.4.2/src/net/singleflight.go:84 +0x42b

goroutine 54 [select]:
net/http.(*persistConn).writeLoop(0xc2080de210)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:661 +0xcbc

goroutine 66 [sleep]:
github.com/influxdb/influxdb/messaging.(*TopicReader).Read(0xc2080f2700, 0xc208162000, 0x8000, 0x8000, 0xc208160000, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/broker.go:1066 +0x46b
github.com/influxdb/influxdb/messaging.CopyFlush(0x7f06d1c2ef80, 0xc208160000, 0x7f06d1c2efa8, 0xc2080f2700, 0x10f, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/handler.go:226 +0xca
github.com/influxdb/influxdb/messaging.(*Handler).getMessages(0xc2080f8240, 0x7f06d1c2ee28, 0xc208160000, 0xc2081281a0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/handler.go:103 +0x605
github.com/influxdb/influxdb/messaging.(*Handler).ServeHTTP(0xc2080f8240, 0x7f06d1c2ee28, 0xc208160000, 0xc2081281a0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/handler.go:45 +0x30c
main.(*Handler).serveMessaging(0xc20801e6a0, 0x7f06d1c2ee28, 0xc208160000, 0xc2081281a0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:57 +0x2d3
main.(*Handler).ServeHTTP(0xc20801e6a0, 0x7f06d1c2ee28, 0xc208160000, 0xc2081281a0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:36 +0x1af
net/http.serverHandler.ServeHTTP(0xc2080f4000, 0x7f06d1c2ee28, 0xc208160000, 0xc2081281a0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208154000)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 37 [IO wait]:
net.(*pollDesc).Wait(0xc20811c0d0, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20811c0d0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20811c070, 0xc20817e000, 0x8000, 0x8000, 0x0, 0x7f06d1c27c30, 0xc2080d2000)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208134010, 0xc20817e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/net.go:121 +0xdc
io.Copy(0x7f06d1c2f028, 0xc208134030, 0x7f06d1c2ec08, 0xc208134010, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/io/io.go:362 +0x1f6
net/http.funcÂ·008()
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:171 +0x7d
created by net/http.(*conn).closeNotify
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:177 +0x2e2
````

**Comment by otoolep** [comment]
It looks like your node is not correctly configured, since it is not forming a cluster. How many nodes are you running? Are you using a config file?If so, please show us the file.

**Comment by s7v7nislands** [comment]
I just learn from doc, copy the command from doc. the 0.9 version of doc seems leak a lot of stuff. I can't find how to setup a cluster.

**Comment by beckettsean** [comment]
The 0.9.0 docs are not complete, and there is a large yellow warning banner
at the top of the page to that effect.

I would advise you to wait a few weeks until there is an official release
for 0.9.0, which will include improved documentation and support options,
as well as a fully tested brew installer.

On Thu, Apr 9, 2015 at 8:57 PM, s7v7nislands <notifications@github.com>
wrote:

> I just learn from doc, copy the command from doc. the 0.9 version of doc
> seems leak a lot of stuff. I can't find how to setup a cluster.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdb/influxdb/issues/2206#issuecomment-91420537>.
>



-- 
Sean Beckett
Director of Support and Professional Services
InfluxDB

**Comment by toddboom** [comment]
@s7v7nislands are you still seeing this with rc27?

**Comment by s7v7nislands** [comment]
no, but I think we should add check in code.

diff --git a/server.go b/server.go
index 0654468..1972f65 100644
--- a/server.go
+++ b/server.go
@@ -1149,6 +1149,10 @@ func (s *Server) applyCreateShardGroupIfNotExists(m *messaging.Message) error {
                return nil
        }

+       if len(s.dataNodes) == 0 {
+               return ErrDataNodeNotFound
+       }
+
        // Sort nodes so they're consistently assigned to the shards.
        nodes := make([]*DataNode, 0, len(s.dataNodes))
        for _, n := range s.dataNodes {

**Comment by jwilder** [comment]
Closing this since this was created using the old cluster code which has been replaced.
