### ISSUE TITLE
Crash in ALTER RETENTION POLICY

### ISSUE THREAD

**Issue by jcsp** [influxdb/influxdb#2251]
Version 0.9.0_rc23

I have no idea if my syntax for setting a policy to be default was actually correct, but it produced a crash:

```
[http] 2015/04/12 10:42:15 127.0.0.1 - - [12/Apr/2015:10:42:15 +0000] GET /query?db=ceph&q=alter+retention+policy+threeway+on+ceph+default+true HTTP/1.1 400 143 - InfluxDBShell/0.9.0-rc23 958ae875-e100-11e4-80ef-000000000000 1.010913ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4f7bbe]

goroutine 115278 [running]:
github.com/influxdb/influxdb.(*Server).UpdateRetentionPolicy(0xc20806c200, 0xc20902d5e4, 0x4, 0xc20902d5d0, 0x8, 0xc2082bd5a0, 0x0, 0x0)
	/home/philip/build/src/github.com/influxdb/influxdb/server.go:1566 +0x3e
github.com/influxdb/influxdb.(*Server).executeAlterRetentionPolicyStatement(0xc20806c200, 0xc2081dab80, 0x0, 0xc2081dab80)
	/home/philip/build/src/github.com/influxdb/influxdb/server.go:2997 +0x139
github.com/influxdb/influxdb.func·039()
	/home/philip/build/src/github.com/influxdb/influxdb/server.go:2197 +0xe0b
created by github.com/influxdb/influxdb.(*Server).ExecuteQuery
	/home/philip/build/src/github.com/influxdb/influxdb/server.go:2231 +0x314
```

```
> show retention policies ceph
name		duration	replicaN	default
default		0		1		true
threeway	720h0m0s	3		false
```

**Comment by otoolep** [comment]
@dgnorton

**Comment by dgnorton** [comment]
`ALTER RETENTION POLICY ... DEFAULT true` should have returned a "bad request" response...
