### ISSUE TITLE
Influxdb Monitoring crashes the server

### ISSUE THREAD

**Issue by NikolaBorisov** [influxdb/influxdb#2260]
I saw this new option in the config about monitoring. I decided to give it a try but it caused influxdb to panic. Basically I enabled this in the config:
```
[monitoring]
enabled = false
write-interval = "1m"          # Period between writing the data.
```

and go this stacktrace

```
panic: unsupported value type during encode fields: int64

goroutine 29 [running]:
github.com/influxdb/influxdb.(*FieldCodec).EncodeFields(0xc2081020b0, 0xc20820ca20, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/philip/build/src/github.com/influxdb/influxdb/database.go:816 +0xae4
github.com/influxdb/influxdb.func·035(0x0, 0x0)
        /home/philip/build/src/github.com/influxdb/influxdb/server.go:1816 +0x75d
github.com/influxdb/influxdb.(*Server).WriteSeries(0xc208138000, 0x9becd0, 0x9, 0x99bed0, 0x7, 0xc208268000, 0x7, 0x8, 0x0, 0x0, ...)
        /home/philip/build/src/github.com/influxdb/influxdb/server.go:1834 +0xa80
github.com/influxdb/influxdb.func·011()
        /home/philip/build/src/github.com/influxdb/influxdb/server.go:410 +0x7fe
created by github.com/influxdb/influxdb.(*Server).StartSelfMonitoring
        /home/philip/build/src/github.com/influxdb/influxdb/server.go:412 +0x241

```

**Comment by otoolep** [comment]
Thanks for the report.

https://github.com/influxdb/influxdb/pull/2261 should fix this.

**Comment by otoolep** [comment]
Should be fixed now.
