### ISSUE TITLE
interface conversion panic when selecting mean or stddev from "server_memory" self-diagnostics measurement

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdb/influxdb#2422]
Built from source from commit 615aabf2fc5df52dc2d011972b53046d240cd10c.

There might be an easier way to reproduce this, but the easiest way I've found is to turn on self-monitoring, wait for at least one self-monitoring write, and then run this curl command:

```
curl -G http://localhost:8086/query --data-urlencode "db=_influxdb" --data-urlencode "q=SELECT alloc FROM server_memory"; # just to see the underlying data before the failure \
echo; # make this output a little easier to follow \
curl -G http://localhost:8086/query --data-urlencode "db=_influxdb" --data-urlencode "q=SELECT mean(alloc) FROM server_memory"
```

which causes this panic:

```
srvr] 2015/04/24 15:16:34 started self-monitoring at interval of 10s
[srvr] 2015/04/24 15:16:34 API server listening on :8086
[srvr] 2015/04/24 15:16:34 broker cq: no data nodes currently available.
[srvr] 2015/04/24 15:16:34 Sending anonymous usage statistics to m.influxdb.com
[messaging] 2015/04/24 15:16:44 connected to broker: http://:8086/messaging/messages?index=0&streaming=true&topicID=1
[http] 2015/04/24 15:16:46 ::1 - - [24/Apr/2015:15:16:46 -0700] GET /query?db=_influxdb&q=SELECT%20alloc%20FROM%20server_memory HTTP/1.1 200 131 - curl/7.37.1 988e1f75-eacf-11e4-800d-000000000000 407.44µs
panic: interface conversion: interface is int64, not float64

goroutine 2425 [running]:
github.com/influxdb/influxdb/influxql.MapMean(0xd1e1d0, 0xc208134b00, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdb/influxdb/influxql/functions.go:218 +0xbf
github.com/influxdb/influxdb.(*LocalMapper).NextInterval(0xc208134b00, 0x0, 0x0, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdb/influxdb/tx.go:401 +0xd3
github.com/influxdb/influxdb/influxql.(*MapReduceJob).processAggregate(0xc208181110, 0xc208179350, 0x6ce368, 0xc20814cb40, 0x1, 0x1, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:626 +0x264
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc208181110, 0xc20806df20, 0xc20810d700)
	/Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:167 +0x8bf
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc208147a40, 0xc20806df20)
	/Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:774 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
	/Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:753 +0x5a
```

**Comment by mark-rushakoff** [comment]
Saw the same error with a different stack trace when querying stddev instead of mean:

```
[srvr] 2015/04/24 15:37:44 started self-monitoring at interval of 10s
[srvr] 2015/04/24 15:37:44 API server listening on :8086
[srvr] 2015/04/24 15:37:44 broker cq: no data nodes currently available.
[srvr] 2015/04/24 15:37:44 Sending anonymous usage statistics to m.influxdb.com
[messaging] 2015/04/24 15:37:55 connected to broker: http://:8086/messaging/messages?index=0&streaming=true&topicID=1
[http] 2015/04/24 15:38:01 ::1 - - [24/Apr/2015:15:38:01 -0700] GET /query?db=_influxdb&q=SELECT%20alloc%20FROM%20server_memory HTTP/1.1 200 131 - curl/7.37.1 906a1a98-ead2-11e4-8011-000000000000 374.846µs
panic: interface conversion: interface is int64, not float64

goroutine 3177 [running]:
github.com/influxdb/influxdb/influxql.MapStddev(0xd1d300, 0xc208236b00, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdb/influxdb/influxql/functions.go:395 +0xac
github.com/influxdb/influxdb.(*LocalMapper).NextInterval(0xc208236b00, 0x0, 0x0, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdb/influxdb/tx.go:401 +0xd3
github.com/influxdb/influxdb/influxql.(*MapReduceJob).processAggregate(0xc208234b60, 0xc2080ea5d0, 0x6ce380, 0xc208124fa0, 0x1, 0x1, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:626 +0x264
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc208234b60, 0xc20818b440, 0xc20810c700)
	/Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:167 +0x8bf
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc2081f2d40, 0xc20818b440)
	/Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:774 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
	/Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:753 +0x5a
```

**Comment by marcosnils** [comment]
@mark-rushakoff I can't even get to the point where self-monitoring writes the point. In my case Influx panics when the first self-monitoring interval runs....

I'm running commit 6f326bcd9a898d1f4d16240301b342c9df8aa120 which is the latest by the time of this comment

**Comment by otoolep** [comment]
@marcosnils -- there are no known issues like you describe. Can you please open a ticket, with explicit details on how to reproduce the issue?

**Comment by otoolep** [comment]
@mark-rushakoff -- this is a known issue. Aggregates only work on float data right now, which monitoring data is not.

**Comment by marcosnils** [comment]
@otoolep debugging the code I've realized it had something to do with the /data/shards diagnostics. I've deleted my data dir and restarted my instance and problem is gone now. 

I could however print the line line when it was failing, the diagnostic `convertRowToPoints` function tried to parse this and it was panicking due to index out or range.

```
[2015-04-25 00:45:43.653425515 +0000 UTC 300 1 0] map[id:1 dataNodes:2 index:3 path:31]
```

**Comment by otoolep** [comment]
There was a recent fix to the monitoring data, and its format would changed in the datastore. This may explain what you saw.

**Comment by dahankzter** [comment]
I get this on a derivative(field_key) query

**Comment by otoolep** [comment]
Server diagnostics are being completely re-implemented for the new design.
