### ISSUE TITLE
Query for exact timestamp causes panic

### ISSUE THREAD

**Issue by tdalzell** [influxdb/influxdb#2487]
This query works:
`SELECT count(msgCount) FROM outbounddata WHERE providerId='1' AND time > now() - 15m`

This query causes panic: ( time = vs time > )
`SELECT count(msgCount) FROM outbounddata WHERE providerId='1' AND time = now() - 15m`

```
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x6c318d pc=0x6c318d]

goroutine 5120 [running]:
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc20bea8310, 0xc20be318c0, 0xc209290700)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:138 +0x68d
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc20be79440, 0xc20be318c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:774 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:753 +0x5a
```

Schema:
```
{
    "database": "streamDB",
    "retentionPolicy": "default",
    "points": [
        {
            "name": "outbounddata",
            "tags": {
                "providerId": "1",
                "customerId": "xyz"
               
            },
            "fields": {
                "stream":"stream1",
                           "subscription":"sdfsd1",
                           "msgCount": 1
            }
        }
    ]
}
```

**Comment by tdalzell** [comment]
After digging around some more it looks like this may be related to #2002
