### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Crazee** [influxdb/influxdb#2660]
I've been running 0.8.6 for a while and it started not processing most continuous query series.  Disk space has also grown so I don't think it's dropping old shards either.
Now the log file complains about panics, which can't be good:
```
+---------------------------------------------+
|  _____        __ _            _____  ____   |
| |_   _|      / _| |          |  __ \|  _ \  |
|   | |  _ __ | |_| |_   ___  _| |  | | |_) | |
|   | | | '_ \|  _| | | | \ \/ / |  | |  _ <  |
|  _| |_| | | | | | | |_| |>  <| |__| | |_) | |
| |_____|_| |_|_| |_|\__,_/_/\_\_____/|____/  |
+---------------------------------------------+

panic: runtime error: index out of range

goroutine 28 [running]:
runtime.panic(0xc1db60, 0x14b0bdc)
	/root/.gvm/gos/go1.3.1/src/pkg/runtime/panic.c:279 +0xf5
github.com/influxdb/influxdb/_vendor/raft.(*Log).commitInfo(0xc2080cb260, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/log.go:300 +0x33a
github.com/influxdb/influxdb/_vendor/raft.(*server).TakeSnapshot(0xc208003b00, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/_vendor/raft/server.go:1192 +0x2aa
github.com/influxdb/influxdb/coordinator.(*RaftServer).ForceLogCompaction(0xc20804e370, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:335 +0xbf
github.com/influxdb/influxdb/coordinator.(*RaftServer).CompactLog(0xc20804e370)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:362 +0x31f
created by github.com/influxdb/influxdb/coordinator.(*RaftServer).startRaft
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:406 +0x512

goroutine 16 [IO wait]:
net.runtime_pollWait(0x7fdc6100c3b0, 0x72, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208218ae0, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208218ae0, 0x0, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc208218a80, 0xdbd5f8, 0x0, 0x7fdc610092b8, 0xb)
	/root/.gvm/gos/go1.3.1/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc2081a6530, 0x8, 0x0, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc2081a6530, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/net/tcpsock_posix.go:244 +0x4b
net/http.(*Server).Serve(0xc208004060, 0x7fdc6100b568, 0xc2081a6530, 0x0, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/net/http/server.go:1698 +0x91
github.com/influxdb/influxdb/api/http.(*HttpServer).serveListener(0xc20804e6e0, 0x7fdc6100b568, 0xc2081a6530, 0xc20803a0e0)
	/root/gocodez/src/github.com/influxdb/influxdb/api/http/api.go:202 +0xb9
github.com/influxdb/influxdb/api/http.(*HttpServer).Serve(0xc20804e6e0, 0x7fdc6100b568, 0xc2081a6530)
	/root/gocodez/src/github.com/influxdb/influxdb/api/http/api.go:172 +0xcbd
github.com/influxdb/influxdb/api/http.(*HttpServer).ListenAndServe(0xc20804e6e0)
	/root/gocodez/src/github.com/influxdb/influxdb/api/http/api.go:91 +0x1a4
github.com/influxdb/influxdb/server.(*Server).ListenAndServe(0xc208010120, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/server/server.go:217 +0xa7b
main.start(0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/daemon/influxd.go:202 +0x101f
main.main()
	/root/gocodez/src/github.com/influxdb/influxdb/daemon/influxd.go:73 +0x1e

goroutine 19 [finalizer wait, 1440 minutes]:
runtime.park(0x4fcc40, 0x14c8890, 0x14b2e89)
	/root/.gvm/gos/go1.3.1/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x14c8890, 0x14b2e89)
	/root/.gvm/gos/go1.3.1/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/root/.gvm/gos/go1.3.1/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/root/.gvm/gos/go1.3.1/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 852 minutes]:
os/signal.loop()
	/root/.gvm/gos/go1.3.1/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/root/.gvm/gos/go1.3.1/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [chan receive, 1440 minutes]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc208070000, 0x7fdc61009418, 0xc20803a008)
	/root/gocodez/src/code.google.com/p/log4go/termlog.go:27 +0x79
created by code.google.com/p/log4go.NewConsoleLogWriter
	/root/gocodez/src/code.google.com/p/log4go/termlog.go:19 +0x68

goroutine 17 [syscall, 1440 minutes]:
runtime.goexit()
	/root/.gvm/gos/go1.3.1/src/pkg/runtime/proc.c:1445

goroutine 22 [select, 23 minutes]:
code.google.com/p/log4go.func·002()
	/root/gocodez/src/code.google.com/p/log4go/filelog.go:84 +0x8ac
created by code.google.com/p/log4go.NewFileLogWriter
	/root/gocodez/src/code.google.com/p/log4go/filelog.go:116 +0x2c4

goroutine 23 [chan receive]:
github.com/influxdb/influxdb/wal.(*WAL).processEntries(0xc2080ca070)
	/root/gocodez/src/github.com/influxdb/influxdb/wal/wal.go:252 +0x64
created by github.com/influxdb/influxdb/wal.NewWAL
	/root/gocodez/src/github.com/influxdb/influxdb/wal/wal.go:103 +0xa53

goroutine 24 [chan send, 852 minutes]:
github.com/influxdb/influxdb/coordinator.(*RaftServer).Close(0xc20804e370)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:598 +0xb8
github.com/influxdb/influxdb/server.(*Server).Stop(0xc208010120)
	/root/gocodez/src/github.com/influxdb/influxdb/server/server.go:277 +0x282
main.waitForSignals(0x7fdc6100b4e8, 0xc208010120)
	/root/gocodez/src/github.com/influxdb/influxdb/daemon/null_profiler.go:27 +0x2f8
created by main.startProfiler
	/root/gocodez/src/github.com/influxdb/influxdb/daemon/null_profiler.go:15 +0x4b

goroutine 30 [chan receive, 23 minutes]:
github.com/influxdb/influxdb/coordinator.(*Coordinator).queryShards(0xc2080b8820, 0xc2080be5a0, 0xc20bfb1f58, 0x5, 0x5, 0xc208773c20, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/coordinator.go:267 +0x15f
github.com/influxdb/influxdb/coordinator.(*Coordinator).runQuerySpec(0xc2080b8820, 0xc2080be5a0, 0x7fdc61012160, 0xc20bfb1b30, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/coordinator.go:315 +0x353
github.com/influxdb/influxdb/coordinator.(*Coordinator).runSingleQuery(0xc2080b8820, 0x7fdc610120f8, 0xc2080b4a40, 0xc2080b0c20, 0x7, 0xc20bfb1e00, 0x7fdc61012160, 0xc20bfb1b30, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/coordinator.go:85 +0x230
github.com/influxdb/influxdb/coordinator.(*Coordinator).RunQuery(0xc2080b8820, 0x7fdc610120f8, 0xc2080b4a40, 0xc2080b0c20, 0x7, 0xc2080540e0, 0xdb, 0x7fdc61012160, 0xc20bfb1b30, 0x0, ...)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/coordinator.go:54 +0x436
github.com/influxdb/influxdb/coordinator.(*RaftServer).runContinuousQuery(0xc20804e370, 0xc2080b0c20, 0x7, 0xc208044180, 0x0, 0x0, 0x0, 0xeccf1a290, 0x0, 0x14caa40)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:552 +0x2bd
github.com/influxdb/influxdb/coordinator.(*RaftServer).checkContinuousQueries(0xc20804e370)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:524 +0x5e1
github.com/influxdb/influxdb/coordinator.(*RaftServer).raftLeaderLoop(0xc20804e370, 0xc208025b40, 0xc208025b00)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:468 +0x18a
created by github.com/influxdb/influxdb/coordinator.(*RaftServer).raftEventHandler
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/raft_server.go:453 +0x268

goroutine 33 [IO wait, 1439 minutes]:
net.runtime_pollWait(0x7fdc6100c460, 0x72, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208218680, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208218680, 0x0, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc208218620, 0xdbd5f8, 0x0, 0x7fdc610092b8, 0xb)
	/root/.gvm/gos/go1.3.1/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc2081a6520, 0xc2082426c0, 0x0, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc2081a6520, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.3.1/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/influxdb/influxdb/coordinator.(*ProtobufServer).ListenAndServe(0xc208025a40)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/protobuf_server.go:68 +0x1c7
created by github.com/influxdb/influxdb/server.(*Server).ListenAndServe
	/root/gocodez/src/github.com/influxdb/influxdb/server/server.go:126 +0x2a2

goroutine 34 [select, 1439 minutes]:
github.com/influxdb/influxdb/cluster.(*WriteBuffer).handleWrites(0xc2082185b0)
	/root/gocodez/src/github.com/influxdb/influxdb/cluster/write_buffer.go:75 +0xd3
created by github.com/influxdb/influxdb/cluster.NewWriteBuffer
	/root/gocodez/src/github.com/influxdb/influxdb/cluster/write_buffer.go:43 +0x286

goroutine 37 [chan receive, 1439 minutes]:
github.com/influxdb/influxdb/server.(*Server).startReportingLoop(0xc208010120, 0xc208242910)
	/root/gocodez/src/github.com/influxdb/influxdb/server/server.go:229 +0xc9
created by github.com/influxdb/influxdb/server.(*Server).ListenAndServe
	/root/gocodez/src/github.com/influxdb/influxdb/server/server.go:210 +0x962

goroutine 408181 [runnable]:
github.com/influxdb/influxdb/engine.(*CumulativeArithmeticAggregator).GetValues(0xc20849be00, 0xaf97c0, 0x4043800000000000, 0xc209d40960, 0x1, 0xc209298e00)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/aggregator_operators.go:125
github.com/influxdb/influxdb/engine.(*AggregatorEngine).getValuesForGroup(0xc208011200, 0xc2091e8820, 0x6, 0xc20a516c80, 0x5, 0x8, 0xc20892a000, 0x0, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/aggregator_engine.go:293 +0x20d
github.com/influxdb/influxdb/engine.func·002(0xc20a516c80, 0x5, 0x8, 0xc20892a000, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/aggregator_engine.go:242 +0x93
github.com/influxdb/influxdb/engine.(*Node).traverse(0xc2088b7ec0, 0x7ffffffffffffffb, 0xc209b15ba0, 0x4, 0x4, 0xc209cd9488, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/trie.go:111 +0x1f7
github.com/influxdb/influxdb/engine.(*Node).traverse(0xc2088b7e00, 0x7ffffffffffffffc, 0xc209b15ba0, 0x3, 0x4, 0xc209cd9488, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/trie.go:117 +0x362
github.com/influxdb/influxdb/engine.(*Node).traverse(0xc2088b7dc0, 0x7ffffffffffffffd, 0xc20972c270, 0x2, 0x2, 0xc209cd9488, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/trie.go:117 +0x362
github.com/influxdb/influxdb/engine.(*Node).traverse(0xc209234c00, 0x7ffffffffffffffe, 0xc209298bc0, 0x1, 0x1, 0xc209cd9488, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/trie.go:117 +0x362
github.com/influxdb/influxdb/engine.(*Node).traverse(0xc208cd5c40, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc209cd9488, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/trie.go:117 +0x362
github.com/influxdb/influxdb/engine.(*Trie).TraverseLevel(0xc209d40940, 0x7fffffffffffffff, 0xc209cd9488, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/trie.go:61 +0xaf
github.com/influxdb/influxdb/engine.(*Trie).Traverse(0xc209d40940, 0xc209cd9488, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/trie.go:49 +0x4c
github.com/influxdb/influxdb/engine.(*AggregatorEngine).runAggregatesForTable(0xc208011200, 0xc2091e8820, 0x6, 0xc2091136c0, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/aggregator_engine.go:262 +0x4f0
github.com/influxdb/influxdb/engine.(*AggregatorEngine).aggregateValuesForSeries(0xc208011200, 0xc20ac5c310, 0xc687c0, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/aggregator_engine.go:178 +0x3b7
github.com/influxdb/influxdb/engine.(*AggregatorEngine).Yield(0xc208011200, 0xc20ac5c310, 0x2, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/aggregator_engine.go:96 +0x167
github.com/influxdb/influxdb/engine.(*FilteringEngine).Yield(0xc20ac264a0, 0xc20ac5c310, 0xc20895f918, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/engine/filtering_engine.go:23 +0x74
github.com/influxdb/influxdb/datastore.yieldToProcessor(0xc20b6bd7a0, 0x7fdc61012408, 0xc20ac264a0, 0xc208dcaf80, 0x1, 0x1, 0x1, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/datastore/utils.go:19 +0x2cd
github.com/influxdb/influxdb/datastore.(*Shard).executeQueryForSeries(0xc2081f4280, 0xc2080be5a0, 0xc2091e8820, 0x6, 0xc208ae41c0, 0x7, 0x7, 0x7fdc61012408, 0xc20ac264a0, 0x0, ...)
	/root/gocodez/src/github.com/influxdb/influxdb/datastore/shard.go:205 +0x5be
github.com/influxdb/influxdb/datastore.(*Shard).executeArrayQuery(0xc2081f4280, 0xc2080be5a0, 0x7fdc61012408, 0xc20ac264a0, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/datastore/shard.go:174 +0x398
github.com/influxdb/influxdb/datastore.(*Shard).Query(0xc2081f4280, 0xc2080be5a0, 0x7fdc61012408, 0xc20ac264a0, 0x0, 0x0)
	/root/gocodez/src/github.com/influxdb/influxdb/datastore/shard.go:112 +0x479
github.com/influxdb/influxdb/cluster.(*ShardData).Query(0xc2080baff0, 0xc2080be5a0, 0xc209a62000)
	/root/gocodez/src/github.com/influxdb/influxdb/cluster/shard.go:327 +0xb0f
created by github.com/influxdb/influxdb/coordinator.(*Coordinator).queryShards
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/coordinator.go:273 +0x340

goroutine 402881 [chan receive]:
github.com/influxdb/influxdb/coordinator.(*MergeChannelProcessor).processChannel(0xc208773c20, 0xc209a62000, 0x7fdc5c84cf88)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/merge_channel_processor.go:127 +0x67
github.com/influxdb/influxdb/coordinator.(*MergeChannelProcessor).ProcessChannels(0xc208773c20)
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/merge_channel_processor.go:118 +0x98
created by github.com/influxdb/influxdb/coordinator.(*Coordinator).runQuerySpec
	/root/gocodez/src/github.com/influxdb/influxdb/coordinator/coordinator.go:313 +0x302
```

**Comment by beckettsean** [comment]
Upgrading to version 0.8.8 may clear the issue. We are unaware of any configuration issues that can lead to this so there aren't too many other things to try.
