### ISSUE TITLE
Aggregate query over tag does not return parse error

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2704]
The query is very simple, just taking the MIN or MAX of a tag rather than a field. That aggregation should not be allowed, since tag values are always strings, but instead of a parser error I get a panic.

```
> select min("tagnum") from tagfield 
ERR: Get http://localhost:8086/query?db=mydb&q=select+min%28%22tagnum%22%29+from+tagfield+: EOF
```
Relevant log lines and stack trace
```
[srvr] 2015/05/29 16:52:27 API server listening on 0.0.0.0:8086
[srvr] 2015/05/29 16:52:27 broker cq: no data nodes currently available.
[srvr] 2015/05/29 16:52:27 Sending anonymous usage statistics to m.influxdb.com
[http] 2015/05/29 16:52:27 127.0.0.1 - - [29/May/2015:16:52:27 -0700] POST /write HTTP/1.1 204 0 - telegraf c2f7f375-065d-11e5-8001-000000000000 4.424829ms
[http] 2015/05/29 16:52:41 127.0.0.1 - - [29/May/2015:16:52:41 -0700] POST /write HTTP/1.1 204 0 - telegraf cb4fa5db-065d-11e5-8010-000000000000 10.495991ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x11dfe1]

goroutine 12563 [running]:
github.com/influxdb/influxdb.(*tx).CreateMapReduceJobs(0xc2122fe5c0, 0xc20d530f00, 0xc20b0ba150, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/influxdb20150528-82093-7zu91/influxdb-0.9.0-rc31/src/github.com/influxdb/influxdb/tx.go:132 +0x3161
github.com/influxdb/influxdb/influxql.(*Planner).Plan(0xc20c8e8940, 0xc20d530f00, 0x2710, 0x93d26e98, 0x0, 0x0)
        /private/tmp/influxdb20150528-82093-7zu91/influxdb-0.9.0-rc31/src/github.com/influxdb/influxdb/influxql/engine.go:865 +0x319
github.com/influxdb/influxdb.(*Server).planSelectStatement(0xc208068000, 0xc20d530f00, 0x2710, 0x0, 0x0, 0x0)
        /private/tmp/influxdb20150528-82093-7zu91/influxdb-0.9.0-rc31/src/github.com/influxdb/influxdb/server.go:2496 +0x14a
github.com/influxdb/influxdb.(*Server).executeSelectStatement(0xc208068000, 0x0, 0xc20d530f00, 0xc2128990ee, 0x4, 0x0, 0xc2128b9620, 0x2710, 0x0, 0x0)
        /private/tmp/influxdb20150528-82093-7zu91/influxdb-0.9.0-rc31/src/github.com/influxdb/influxdb/server.go:2321 +0xba
github.com/influxdb/influxdb.func·040()
        /private/tmp/influxdb20150528-82093-7zu91/influxdb-0.9.0-rc31/src/github.com/influxdb/influxdb/server.go:2225 +0xae3
created by github.com/influxdb/influxdb.(*Server).ExecuteQuery
        /private/tmp/influxdb20150528-82093-7zu91/influxdb-0.9.0-rc31/src/github.com/influxdb/influxdb/server.go:2307 +0x314
```

**Comment by jwilder** [comment]
This no longer panics.  It just returns empty results now.

**Comment by jwilder** [comment]
This still needs to return a 400 error because it is an invalid query.

**Comment by beckettsean** [comment]
query requires at least one field in the SELECT clause, so returning nothing for invalid functions seems okay:

```
> insert errors,tagk=foo fieldk=42
> insert errors,tagk=foo fieldk=43
> insert errors,tagk=foo fieldk=44
> select mean(fieldk) from errors
name: errors
------------
time			mean
1970-01-01T00:00:00Z	43

> select mean(fieldk), max(tagk) from errors
name: errors
------------
time			mean	max
1970-01-01T00:00:00Z	43	

> select mean(fieldk), mean(tagk) from errors
name: errors
------------
time			mean	mean
1970-01-01T00:00:00Z	43	

> select mean(tagk) from errors
ERR: statement must have at least one field in select clause
> 
```
