### ISSUE TITLE
[0.9-rc31] CONTINUOUS QUERIES  panic: runtime error: index out of range 

### ISSUE THREAD

**Issue by Jean-Emile** [influxdb/influxdb#2726]
Hi,

I have a crash report indicating me a  "panic: runtime error: index out of range" 
The crash happened during the creation of the  continuous query below :
```
CREATE CONTINUOUS QUERY compute_node_cpu_user_percent_mean ON indeed BEGIN 
  SELECT mean(usage),host INTO "compute_node_cpu_user_percent_mean_1h" FROM compute_node_cpu_user_percent GROUP BY time(1h) 
END
```
The code used for putting the data into influxdb:
```
 client = InfluxDBClient('localhost', 8086, 'root', 'root', 'db')
    client.drop_database('db')
    client.create_database('db')

    for server_id in range(0, 2):
        cpu_metric = [
            {
                "name": "compute_node_cpu_user_percent",
                "tags": {
                    "datacenter": 'Meneac',
                    "availabilityZone": "Zone1",
                    "host": "server" + str(server_id)
                },
                "fields": {
                    "usage": randint(0, 100)
                }
            }
        ]

        # semaine === 10 080 minutes
        for i in range(0, 10080):
           if client.write_points(cpu_metric) is not True:
```

The log : 
```
panic: runtime error: index out of range

goroutine 9877 [running]:
github.com/influxdb/influxdb.(*Server).convertRowToPoints(0xc20805e200, 0xc20834e9f0, 0x25, 0xc2081a8480, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:4097 +0x7b7
github.com/influxdb/influxdb.(*Server).runContinuousQueryAndWriteResult(0xc20805e200, 0xc2086f05c0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:4049 +0x158
github.com/influxdb/influxdb.(*Server).runContinuousQuery(0xc20805e200, 0xc2086f05c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:4013 +0x486
github.com/influxdb/influxdb.func·050(0xc2086f05c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:3977 +0x34
created by github.com/influxdb/influxdb.(*Server).RunContinuousQueries
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:3978 +0x269
```

**Comment by beckettsean** [comment]
The points may not be actually writing. You've got `name` in your JSON but in RC31 the proper syntax is `measurement`: https://github.com/influxdb/influxdb/issues/2564

It's still not good that the db panics, but can you try again on RC32+?

**Comment by Jean-Emile** [comment]
fixed in RC33 thanks

**Comment by beckettsean** [comment]
Thanks for the update, @Jean-Emile
