### ISSUE TITLE
OpenTSDB listener crashes

### ISSUE THREAD

**Issue by dkulinski-edm** [influxdb/influxdb#2799]
I'm running the latest version of influxdb ```[srvr] 2015/06/06 00:27:18 influxdb started, version 0.9.0-rc31, commit 8ade485b5865e642b128a7cc6eb20c9da73d1b48``` and the opentsdb listener is crashing when uploading data to it:
```
[srvr] 2015/06/06 00:27:30 TSDB listener accept  {0xc2081a07a0 <nil>}
[srvr] 2015/06/06 00:27:30 http: panic serving 10.32.225.226:62098: sync: negative WaitGroup counter
goroutine 2312 [running]:
net/http.func·011()
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1130 +0xbb
sync.(*WaitGroup).Add(0xc2080d4820, 0xffffffffffffffff)
        /root/.gvm/gos/go1.4.2/src/sync/waitgroup.go:67 +0x96
sync.(*WaitGroup).Done(0xc2080d4820)
        /root/.gvm/gos/go1.4.2/src/sync/waitgroup.go:85 +0x31
github.com/influxdb/influxdb/opentsdb.(*Server).ServeHTTP(0xc2080d47e0, 0x7f721504fcb0, 0xc208058280, 0xc208220000)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/opentsdb/opentsdb.go:349 +0x955
net/http.(*ServeMux).ServeHTTP(0xc208102ea0, 0x7f721504fcb0, 0xc208058280, 0xc208220000)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20819aa80, 0x7f721504fcb0, 0xc208058280, 0xc208220000)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208116780)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e
```

The same request seems to work fine with OpenTSDB. I'm using https://github.com/sps/metrics-opentsdbto write data if that helps.

**Comment by tcolgate** [comment]
Unlimelytobe able to look into this, but I reckon its multiple requests on
one connection. Probably leaving/entering the wait group in the wrong place

**Comment by otoolep** [comment]
The openTSDB input has been refactored here: https://github.com/influxdb/influxdb/pull/2823 and I expect the WaitGroup bug will have been addressed.

Closing as fixed in RC33.
