### ISSUE TITLE
0.9rc31: restore backup crash the daemon

### ISSUE THREAD

**Issue by dtouzeau** [influxdb/influxdb#2801]
Hi i have backuped the influx database using influxdb backup command from server 1
i want to restore it to server 2 using the restore command.

Restore seems do the job....
```
2015/06/06 18:00:28 influxdb restore, version 0.9.0-rc31, commit 8ade485b5865e642b128a7cc6eb20c9da73d1b48
2015/06/06 18:00:28 unpacking: meta / idx=474980262 (274432 bytes)
2015/06/06 18:00:28 unpacking: shards/1 / idx=784586 (45993984 bytes)
2015/06/06 18:00:28 unpacking: shards/10 / idx=0 (24576 bytes)
2015/06/06 18:00:28 unpacking: shards/100 / idx=0 (24576 bytes)
2015/06/06 18:00:28 unpacking: shards/101 / idx=0 (24576 bytes)
2015/06/06 18:00:28 unpacking: shards/102 / idx=0 (24576 bytes)
2015/06/06 18:00:28 unpacking: shards/103 / idx=0 (24576 bytes)
2015/06/06 18:00:28 unpacking: shards/104 / idx=0 (24576 bytes)
2015/06/06 18:00:28 unpacking: shards/105 / idx=0 (24576 bytes)
2015/06/06 18:00:28 unpacking: shards/106 / idx=0 (24576 bytes)
...
:01:14 unpacking: shards/93 / idx=0 (24576 bytes)
2015/06/06 18:01:14 unpacking: shards/94 / idx=0 (24576 bytes)
2015/06/06 18:01:14 unpacking: shards/95 / idx=0 (24576 bytes)
2015/06/06 18:01:14 unpacking: shards/96 / idx=0 (24576 bytes)
2015/06/06 18:01:14 unpacking: shards/97 / idx=0 (24576 bytes)
2015/06/06 18:01:14 unpacking: shards/98 / idx=0 (24576 bytes)
2015/06/06 18:01:14 unpacking: shards/99 / idx=0 (24576 bytes)
2015/06/06 18:01:14 restore complete using /home/restore/snapshot.db
```
After restoring, the source database cannot be displayed and after restarting the service the daemon crash with these errors:
```
[srvr] 2015/06/06 18:02:20 GOMAXPROCS set to 2
[srvr] 2015/06/06 18:02:20 using configuration at: /etc/opt/influxdb/influxdb.conf
[srvr] 2015/06/06 18:02:20 influxdb started, version 0.9.0-rc31, commit 8ade485b5865e642b128a7cc6eb20c9da73d1b48
[srvr] 2015/06/06 18:02:20 Cluster server listening on [::]:8086
[srvr] 2015/06/06 18:02:20 broker opened at /home/artica/squid/InfluxDB/raft
[raft] 2015/06/06 18:02:20 stopped[1]: log open: created at /home/artica/squid/InfluxDB/raft/raft, with ID 1, term 1, last applied index of 475075464
[raft] 2015/06/06 18:02:20 log open: promoting to leader immediately
[srvr] 2015/06/06 18:02:20 broker already member of cluster.  Using existing state and ignoring join URLs
[srvr] 2015/06/06 18:02:20 Loading metadata index for 2f7f6399-d937-d289-ba22-00006efa9e8c
[srvr] 2015/06/06 18:02:20 Loading metadata index for 3c330599-0b11-5ca8-0a43-00006fcddc83
panic: invalid page type: 0: 0

goroutine 1 [running]:
github.com/boltdb/bolt.(*Cursor).search(0xc2091b3c40, 0xc2097863a8, 0x4, 0x8, 0x47f8)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/cursor.go:240 +0x1ed
github.com/boltdb/bolt.(*Cursor).seek(0xc2091b3c40, 0xc2097863a8, 0x4, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/cursor.go:152 +0x122
github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc20964f7a8, 0xc2097863a8, 0x4, 0x8, 0xc2097863a8, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/bucket.go:162 +0x228
github.com/boltdb/bolt.(*Bucket).CreateBucketIfNotExists(0xc20964f7a8, 0xc2097863a8, 0x4, 0x8, 0xc2097863a8, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/bucket.go:196 +0x5e
github.com/boltdb/bolt.(*Tx).CreateBucketIfNotExists(0xc20964f790, 0xc2097863a8, 0x4, 0x8, 0x8, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/tx.go:103 +0x64
github.com/influxdb/influxdb.func·052(0xc20964f790, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/shard.go:167 +0x8a
github.com/boltdb/bolt.(*DB).Update(0xc20b8c49c0, 0xc208124fe0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/db.go:547 +0xde
github.com/influxdb/influxdb.(*Shard).open(0xc2080c2b80, 0xc209804420, 0x29, 0x7fa789872168, 0xc209354160, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/shard.go:179 +0x538
github.com/influxdb/influxdb.func·008(0xc20803a570, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:331 +0x944
github.com/influxdb/influxdb.func·003(0xc2080351e0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/metastore.go:54 +0x7f
github.com/boltdb/bolt.(*DB).View(0xc208036ea0, 0xc2081253a0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/db.go:578 +0xe7
github.com/influxdb/influxdb.(*metastore).view(0xc20803a550, 0xc2081253d8, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/metastore.go:54 +0x5d
github.com/influxdb/influxdb.(*Server).load(0xc208060b00, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:347 +0x5e
github.com/influxdb/influxdb.(*Server).Open(0xc208060b00, 0xc20803d830, 0x1e, 0x7fa78986fc38, 0xc20803a540, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:209 +0x567
main.(*RunCommand).openServer(0xc20803d380, 0xc208010af0, 0x1, 0x1, 0xc2080d89e0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:639 +0x4ed
main.(*RunCommand).Open(0xc20803d380, 0xc208070d80, 0xc20802bac0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:336 +0x6da
main.(*RunCommand).Run(0xc20803d380, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:261 +0x7e4
main.main()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x495

goroutine 5 [syscall]:
os/signal.loop()
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc208010530, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010530, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080104d0, 0x0, 0x7fa78986ddb0, 0xc209768128)
	/root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803a4f8, 0xc208055dc8, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803a4f8, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc2080de000, 0x7fa78986e850, 0xc20803a4f8, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7fa78986e850, 0xc20803a4f8, 0x7fa78986e7d0, 0xc2080d89e0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
main.func·007()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:141 +0x5b
created by main.(*Node).openListener
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:151 +0x26e

goroutine 7 [chan receive]:
main.func·004()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:199 +0xed
created by main.startProfiling
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:202 +0x2dc

goroutine 9 [select]:
github.com/influxdb/influxdb/messaging.func·003()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/broker.go:287 +0x16a
created by github.com/influxdb/influxdb/messaging.(*Broker).startTopicTruncation
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/messaging/broker.go:294 +0xad

goroutine 10 [select]:
github.com/influxdb/influxdb/raft.(*Log).applier(0xc2080369c0, 0xc208038660)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:1439 +0x2b8
created by githu
```

**Comment by beckettsean** [comment]
Backup and restore are being re-written with the new write path.
