### ISSUE TITLE
RC32: Panic when running sum on a string value

### ISSUE THREAD

**Issue by srini-raju** [influxdb/influxdb#2843]
When i run a sum(value1) i get the below panic if value1 is a string.

```
panic: interface conversion: interface is string, not float64

goroutine 93 [running]:
github.com/influxdb/influxdb/influxql.MapSum(0xcda210, 0xc2081eef20, 0x0, 0x0)
	/Users/raju/Documents/raju/itsdata/go-projects/src/github.com/influxdb/influxdb/influxql/functions.go:424 +0xac
github.com/influxdb/influxdb/tsdb.(*LocalMapper).NextInterval(0xc2081eef20, 0x0, 0x0, 0x0, 0x0)
	/Users/raju/Documents/raju/itsdata/go-projects/src/github.com/influxdb/influxdb/tsdb/tx.go:385 +0xd3
github.com/influxdb/influxdb/influxql.(*MapReduceJob).processAggregate(0xc2080a0a80, 0xc2080db590, 0x773400, 0xc208109e60, 0x1, 0x1, 0x0, 0x0)
	/Users/raju/Documents/raju/itsdata/go-projects/src/github.com/influxdb/influxdb/influxql/engine.go:778 +0x264
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc2080a0a80, 0xc20812f4a0, 0xf000)
	/Users/raju/Documents/raju/itsdata/go-projects/src/github.com/influxdb/influxdb/influxql/engine.go:170 +0x8ca
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc208113400, 0xc20812f4a0)
	/Users/raju/Documents/raju/itsdata/go-projects/src/github.com/influxdb/influxdb/influxql/engine.go:926 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
	/Users/raju/Documents/raju/itsdata/go-projects/src/github.com/influxdb/influxdb/influxql/engine.go:905 +0x5a

goroutine 1 [chan receive (nil chan), 3 minutes]:
main.(*Main).Run(0xc20801c760, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/Users/raju/Documents/raju/itsdata/go-projects/src/github.com/influxdb/influxdb/cmd/influxd/main.go:60 +0x3d6
main.main()
	/Users/raju/Documents/raju/itsdata/go-projects/src/github.com/influxdb/influxdb/cmd/influxd/main.go:24 +0x1d0
```

**Comment by dgnorton** [comment]
Fixed by #2845.  Closing.
