### ISSUE TITLE
rc33 influxd panic immediately if insert a point having non-exist field

### ISSUE THREAD

**Issue by ziyel** [influxdb/influxdb#2914]
We inserted below two point with line protocol one by one. And the influx panic with following error msgs.

test.test.test.test2,host=host value="20" 1434009080000000000
test.test.test.test2,host=host value="20",value2="20" 1434009080000000000

    panic: field does not exist for value2
    
    goroutine 66 [running]:
    github.com/influxdb/influxdb/tsdb.(*FieldCodec).EncodeFields(0xc208152dd0, 0xc2080e0090, 0x0, 0x0, 0x0, 0x0, 0x0)
            /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/shard.go:525 +0x2fc
    github.com/influxdb/influxdb/tsdb.(*Shard).validateSeriesAndFields(0xc208155bc0, 0xc20812f1c0, 0x1, 0x1, 0x0, 0x0,     0x0, 0x0, 0x0, 0x0, ...)
            /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/shard.go:372 +0xbc3
    github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints(0xc208155bc0, 0xc20812f1c0, 0x1, 0x1, 0x0, 0x0)
            /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/shard.go:114 +0x75
    github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard(0xc20800b7c0, 0xb, 0xc20812f1c0, 0x1, 0x1, 0x0, 0x0)
            /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/store.go:256 +0xf7
    github.com/influxdb/influxdb/cluster.func·002(0xb, 0x1, 0xc20812f1c0, 0x1, 0x1)

I think it should return the error messages other then panic immediately

**Comment by ziyel** [comment]
duplicate issue with #2869
