### ISSUE TITLE
[0.9.0] influxd is not working.

### ISSUE THREAD

**Issue by ghmlee** [influxdb/influxdb#2950]
I installed a `stable` influxdb 0.9.0 from homebrew on OS X 10.10. When I command `influxd`, I got this error messages.

```
 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

GOMAXPROCS set to 4
no configuration provided, using default settings
2015/06/12 12:15:41 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
2015/06/12 12:15:41 read local node id: 1
2015/06/12 12:15:43 [WARN] raft: Heartbeat timeout reached, starting election
2015/06/12 12:15:43 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
2015/06/12 12:15:43 [DEBUG] raft: Votes needed: 1
2015/06/12 12:15:43 [DEBUG] raft: Vote granted. Tally: 1
2015/06/12 12:15:43 [INFO] raft: Election won. Tally: 1
2015/06/12 12:15:43 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
2015/06/12 12:15:43 [INFO] raft: Disabling EnableSingleNode (bootstrap)
2015/06/12 12:15:43 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/06/12 12:15:43 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/06/12 12:15:43 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
panic: interface conversion: interface is nil, not *internal.CreateNodeCommand

goroutine 11 [running]:
github.com/influxdb/influxdb/meta.(*storeFSM).applyCreateNodeCommand(0xc208076640, 0xc2080bd0e0, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/meta/store.go:1310 +0xb6
github.com/influxdb/influxdb/meta.func·023(0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/meta/store.go:1263 +0x91
github.com/influxdb/influxdb/meta.(*storeFSM).Apply(0xc208076640, 0xc20806a740, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/meta/store.go:1299 +0x2f1
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080ba1c0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/raft.go:538 +0xd2d
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/raft.go:242 +0x27
github.com/hashicorp/raft.func·011()
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 1 [select]:
github.com/influxdb/influxdb/meta.(*Store).waitForLeader(0xc208076640, 0x2540be400, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/meta/store.go:367 +0x401
github.com/influxdb/influxdb/meta.(*Store).Open(0xc208076640, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/meta/store.go:189 +0x221
github.com/influxdb/influxdb/cmd/influxd/run.func·003(0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:277 +0x779
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc2080d4000, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:308 +0x5e
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc208044360, 0xc20800a000, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:96 +0x8b5
main.(*Main).Run(0xc2080a9f60, 0xc20800a000, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cmd/influxd/main.go:76 +0x30e
main.main()
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cmd/influxd/main.go:39 +0x1d0

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc208011bf0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011bf0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208011b90, 0x0, 0xd8dca0, 0xc2080d6090)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080381a8, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080381a8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080bcb10, 0xd8ebd8, 0xc2080381a8, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:274 +0x762

goroutine 9 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080381b0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080bcb40, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/meta/store.go:1636 +0x64
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc208011c70)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
created by github.com/hashicorp/raft.NewNetworkTransport
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4

goroutine 10 [runnable]:
syscall.Syscall(0x6, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:20 +0x5
syscall.Close(0x8, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:402 +0x55
os.(*file).close(0xc208130000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file_unix.go:106 +0x6d
os.(*File).Close(0xc20812e000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file_unix.go:98 +0x61
io/ioutil.WriteFile(0xc2080bcbd0, 0x25, 0xc20810e9c4, 0x13, 0x40, 0xc2000001ed, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/ioutil/ioutil.go:85 +0x10d
github.com/hashicorp/raft.(*JSONPeers).SetPeers(0xc2080bcc00, 0xc2081087a0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/peer.go:121 +0x4e3
github.com/hashicorp/raft.(*Raft).processLog(0xc2080ba1c0, 0xc20806a940, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/raft.go:1117 +0x1141
github.com/hashicorp/raft.(*Raft).processLogs(0xc2080ba1c0, 0x11, 0xc2081141e0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/raft.go:1075 +0x444
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080ba1c0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/raft.go:825 +0x3d2
github.com/hashicorp/raft.(*Raft).runLeader(0xc2080ba1c0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/raft.go:779 +0x74e
github.com/hashicorp/raft.(*Raft).run(0xc2080ba1c0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/raft.go:576 +0xc9
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/raft.go:241 +0x27
github.com/hashicorp/raft.func·011()
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 12 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080ba1c0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/raft.go:1594 +0x466
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/raft.go:243 +0x27
github.com/hashicorp/raft.func·011()
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 13 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080381b8, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc208076640)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/meta/store.go:436 +0x8f
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/meta/store.go:183 +0x1c2
```

**Comment by huhongbo** [comment]
delete the meta data and restart the influxdb

**Comment by ghmlee** [comment]
@huhongbo I installed it with homebrew. I tried `brew uninstall influxdb` and `brew install influxdb` again. It is not still working. May I ask you how can I delete the meta data? Where is the path?

**Comment by leelasharma** [comment]
there should be a meta directorty, most likely in /var/lib/influxdb

**Comment by indrekj** [comment]
found it `~/.influxdb/meta`

**Comment by ghmlee** [comment]
@leelasharma @indrekj Thank you. I found it `~/.influxdb/meta` too.
