### ISSUE TITLE
[0.9.0] Panic on starting influxdb

### ISSUE THREAD

**Issue by nklizhe** [influxdb/influxdb#2978]
OS: Ubuntu 14.04.1 LTS

### Steps:
1. download InfluxDB 0.9.0 from: http://influxdb.s3.amazonaws.com/influxdb_0.9.0_amd64.deb
2. dpkg -i influxdb_0.9.0_amd64.deb
3. /opt/influxdb/influxd
4. panic: interface conversion: interface is nil, not *internal.CreateNodeCommand

### Log:
```
/opt/influxdb/influxd

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

GOMAXPROCS set to 8
no configuration provided, using default settings
2015/06/13 09:06:38 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
2015/06/13 09:06:38 read local node id: 1
2015/06/13 09:06:40 [WARN] raft: Heartbeat timeout reached, starting election
2015/06/13 09:06:40 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
2015/06/13 09:06:40 [DEBUG] raft: Votes needed: 1
2015/06/13 09:06:40 [DEBUG] raft: Vote granted. Tally: 1
2015/06/13 09:06:40 [INFO] raft: Election won. Tally: 1
2015/06/13 09:06:40 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
2015/06/13 09:06:40 [INFO] raft: Disabling EnableSingleNode (bootstrap)
2015/06/13 09:06:40 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/06/13 09:06:40 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/06/13 09:06:40 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
panic: interface conversion: interface is nil, not *internal.CreateNodeCommand

goroutine 11 [running]:
github.com/influxdb/influxdb/meta.(*storeFSM).applyCreateNodeCommand(0xc208072640, 0xc208126000, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:1310 +0xb6
github.com/influxdb/influxdb/meta.func·023(0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:1263 +0x91
github.com/influxdb/influxdb/meta.(*storeFSM).Apply(0xc208072640, 0xc20808e780, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:1299 +0x2f1
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080b81c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:538 +0xd2d
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:242 +0x27
github.com/hashicorp/raft.func·011()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 1 [select]:
github.com/influxdb/influxdb/meta.(*Store).waitForLeader(0xc208072640, 0x2540be400, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:367 +0x401
github.com/influxdb/influxdb/meta.(*Store).Open(0xc208072640, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:189 +0x221
github.com/influxdb/influxdb/cmd/influxd/run.func·003(0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:277 +0x779
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc2080d4000, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:308 +0x5e
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc208044360, 0xc20800a000, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:96 +0x8b5
main.(*Main).Run(0xc2080a7f60, 0xc20800a000, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:76 +0x30e
main.main()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:39 +0x1d0

goroutine 6 [syscall]:
os/signal.loop()
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc2080101b0, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080101b0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010150, 0x0, 0x7faa29812cc8, 0xc20800a4e0)
	/root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208038020, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208038020, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080baa50, 0x7faa29814bd8, 0xc208038020, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:274 +0x762

goroutine 9 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038028, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080baa80, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:1636 +0x64
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc208010230)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
created by github.com/hashicorp/raft.NewNetworkTransport
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4

goroutine 10 [runnable]:
log.itoa(0xc208034ad0, 0x6, 0x2)
	/root/.gvm/gos/go1.4.2/src/log/log.go:62
log.(*Logger).formatHeader(0xc208034aa0, 0xc208034ad0, 0xecd0de9a0, 0xc2100b6212, 0x1067300, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/log/log.go:96 +0x705
log.(*Logger).Output(0xc208034aa0, 0x2, 0xc2080fe5a0, 0x48, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/log/log.go:148 +0x20c
log.(*Logger).Printf(0xc208034aa0, 0xb82990, 0x2f, 0xc208123858, 0x3, 0x3)
	/root/.gvm/gos/go1.4.2/src/log/log.go:160 +0x85
github.com/hashicorp/raft.(*Raft).processLog(0xc2080b81c0, 0xc20808ea80, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:1108 +0x5eb
github.com/hashicorp/raft.(*Raft).processLogs(0xc2080b81c0, 0x6, 0xc20810a1e0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:1075 +0x444
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080b81c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:825 +0x3d2
github.com/hashicorp/raft.(*Raft).runLeader(0xc2080b81c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:779 +0x74e
github.com/hashicorp/raft.(*Raft).run(0xc2080b81c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:576 +0xc9
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:241 +0x27
github.com/hashicorp/raft.func·011()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 12 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080b81c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:1594 +0x466
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:243 +0x27
github.com/hashicorp/raft.func·011()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 14 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038030, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc208072640)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:436 +0x8f
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:183 +0x1c2
```

**Comment by nklizhe** [comment]
OK, I think I found the reason: there were old data files in `/root/.influxdb`. No more panic after delete it.
