### ISSUE TITLE
syntactically incorrect line protocol insert panics the database

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3061]
From https://github.com/influxdb/influxdb/issues/2883#issuecomment-113638315

```
> use db
Using database db
> INSERT foo,a=b 123
ERR: Post http://localhost:8086/write?consistency=any&db=db&precision=n&rp=default: EOF
```

Logs:

```
panic: unsupported value type during encode fields: <nil>

goroutine 68 [running]:
github.com/influxdb/influxdb/tsdb.(*FieldCodec).EncodeFields(0xc20802b450, 0xc20816a4b0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/tsdb/shard.go:571 +0xc56
github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints(0xc20811b4c0, 0xc2080d41d0, 0x1, 0x1, 0x0, 0x0)
        /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/tsdb/shard.go:145 +0x427
github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard(0xc208037740, 0xa2, 0xc2080d41d0, 0x1, 0x1, 0x0, 0x0)
        /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/tsdb/store.go:260 +0xf7
github.com/influxdb/influxdb/cluster.func·002(0xa2, 0x1, 0xc2080d41d0, 0x1, 0x1)
        /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cluster/points_writer.go:241 +0xfc
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
        /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x30b
```

**Comment by msiebuhr** [comment]
As opposed to #3062, this happens regardless of there is something in the database or not.

While playing around, I found some other queries crash the servers `insert foo,a=b abc` and `insert foo 123`, while `insert foo` seems to crash the *client*.

**Comment by msiebuhr** [comment]
Created bug #3078 for the client-side bug.
