### ISSUE TITLE
Panic while writing data, converted from JSON

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3179]
Reported by partner in field:

```
2015/06/29 15:59:23 Sending anonymous usage statistics to m.influxdb.com
panic: runtime error: slice bounds out of range

goroutine 82 [running]:
github.com/influxdb/influxdb/tsdb.scanKey(0xc208954d70, 0x93, 0x93, 0x93, 0xea2360, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.TRpE9Rojq9/src/github.com/influxdb/influxdb/tsdb/points.go:267 +0x59f
github.com/influxdb/influxdb/tsdb.parsePoint(0xc208954d70, 0x93, 0x93, 0xecd23625c, 0x15d951a0, 0xe9b4c0, 0xacf1b0, 0x1, 0x0, 0x0, ...)
        /tmp/tmp.TRpE9Rojq9/src/github.com/influxdb/influxdb/tsdb/points.go:141 +0x86
github.com/influxdb/influxdb/tsdb.ParsePointsWithPrecision(0xc208730008, 0x224dfb, 0x224dfb, 0xecd23625c, 0xc215d951a0, 0xe9b4c0, 0xacf1b0, 0x1, 0x0, 0x0, ...)
        /tmp/tmp.TRpE9Rojq9/src/github.com/influxdb/influxdb/tsdb/points.go:124 +0x22a
github.com/influxdb/influxdb/tsdb.ParsePoints(0xc208730008, 0x224dfb, 0x224dfb, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.TRpE9Rojq9/src/github.com/influxdb/influxdb/tsdb/points.go:102 +0xe8
github.com/influxdb/influxdb/services/hh.(*Processor).unmarshalWrite(0xc20800c600, 0xc208730000, 0x224e03, 0x224e03, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.TRpE9Rojq9/src/github.com/influxdb/influxdb/services/hh/processor.go:201 +0x101
github.com/influxdb/influxdb/services/hh.func·002(0x2, 0xc20800c660)
        /tmp/tmp.TRpE9Rojq9/src/github.com/influxdb/influxdb/services/hh/processor.go:146 +0x20b
created by github.com/influxdb/influxdb/services/hh.(*Processor).Process
        /tmp/tmp.TRpE9Rojq9/src/github.com/influxdb/influxdb/services/hh/processor.go:177 +0x1f7

goroutine 1 [chan receive (nil chan)]:
main.(*Main).Run(0xc20831ef60, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /tmp/tmp.TRpE9Rojq9/src/github.com/influxdb/influxdb/cmd/influxd/main.go:75 +0x450
main.main()
        /tmp/tmp.TRpE9Rojq9/src/github.com/influxdb/influxdb/cmd/influxd/main.go:35 +0x1d0

goroutine 6 [syscall]:
```

**Comment by otoolep** [comment]
cc @jwilder

**Comment by otoolep** [comment]
Partner cannot reproduce.
