### ISSUE TITLE
[0.9.0] Mixing aggregate function and arithmetic operator crashes influx

### ISSUE THREAD

**Issue by mihaicostin** [influxdb/influxdb#3198]
```
$ brew info influxdb
influxdb: stable 0.9.0 (bottled), HEAD
```
The values were stored as float using the line protocol `series3 a=10.0,b=11.0`

```
> select * from series3
name: series3
-------------
time				a	b
2015-06-30T20:24:48.52864879Z	10	11
2015-06-30T20:24:49.05526346Z	10	11
2015-06-30T20:24:49.651337776Z	10	11
2015-06-30T20:24:50.220320572Z	10	11

> select count(a),a+b from series3
ERR: Get http://localhost:8086/query?db=mydb&q=select+count%28a%29%2Ca%2Bb+from+series3: EOF
```

and influxd 
```
2015/06/30 23:33:08 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[http] 2015/06/30 23:33:19 127.0.0.1 - - [30/Jun/2015:23:33:19 +0300] GET /query?db=mydb&q=select+%2A+from+series3 HTTP/1.1 200 159 - InfluxDBShell/0.9.0 3ea650be-1f67-11e5-8001-000000000000 1.664083ms
panic: runtime error: index out of range

goroutine 24 [running]:
github.com/influxdb/influxdb/influxql.func·004(0xc2081b7180, 0x2, 0x2, 0x1da3c, 0x4d9ec0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/influxql/engine.go:600 +0x4a
github.com/influxdb/influxdb/influxql.func·006(0xc2081b7180, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/influxql/engine.go:621 +0x64
github.com/influxdb/influxdb/influxql.(*MapReduceJob).processResults(0xc2080111f0, 0xc2081b7160, 0x1, 0x1, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/influxql/engine.go:519 +0x4d1
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc2080111f0, 0xc2081c5ce0, 0x0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/influxql/engine.go:194 +0xc41
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc2081c9500, 0xc2081c5ce0)
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/influxql/engine.go:926 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
	/private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/influxql/engine.go:905 +0x5a

....
```
Same thing happens for mean.
admittedly, the query doesn't make much sense but it could return something similar to `select count(a),a from series3` instead of crashing

BTW, it's it possible anymore to use expression as parameters for aggregate functions ? It used to work in previous versions of influx:
```
> select mean(a+b) from series3
ERR: expected field argument in mean()
```

**Comment by beckettsean** [comment]
@mihaicostin I don't believe operators are legal inside of function parameters for 0.9. If you have a use case for that please open a new issue.

I'm not sure why the math is causing a panic but we'll prioritize that.

**Comment by beckettsean** [comment]
Verified `select count(a), a+b from test1` where `a` and `b` are both floats still panics 0.9.1.

**Comment by beckettsean** [comment]
Still panics 0.9.2

**Comment by otoolep** [comment]
Mixing aggregate and non-aggregate queries is not supported by InfluxDB. It should not panic, so I can fix that, but mixing query types is not currently on the road map.

**Comment by otoolep** [comment]
Fixed  by https://github.com/influxdb/influxdb/pull/3625

**Comment by otoolep** [comment]
Panic fixed.

**Comment by otoolep** [comment]
Thanks for the report @mihaicostin
