### ISSUE TITLE
InfluxDB server runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by buro1983** [influxdb/influxdb#3227]
I was trying to insert series using CURL. I have observed that if I don't put quote around data part of HTTP POST then influx server is throwing panic but server  is not crashing. Please find the trace below,

```
http: panic serving <ip:port>: runtime error: slice bounds out of range
goroutine 761 [running]:
net/http.funcÂ·011()
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb/tsdb.scanKey(0xc208039c00, 0x5f, 0x200, 0x5f, 0x7fb01a9830b8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/points.go:239 +0x59f
github.com/influxdb/influxdb/tsdb.parsePoint(0xc208039c00, 0x5f, 0x200, 0xecd289393, 0x1d3f0be, 0x10604c0, 0xc20816210c, 0x1, 0x0, 0x0, ...)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/points.go:113 +0x86
github.com/influxdb/influxdb/tsdb.ParsePointsWithPrecision(0xc208039c00, 0x5f, 0x200, 0xecd289393, 0x1d3f0be, 0x10604c0, 0xc20816210c, 0x1, 0x0, 0x0, ...)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/points.go:96 +0x1d0
github.com/influxdb/influxdb/services/httpd.(*Handler).serveWriteLine(0xc20800e310, 0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0, 0xc208039c00, 0x5f, 0x200, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:422 +0x1ca
github.com/influxdb/influxdb/services/httpd.(*Handler).serveWrite(0xc20800e310, 0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:326 +0x69d
github.com/influxdb/influxdb/services/httpd.*Handler.(github.com/influxdb/influxdb/services/httpd.serveWrite)Â·fm(0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:98 +0x4f
github.com/influxdb/influxdb/services/httpd.funcÂ·001(0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:601 +0x78
net/http.HandlerFunc.ServeHTTP(0xc20801caa0, 0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.funcÂ·002(0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:652 +0xd9
net/http.HandlerFunc.ServeHTTP(0xc2080ddd70, 0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.funcÂ·003(0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:668 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc20801cac0, 0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.funcÂ·004(0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:701 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc2080dddb0, 0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.funcÂ·005(0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:711 +0x179
net/http.HandlerFunc.ServeHTTP(0xc2080dddd0, 0x7fb01a9818d8, 0xc2081510c0, 0xc2080d75f0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.funcÂ·006(0x7fb01a9818d8, 0xc2081510a0, 0xc2080d75f0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:719 +0x123
net/http.HandlerFunc.ServeHTTP(0xc20801cae0, 0x7fb01a9818d8, 0xc2081510a0, 0xc2080d75f0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.funcÂ·007(0x7fb01a981128, 0xc208071680, 0xc2080d75f0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:729 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc20801cb00, 0x7fb01a981128, 0xc208071680, 0xc2080d75f0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc2080365a0, 0x7fb01a981128, 0xc208071680, 0xc2080d75f0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc20800e310, 0x7fb01a981128, 0xc208071680, 0xc2080d75f0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/handler.go:166 +0x256
net/http.serverHandler.ServeHTTP(0xc208045c20, 0x7fb01a981128, 0xc208071680, 0xc2080d75f0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080715e0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e
```

**Comment by beckettsean** [comment]
Can you include the `curl` statement you were running?

**Comment by beckettsean** [comment]
I cannot reproduce. 

```
## Succeeds:
$ curl -X POST 'http://localhost:8086/write?db=mydb' --data-binary 'disk_free,hostname=server01 value=442221834240 1435362189575692182'

## Fails but does not cause any error, just a 400 response to `curl`
$ curl -X POST 'http://localhost:8086/write?db=mydb' --data-binary disk_free,hostname=server01 value=442221834240 1435362189575692182
unable to parse 'disk_free,hostname=server01': invalid field format
curl: (6) Could not resolve host: value=442221834240

## Fails but does not cause any error, just a 400 response to `curl`
$ curl -X POST 'http://localhost:8086/write?db=mydb' --data-binary disk_free value=442221834240 
unable to parse 'disk_free': invalid field format
curl: (6) Could not resolve host: value=442221834240
```
