### ISSUE TITLE
[0.9.0] Trouble restarting influxdb

### ISSUE THREAD

**Issue by phagunbaya** [influxdb/influxdb#3472]
I have few 100 megs of data and running in a single influx node. When I restart influxdb I get below error and it crashes.

```
2015/07/27 17:08:19 [INFO] raft: Starting snapshot up to 11727
2015/07/27 17:08:19 [INFO] snapshot: Creating new snapshot at /var/opt/influxdb/meta/snapshots/3284-11727-1438016899306.tmp
panic: not implemented yet

goroutine 12 [running]:
github.com/influxdb/influxdb/meta.(*storeFSMSnapshot).Persist(0xc209e0e038, 0x7f6987965938, 0xc2080441e0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:1592 +0x76
github.com/hashicorp/raft.(*Raft).takeSnapshot(0xc2080be1c0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:1674 +0x826
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080be1c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:1602 +0x105
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:243 +0x27
github.com/hashicorp/raft.func·011()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 1 [chan receive (nil chan), 2 minutes]:
main.(*Main).Run(0xc208019f60, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x450
main.main()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:39 +0x1d0

goroutine 6 [syscall, 3 minutes]:
os/signal.loop()
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
	/root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait, 3 minutes]:
net.(*pollDesc).Wait(0xc2080103e0, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080103e0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010380, 0x0, 0x7f6ab47fccc8, 0xc208068000)
	/root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803e7c8, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803e7c8, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080c1c20, 0x7f6ab47ff338, 0xc20803e7c8, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:274 +0x762

goroutine 9 [chan receive, 3 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803e7d0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080c1c50, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:1636 +0x64
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc208010460)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
created by github.com/hashicorp/raft.NewNetworkTransport
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080be1c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:807 +0xc7c
github.com/hashicorp/raft.(*Raft).runLeader(0xc2080be1c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:779 +0x74e
github.com/hashicorp/raft.(*Raft).run(0xc2080be1c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:576 +0xc9
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:241 +0x27
github.com/hashicorp/raft.func·011()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 11 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080be1c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:490 +0xf74
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:242 +0x27
github.com/hashicorp/raft.func·011()
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 13 [chan receive, 3 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803e7d8, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc20802c000)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:436 +0x8f
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:183 +0x1c2

goroutine 34 [select, 3 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc208062000, 0xc20802e420)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:390 +0x14a
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:280 +0x8d3

goroutine 35 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc208045220)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/hh/service.go:98 +0x2e7
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/hh/service.go:62 +0xef

goroutine 36 [select, 2 minutes]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc208045220)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/hh/service.go:116 +0x2a4
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/hh/service.go:63 +0x109

goroutine 37 [chan receive, 2 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803e7e0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc208010230)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cluster/service.go:79 +0x102
created by github.com/influxdb/influxdb/cluster.(*Service).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cluster/service.go:56 +0x67

goroutine 38 [select, 2 minutes]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc208030d20)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/precreator/service.go:72 +0x407
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/precreator/service.go:50 +0xcb

goroutine 39 [chan receive, 2 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803e7e8, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc208030e10)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/snapshotter/service.go:68 +0xad
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/snapshotter/service.go:46 +0x62

goroutine 40 [IO wait, 2 minutes]:
net.(*pollDesc).Wait(0xc212b96530, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc212b96530, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc212b964d0, 0x0, 0x7f6ab47fccc8, 0xc2165212a8)
	/root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc209e0eaa0, 0xc208021c00, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc209e0eaa0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc216ebf080, 0x7f6ab47ff338, 0xc209e0eaa0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f6ab47ff338, 0xc209e0eaa0, 0x7f69be44bf40, 0xc2165212e0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc2080c1a10)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/admin/service.go:71 +0x147
created by github.com/influxdb/influxdb/services/admin.(*Service).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/admin/service.go:39 +0xd9

goroutine 41 [select]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc2080102a0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:151 +0x1fc
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:87 +0x1ed

goroutine 42 [IO wait, 2 minutes]:
net.(*pollDesc).Wait(0xc212b965a0, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc212b965a0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc212b96540, 0x0, 0x7f6ab47fccc8, 0xc216521318)
	/root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc209e0eaa8, 0xc208021c00, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc209e0eaa8, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc216ebf0e0, 0x7f6ab47ff338, 0xc209e0eaa8, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f6ab47ff338, 0xc209e0eaa8, 0x7f69be44bf68, 0xc208010310, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc20808f7c0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/service.go:83 +0x79
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/service.go:51 +0x283

goroutine 43 [select, 2 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc20802e8a0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/retention/service.go:67 +0x433
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/retention/service.go:44 +0x67

goroutine 44 [select, 2 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc20802e8a0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/retention/service.go:101 +0x821
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x81

goroutine 45 [chan receive, 2 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc208062000)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:341 +0x5e
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:303 +0xd78

goroutine 46 [select, 2 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc20802e360)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:118 +0x2da
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:102 +0xa1a
```

Is it related to resource usage, if yes then the node has plenty of it or something else ?

**Comment by marcospedreiro** [comment]
+1 blocking issue

**Comment by mjdesa** [comment]
@phagunbaya can you verify that this is still broken in v0.9.2?

**Comment by beckettsean** [comment]
Closing due to lack of repro case. Snapshotting is improved in 0.9.2+, will re-open if there's an issue in 0.9.3+
