### ISSUE TITLE
[0.9.2] Sending a large number of tag causes panic

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb#3511]
```
015/07/29 18:39:44 http: panic serving 127.0.0.1:63422: runtime error: index out of range
goroutine 1010 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb/tsdb.scanKey(0xc215dbe000, 0xb11, 0xfffe00, 0xaf3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/points.go:276 +0x1350
github.com/influxdb/influxdb/tsdb.parsePoint(0xc215dbe000, 0xb11, 0xfffe00, 0xecd4b7760, 0x17f767e7, 0xab0dc0, 0x6d6db0, 0x1, 0x0, 0x0, ...)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/points.go:141 +0x86
github.com/influxdb/influxdb/tsdb.ParsePointsWithPrecision(0xc215dbe000, 0xd84730, 0xfffe00, 0xecd4b7760, 0x17f767e7, 0xab0dc0, 0x6d6db0, 0x1, 0x0, 0x0, ...)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/points.go:124 +0x22a
github.com/influxdb/influxdb/services/httpd.(*Handler).serveWriteLine(0xc2080102a0, 0x245dd40, 0xc20f0e28e0, 0xc20cdd2000, 0xc215dbe000, 0xd84730, 0xfffe00, 0x0)
```

**Comment by mjdesa** [comment]
@toddboom to recreate the issue set

```toml
[series]
num_tags = 100
num_keys = 1
```

in the `stress` script toml file. 

Everything is fine if `num_tags`<100.

**Comment by mjdesa** [comment]
Found the [problem](https://github.com/influxdb/influxdb/blob/master/tsdb/points.go#L203). If you up this value then everything work.

**Comment by toddboom** [comment]
Super lame. Nice catch, btw. This should definitely be handled better.
