### ISSUE TITLE
[0.9.2] Using AND in a SELECT statement causing panic

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb#3542]
From issue https://github.com/influxdb/influxdb/issues/3525

```
select value AND value from cpu
```

causes db to panic

```
panic: interface conversion: interface is float64, not map[string]interface {}

goroutine 52 [running]:
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc208042000, 0xc208176000, 0x2710, 0x2710, 0x0)
    /Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/executor.go:689 +0xc63
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Add(0xc208042000, 0xc20815e000, 0x2710, 0x3000, 0xd26bd0)
    /Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/executor.go:587 +0x370
github.com/influxdb/influxdb/tsdb.(*Executor).executeRaw(0xc20827c210, 0xc208252120)
    /Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/executor.go:285 +0x951
created by github.com/influxdb/influxdb/tsdb.(*Executor).Execute
    /Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/executor.go:82 +0x89
```

**Comment by beckettsean** [comment]
@mjdesa what about `select field and tag` or `select field1 AND field2`? Do those behave any differently?

**Comment by mjdesa** [comment]
Just tested, and yeah. 

```
select value AND value from cpu
```

causes panic, while

```
select value AND other_value from cpu
```

doesnt

**Comment by beckettsean** [comment]
No longer panics in 0.9.3 nightly

```
> show field keys
name: thing
-----------
fieldKey
othervalue
value

> select value and value from thing
ERR: error parsing query: invalid operator AND in SELECT clause at line 1, char 8; operator is intended for WHERE clause
> select value and othervalue from thing
ERR: error parsing query: invalid operator AND in SELECT clause at line 1, char 8; operator is intended for WHERE clause

```
