### ISSUE TITLE
[ 0.9.3-nightly-be792b9] Querying data node causes panic

### ISSUE THREAD

**Issue by mail2fish** [influxdb/influxdb#3574]
```
[http] 2015/08/06 17:06:37 ::1 - - [06/Aug/2015:17:06:37 +0800] GET /query?q=SELECT+max+FROM+%22Requests%22+&db=throne HTTP/1.1 200 210 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0 712beabc-3c1a-11e5-80ca-000000000000 1.365744ms
panic: interface conversion: interface is float64, not map[string]interface {}

goroutine 408 [running]:
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc208504000, 0xc2083ba000, 0xa, 0x2710, 0x0)
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:758 +0xc63
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc208504000)
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:693 +0xba
github.com/influxdb/influxdb/tsdb.(*RawExecutor).execute(0xc208560330, 0xc20806a9c0)
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:149 +0x2d7
created by github.com/influxdb/influxdb/tsdb.(*RawExecutor).Execute
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:93 +0x5a
```

**Comment by corylanou** [comment]
It's possible that this is fixed in https://github.com/influxdb/influxdb/pull/3564.  Based on the query, you should of hit the first branch of the if statement and didn't.  Once this is merged to master and you upgrade let's re-check this.

**Comment by mjdesa** [comment]
I get the same panic when I query a data node in a cluster in version 0.9.3-nightly-be792b9, commit be792b926a86bad31b8e3c9e0d997a6ede31dc70

Steps to repro in AWS:

1. Launch 4 AWS instances and Install Influxdb on each node.
2. On each node update set `hostname = "<Instances Private DNS>"`  in the meta section of `/etc/opt/influxdb/influxdb.conf`.
3. Start InfluxDB on one node.
4. On another node in `/etc/init.d/influxdb` set `INFLUXD_OPTS="-join addr_1:port_1"`.
5. Start InfluxDB on that node.
6. On another node in `/etc/init.d/influxdb` set `INFLUXD_OPTS="-join addr_1:port_1,addr_2:port_2"`.
7. Start InfluxDB on that node.
8. On another node in `/etc/init.d/influxdb` set `INFLUXD_OPTS="-join addr_1:port_1,addr_2:port_2"`.
9. Start InfluxDB on that node.
10. Write one point to each of the nodes.
11. Query the 3 raft nodes (should see all 4 points).
12. Query the 1 data node. (should cause panic).

```
panic: interface conversion: interface is float64, not map[string]interface {}

goroutine 72 [running]:
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc2080ea000, 0xc2081ae000, 0x1, 0x2710, 0x0)
	/tmp/tmp.IrAPUmtyJ8/src/github.com/influxdb/influxdb/tsdb/executor.go:734 +0x10bf
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc2080ea000)
	/tmp/tmp.IrAPUmtyJ8/src/github.com/influxdb/influxdb/tsdb/executor.go:660 +0xd6
github.com/influxdb/influxdb/tsdb.(*Executor).executeRaw(0xc208180090, 0xc2080801e0)
	/tmp/tmp.IrAPUmtyJ8/src/github.com/influxdb/influxdb/tsdb/executor.go:239 +0x1211
created by github.com/influxdb/influxdb/tsdb.(*Executor).Execute
	/tmp/tmp.IrAPUmtyJ8/src/github.com/influxdb/influxdb/tsdb/executor.go:88 +0x9a
```
