### ISSUE TITLE
[0.9.2] Out of memory panic when starting influx

### ISSUE THREAD

**Issue by hworld** [influxdb/influxdb#3668]
Using a Digital Ocean Droplet: 4GB Ram, 2 Cores, SSD Disk. Fedora 22 installed on it. Using the current version of InfluxDB: 0.9.2.

I used a test script to write a bunch of data that's similar to my use case. It creates a lot of unique tag values.

Here's the PHP script I'm using to write in test data:

```php
$n = 0;
while ( $n < 30000000 ) {

	$influxRows = [];

	foreach ( range( 0, 1000 ) as $i ) {

		$userId = 0;
		if ( mt_rand( 1, 100 ) > 50 ) {
			$userId = mt_rand( 1, 500000 );  // 500 thousand users.
		}

		$x = mt_rand( 1, 100 );
		if ( $x < 95 ) {
			$gameId = mt_rand( 1, 10000 );
		}
		else {
			$gameId = mt_rand( 10001, 80000 );
		}

		$ipAddress = mt_rand( 0, 255 );
		$ipAddress = "{$ipAddress}.{$ipAddress}.{$ipAddress}.{$ipAddress}";

		$influxRows[] = [
			'measurement' => 'download',
			'fields' => [
				'value' => 1,
				'ip_address' => (string)$ipAddress,
			],
			'tags' => [
				'game_id' => (string)$gameId,
				'logged_user_id' => (string)$userId,
			],
		];

		++$n;
	}

	$client->mark( [ 'points' => $influxRows ] );
}
```

I'm trying to create events, such as a "download" event for a file. I pushed in chunks of 1k points each batch. Memory climbed for a while, but then stayed steady as the OS handled the mmap'ed file correctly. Eventually it OOMs like the error below. Any time I try to start influxdb up again, it fails with the same error. It also takes a really long time to load up influxdb, memory climbs the whole time, and eventually it just crashes.  About 3mil points were written before getting into this state.

I need to be able to query on the game_id and the user_id in some cases, which is why the user id is part of the tags. This will obviously create really high cardinality fields. Is this what's causing it to fail? I would expect influx to be able to stream the data from the FS into memory to operate on. Could it be that information about all the unique series created takes too much memory?

I also notice that it's dying during the flush. Could it be that the flushing is batching up too many points per write that overflows memory?

```
[metastore] 2015/08/14 17:16:52 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
[metastore] 2015/08/14 17:16:52 read local node id: 1
[metastore] 2015/08/14 17:16:53 [WARN] raft: Heartbeat timeout reached, starting election
[metastore] 2015/08/14 17:16:53 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
[metastore] 2015/08/14 17:16:53 [DEBUG] raft: Votes needed: 1
[metastore] 2015/08/14 17:16:53 [DEBUG] raft: Vote granted. Tally: 1
[metastore] 2015/08/14 17:16:53 [INFO] raft: Election won. Tally: 1
[metastore] 2015/08/14 17:16:53 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
[metastore] 2015/08/14 17:16:53 [INFO] raft: Disabling EnableSingleNode (bootstrap)
[metastore] 2015/08/14 17:16:53 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/14 17:16:53 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/14 17:16:53 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/14 17:16:53 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/14 17:16:53 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[shard] 2015/08/14 17:18:18 flush 181228 points in 23.744s
[shard] 2015/08/14 17:18:38 flush 180260 points in 20.035s
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc2e2320000, 0x100000, 0xed6b00, 0xed1418)
	/root/.gvm/gos/go1.4.2/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0xed6b00, 0x100000, 0x431712)
	/root/.gvm/gos/go1.4.2/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0xed6b00, 0x1, 0x1000000002b, 0x40f8ae)
	/root/.gvm/gos/go1.4.2/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0xee0498, 0x7f6429b21f48)
	/root/.gvm/gos/go1.4.2/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x7f64b2d4d000, 0xc20000002b, 0x7f6429b21f48)
	/root/.gvm/gos/go1.4.2/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
	/root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:198 fp=0xc2080b0b80 sp=0xc2080b0b78
runtime.mallocgc(0x1000, 0xa4f580, 0x7f6400000000, 0x2a)
	/root/.gvm/gos/go1.4.2/src/runtime/malloc.go:178 +0x849 fp=0xc2080b0c30 sp=0xc2080b0b80
runtime.newarray(0xa4f580, 0x40, 0xc2e2317800)
	/root/.gvm/gos/go1.4.2/src/runtime/malloc.go:365 +0xc1 fp=0xc2080b0c68 sp=0xc2080b0c30
runtime.growslice(0x8feb60, 0xc2e2317800, 0x1b, 0x1b, 0x1, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/runtime/slice.go:87 +0x2bb fp=0xc2080b0cc8 sp=0xc2080b0c68
github.com/boltdb/bolt.(*node).put(0xc2e2309c70, 0xc284642030, 0x2a, 0x2a, 0xc284642030, 0x2a, 0x2a, 0xc2514ebd80, 0x20, 0x20, ...)
	/root/go/src/github.com/boltdb/bolt/node.go:131 +0x470 fp=0xc2080b0e08 sp=0xc2080b0cc8
github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc2906b72c8, 0xc284642030, 0x2a, 0x2a, 0x7fffffff, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/bucket.go:183 +0x59c fp=0xc2080b1000 sp=0xc2080b0e08
github.com/boltdb/bolt.(*Bucket).CreateBucketIfNotExists(0xc2906b72c8, 0x7f6467cf36b6, 0x2a, 0x7ffffff3, 0x7f6467cf36aa, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/bucket.go:196 +0x5e fp=0xc2080b1058 sp=0xc2080b1000
github.com/boltdb/bolt.(*Tx).CreateBucketIfNotExists(0xc2906b72b0, 0x7f6467cf36b6, 0x2a, 0x7ffffff3, 0x2a, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/tx.go:103 +0x64 fp=0xc2080b1098 sp=0xc2080b1058
github.com/influxdb/influxdb/tsdb.func·015(0xc2906b72b0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:428 +0x2fc fp=0xc2080b1228 sp=0xc2080b1098
github.com/boltdb/bolt.(*DB).Update(0xc208118000, 0xc2080b1338, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/db.go:547 +0xde fp=0xc2080b1290 sp=0xc2080b1228
github.com/influxdb/influxdb/tsdb.(*Shard).FlushPartition(0xc2080460b0, 0xc2080b1404, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:447 +0x103 fp=0xc2080b1378 sp=0xc2080b1290
github.com/influxdb/influxdb/tsdb.(*Shard).Flush(0xc2080460b0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:387 +0x143 fp=0xc2080b1490 sp=0xc2080b1378
github.com/influxdb/influxdb/tsdb.(*Shard).Open(0xc2080460b0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:158 +0xd5 fp=0xc2080b1538 sp=0xc2080b1490
github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0xc20802e480, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/store.go:240 +0xa2a fp=0xc2080b1808 sp=0xc2080b1538
github.com/influxdb/influxdb/tsdb.(*Store).Open(0xc20802e480, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/store.go:266 +0x19a fp=0xc2080b1868 sp=0xc2080b1808
github.com/influxdb/influxdb/cmd/influxd/run.func·003(0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:310 +0x961 fp=0xc2080b1a20 sp=0xc2080b1868
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc2080b60e0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:332 +0x5e fp=0xc2080b1a60 sp=0xc2080b1a20
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc208011c00, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:97 +0x7ab fp=0xc2080b1c18 sp=0xc2080b1a60
main.(*Main).Run(0xc20809ba80, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:76 +0x3bc fp=0xc2080b1ec0 sp=0xc2080b1c18
main.main()
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:38 +0xdc fp=0xc2080b1f98 sp=0xc2080b1ec0
runtime.main()
	/root/.gvm/gos/go1.4.2/src/runtime/proc.go:63 +0xf3 fp=0xc2080b1fe0 sp=0xc2080b1f98
runtime.goexit()
	/root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080b1fe8 sp=0xc2080b1fe0

goroutine 6 [syscall, 1 minutes]:
os/signal.loop()
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 18 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803ab00, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc208074000)
	/root/go/src/github.com/influxdb/influxdb/meta/store.go:470 +0x8f
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/root/go/src/github.com/influxdb/influxdb/meta/store.go:205 +0x1c2

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait, 1 minutes]:
net.(*pollDesc).Wait(0xc208010370, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010370, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010310, 0x0, 0x7f64b2d5ecc8, 0xc208066000)
	/root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803aaf0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803aaf0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080bb950, 0x7f64b2d61308, 0xc20803aaf0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:298 +0x7a8

goroutine 9 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803aaf8, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080bb980, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/meta/store.go:1855 +0x64
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc2080103f0)
	/root/go/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
created by github.com/hashicorp/raft.NewNetworkTransport
	/root/go/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc20800c380)
	/root/go/src/github.com/hashicorp/raft/raft.go:807 +0xc7c
github.com/hashicorp/raft.(*Raft).runLeader(0xc20800c380)
	/root/go/src/github.com/hashicorp/raft/raft.go:779 +0x74e
github.com/hashicorp/raft.(*Raft).run(0xc20800c380)
	/root/go/src/github.com/hashicorp/raft/raft.go:576 +0xc9
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
	/root/go/src/github.com/hashicorp/raft/raft.go:241 +0x27
github.com/hashicorp/raft.func·011()
	/root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 11 [select, 1 minutes]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc20800c380)
	/root/go/src/github.com/hashicorp/raft/raft.go:490 +0xf74
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
	/root/go/src/github.com/hashicorp/raft/raft.go:242 +0x27
github.com/hashicorp/raft.func·011()
	/root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 12 [select, 1 minutes]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc20800c380)
	/root/go/src/github.com/hashicorp/raft/raft.go:1594 +0x466
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
	/root/go/src/github.com/hashicorp/raft/raft.go:243 +0x27
github.com/hashicorp/raft.func·011()
	/root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 19 [select, 1 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc2080b60e0, 0xc20802e1e0)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:421 +0x14a
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:304 +0x919

goroutine 20 [select]:
github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc2080460b0, 0xc208102840)
	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:468 +0x39d
created by github.com/influxdb/influxdb/tsdb.func·010
	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611
```

**Comment by hworld** [comment]
Just adding a bit more info. There's only one DB created, no cluster/replication, only this single measurement, and no CQs. Using default config file as well.

**Comment by mjdesa** [comment]
@hworld correct me if I'm mistaken, but seems like you have about 50k users and 8k different games, which would be about 400 million unique series. Is this wrong?

**Comment by hworld** [comment]
Way worse than that. 500k users and 80k different games in this scenario. The amount of series is pretty staggering. Though, remember that I've only written 3 million points, so the max series it can have is 3 million at the moment. 

I'm curious if the OOM is related to the number of series, or something else. I couldn't find much information on how the data is stored on disk/memory and used. Issuing queries against the measurement with just 500k points written such as: `select count(value) from download where game_id = '1'` returned really fast. 200ms or so. Seems like influx was really performant with many series for selects, at least.

**Comment by mjdesa** [comment]
>I need to be able to query on the game_id and the user_id in some cases, which is why the user id is part of the tags. This will obviously create really high cardinality fields. Is this what's causing it to fail? I would expect influx to be able to stream the data from the FS into memory to operate on. Could it be that information about all the unique series created takes too much memory?

Tags are kept in an inverted index in RAM. I'm fairly certain that your tag-set cardinality is what is causing the issue.

**Comment by mjdesa** [comment]
With 4GB of RAM I'd recommend keeping your total number of series below 1 million.

**Comment by jwilder** [comment]
4GB of RAM is definitely not enough for this many series on a single server currently.  This is a similar issue to #3644.
