### ISSUE TITLE
TestCluster_Restart failing on CircleCI

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3677]
Failing due a timeout.

https://circle-artifacts.com/gh/influxdb/influxdb/4795/artifacts/0/tmp/circle-artifacts.oQFPcts/test_logs.txt

=== RUN TestCluster_Restart
[metastore] 2015/08/14 22:52:08 adding new raft peer: nodeId=2 addr=127.0.0.1:46112
[metastore] 2015/08/14 22:52:08 adding new raft peer: nodeId=3 addr=127.0.0.1:39852
panic: test timed out after 8m0s

goroutine 643 [running]:
testing.funcÂ·008()
	/usr/local/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive, 7 minutes]:
testing.RunTests(0xb0a4e8, 0xcc6be0, 0x6d, 0x6d, 0xc20802b701)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208046910, 0xcd1400)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/influxdb/influxdb/meta/_test/_testmain.go:270 +0x1d5

**Comment by otoolep** [comment]
@jwilder

**Comment by otoolep** [comment]
Second failure:

https://circle-artifacts.com/gh/influxdb/influxdb/4813/artifacts/1/tmp/circle-artifacts.BNjLOBk/test_logs_race.txt

**Comment by otoolep** [comment]
For the record, still happening.

https://circle-artifacts.com/gh/influxdb/influxdb/5438/artifacts/0/tmp/circle-artifacts.GOc3MlF/test_logs.txt

cc @jwilder @benbjohnson

**Comment by otoolep** [comment]
https://circle-artifacts.com/gh/influxdb/influxdb/5574/artifacts/0/tmp/circle-artifacts.yJ0Qnoy/test_logs.txt

**Comment by otoolep** [comment]
This failure continues to occur fairly regularly.

**Comment by otoolep** [comment]
Great stuff.
