### ISSUE TITLE
[0.9.3 rc-1] panic - index out of range in http write hander

### ISSUE THREAD

**Issue by jhorwit2** [influxdb/influxdb#3794]
```
2015/08/21 15:30:16 http: panic serving 10.15.5.228:41759: runtime error: index out of range
goroutine 113 [running]:
net/http.func·011()
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb/services/httpd.(*Handler).serveWriteLine(0xc20800e2a0, 0x7f9a8c70c920, 0xc20801c120, 0xc208110000, 0xc20804e200, 0x1, 0x200, 0x0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:425 +0x1150
github.com/influxdb/influxdb/services/httpd.(*Handler).serveWrite(0xc20800e2a0, 0x7f9a8c70c920, 0xc20801c120, 0xc208110000, 0x0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:346 +0x69d
github.com/influxdb/influxdb/services/httpd.*Handler.(github.com/influxdb/influxdb/services/httpd.serveWrite)·fm(0x7f9a8c70c920, 0xc20801c120, 0xc208110000, 0x0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:103 +0x4f
github.com/influxdb/influxdb/services/httpd.func·001(0x7f9a8c70c920, 0xc20801c120, 0xc208110000)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:621 +0x78
net/http.HandlerFunc.ServeHTTP(0xc2080a10c0, 0x7f9a8c70c920, 0xc20801c120, 0xc208110000)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·002(0x7f9a8c70c848, 0xc20801d080, 0xc208110000)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:679 +0x288
net/http.HandlerFunc.ServeHTTP(0xc2080c9820, 0x7f9a8c70c848, 0xc20801d080, 0xc208110000)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·003(0x7f9a8c70c848, 0xc20801d080, 0xc208110000)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:688 +0xba
net/http.HandlerFunc.ServeHTTP(0xc2080a10e0, 0x7f9a8c70c848, 0xc20801d080, 0xc208110000)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·004(0x7f9a8c70c848, 0xc20801d080, 0xc208110000)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:721 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc2080c9850, 0x7f9a8c70c848, 0xc20801d080, 0xc208110000)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·005(0x7f9a8c70c848, 0xc20801d080, 0xc208110000)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:731 +0x179
net/http.HandlerFunc.ServeHTTP(0xc2080c9870, 0x7f9a8c70c848, 0xc20801d080, 0xc208110000)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·006(0x7f9a8c70c848, 0xc20801d020, 0xc208110000)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:739 +0x123
net/http.HandlerFunc.ServeHTTP(0xc2080a1100, 0x7f9a8c70c848, 0xc20801d020, 0xc208110000)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·007(0x7f9a8c70c810, 0xc2080423c0, 0xc208110000)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:749 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc2080a1120, 0x7f9a8c70c810, 0xc2080423c0, 0xc208110000)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208034028, 0x7f9a8c70c810, 0xc2080423c0, 0xc208110000)
	/root/go/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc20800e2a0, 0x7f9a8c70c810, 0xc2080423c0, 0xc208110000)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:167 +0x256
net/http.serverHandler.ServeHTTP(0xc20813c2a0, 0x7f9a8c70c810, 0xc2080423c0, 0xc208110000)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2088d01e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e```

**Comment by jhorwit2** [comment]
I can't start my app because of this :(.

**Comment by otoolep** [comment]
Are you writing data to the server? Can we see the data you are posting?

**Comment by jhorwit2** [comment]
I'm sending 5k points per request for most databases. some are way less. I have been sending the same type of data and just recently ran into issues. 

I'll get you some points, but a very interesting thing I see in my application logs is influx is sending back `Status: 404. Body: database not found: "dashboard"`.... randomly... the database exists and has existed for a while

**Comment by jhorwit2** [comment]
@otoolep you can see some examples [here](https://github.com/influxdb/influxdb/issues/3282#issuecomment-120168155)

**Comment by jhorwit2** [comment]
The very interesting thing is the the vast majority of my writes work fine, but some fail. I'll modify my application to log the ones that are failing.

**Comment by jwilder** [comment]
Reproduced with:
```
curl -XPOST -v http://localhost:8086/write --data-binary "         "
```

**Comment by jhorwit2** [comment]
```
dashboard,section=profileOptions,tier=basic value="view",userID=numbers,siteID="stuff" 1440186157466
dashboard,section=ruleEditor,tier=basic value="customMessageSaveAttributes",userID=numbers,siteID="stuff",position="center",goal="email",state="active" 1440186158905
dashboard,section=ruleEditor,tier=basic value="savedExistingCustomMessage",userID=numbers,siteID="stuff",messageCount=1,default=false,interests="[]",socialSources="[]",geoLocations="[]",campaignMediums="[]",returning="true",campaignNames="[]",devices="[]",referringDomains="[]" 1440186158912
dashboard,section=ruleManager,tier=basic value="view",userID=numbers,siteID="stuff" 1440186159007
dashboard,section=user value="login",userID=numbers 1440186163464
```

replace numbers with 9 or so digits (some writes work and every point wrote includes the userID so i'm going to assume that isn't it)

**Comment by jhorwit2** [comment]
This one also failed

```
subscription,tier=tier1,type=upgrade_to_pro user_email="address" 1440186365139
```

**Comment by jhorwit2** [comment]
Nothing seems weird on my end. I logged serialized objects of what was being sent and seem normal. no nulls or empty points.

```
[{"measurement":"dashboard","fields":{"value":"view","userID":numbers,"siteID":"stuff"},"tags":{"section":"ruleManager","tier":"basic"},"time":1440186911976}]
```
which turns into line protocol.

**Comment by Jhors2** [comment]
I noticed the above panic, however it was not fatal to the influx daemon.  It seems as though it happened when a retention policy and/or database didn't exist that I was attempting to write to.  Once I created the database and/or retention policy the panics disappeared from the logs.

**Comment by jhorwit2** [comment]
It randomly stopped for me. I'm guessing it was fixed in rc2. I'm going to close.
