### ISSUE TITLE
arithmetic on fields can crash influxd

### ISSUE THREAD

**Issue by Chestal** [influxdb/influxdb#3827]
influxdb version: influxdb_**0.9.3-rc2**_amd64.deb (same for the 2015-08-25 nightly)
running on Debian jessie.

The following sequence of commands crashed the daemon (fresh install):
```
$ /opt/influxdb/influx
Connected to http://localhost:8086 version 0.9.3-rc2
InfluxDB shell 0.9.3-rc2
> create database foo
> use foo
Using database foo
> insert bar a=1
> select a + b from bar
ERR: Get http://localhost:8086/query?db=foo&q=select+a+%2B+b+from+bar: EOF
```

The corresponding log entry starts with:
```
goroutine 40 [running]:
github.com/influxdb/influxdb/influxql.func·016(0xc208144b80, 0x2, 0x2, 0x910d20, 0xc20802bd20)
        /root/go/src/github.com/influxdb/influxdb/influxql/result.go:151 +0x4a
github.com/influxdb/influxdb/influxql.func·018(0xc208144b80, 0x2, 0x2, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/influxql/result.go:173 +0xa8
github.com/influxdb/influxdb/tsdb.processForMath(0xc208150050, 0x1, 0x1, 0xc208144be0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/executor.go:867 +0x4ad
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc208324180, 0xc20833e000, 0x1, 0x2710, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/executor.go:760 +0xf45
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc208324180)
        /root/go/src/github.com/influxdb/influxdb/tsdb/executor.go:661 +0xd6
github.com/influxdb/influxdb/tsdb.(*Executor).executeRaw(0xc2083163c0, 0xc2080958c0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/executor.go:228 +0x4e2
created by github.com/influxdb/influxdb/tsdb.(*Executor).Execute
        /root/go/src/github.com/influxdb/influxdb/tsdb/executor.go:88 +0x9a
```

In the above example the expression `a + b` refers to a non-existing field *b*. However, the same crash occurs when both fields exist. I am not sure whether this type of query is supported anyway, but obviously the daemon should not crash.

**Comment by otoolep** [comment]
Thanks for the report @Chestal -- this is a known issue. https://github.com/influxdb/influxdb/issues/3200
