### ISSUE TITLE
[0.9.3-rc3] restart influxdb causing panic

### ISSUE THREAD

**Issue by huhongbo** [influxdb/influxdb#3848]
influxdb 0.9.3rc3
centos 7.1
sometime influxdb stop write the point,and I restart the influxdb 
restart influxdb with high load causing panic
```
[run] 2015/08/26 12:57:48 Signal received, initializing clean shutdown...
[run] 2015/08/26 12:57:48 Waiting for clean shutdown...
[snapshot] 2015/08/26 12:57:48 snapshot listener closed
[tcp] 2015/08/26 12:57:48 cluster service accept error: network connection closed
[http] 2015/08/26 12:57:48 172.17.0.30 - root [26/Aug/2015:12:57:48 +0800] POST /write?db=metrics&p=%5BREDACTED%5D&precision=s&u=root HTTP/1.1 204 0 - Ruby ff6ba6dc-4bae-11e5-a2ea-000000000000 9.527186ms
[shard-precreation] 2015/08/26 12:57:48 Precreation service terminating
panic: assignment to entry in nil map

goroutine 662224 [running]:
github.com/influxdb/influxdb/tsdb.(*Store).CreateShard(0xc2080341a0, 0xc2441cfd8f, 0x7, 0xc20f810370, 0x7, 0x1, 0x0, 0x0)
        /home/philip/build2/src/github.com/influxdb/influxdb/tsdb/store.go:90 +0x727
github.com/influxdb/influxdb/cluster.func·002(0x1, 0x1, 0xc234d5c000, 0x6a, 0x80)
        /home/philip/build2/src/github.com/influxdb/influxdb/cluster/points_writer.go:245 +0x1c4
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
        /home/philip/build2/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x30b

goroutine 1 [select]:
main.(*Main).Run(0xc20806bb00, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /home/philip/build2/src/github.com/influxdb/influxdb/cmd/influxd/main.go:101 +0xe06
main.main()
        /home/philip/build2/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xdc
```

**Comment by jwilder** [comment]
This happens when a write is still running on the server when you stop the server.  There currently isn't a way to cancel the write when this happens but we should be able to avoid the panics.
