### ISSUE TITLE
[0.9.3] InfluxDB crashes on bringing up multi-node cluster

### ISSUE THREAD

**Issue by atulguptaag** [influxdb/influxdb#3965]
InfluxDB was built from source at version 0.9.3

I am bringing up a multi-node cluster. This is the first time the instances are being launched - so there is no prior data. The first instance crashed on the initial execution and it crashes at subsequent launches as well. The crash is always at the same code location.

Here is the relevant logs snippet:
```
[metastore] 2015/09/01 23:20:52 Using data dir: /var/opt/influxdb/meta
Using configuration at: /etc/opt/influxdb/config.toml
[metastore] 2015/09/01 23:20:52 Node at 10.2.26.1:8088 [Follower]
[metastore] 2015/09/01 23:20:53 Node at 10.2.26.1:8088 [Leader]. peers=[]
[metastore] 2015/09/01 23:20:53 Created local node: id=1, host=10.2.26.1:8088
[store] 2015/09/01 23:20:53 Using data dir: /var/opt/influxdb/data
[handoff] 2015/09/01 23:20:53 Starting hinted handoff service
[handoff] 2015/09/01 23:20:53 Using data dir: /var/opt/influxdb/hh
[tcp] 2015/09/01 23:20:53 Starting cluster service
[shard-precreation] 2015/09/01 23:20:53 Starting precreation service with check interval of 10m0s, advance period of 30m0s
[snapshot] 2015/09/01 23:20:53 Starting snapshot service
[admin] 2015/09/01 23:20:53 Starting admin service
[admin] 2015/09/01 23:20:53 Listening on HTTP: [::]:8083
[continuous_querier] 2015/09/01 23:20:53 Starting continuous query service
[httpd] 2015/09/01 23:20:53 Starting HTTP service
[httpd] 2015/09/01 23:20:53 Authentication enabled: false
[httpd] 2015/09/01 23:20:53 Listening on HTTP: [::]:8086
[retention] 2015/09/01 23:20:53 Starting rentention policy enforcement service
2015/09/01 23:20:53 InfluxDB starting, version 0.9, branch unknown, commit unknown
2015/09/01 23:20:53 Go version go1.4.1, GOMAXPROCS set to 40
[run] 2015/09/01 23:20:53 Listening for signals
[metastore] 2015/09/01 23:21:05 adding new raft peer: nodeId=2 addr=10.2.27.1:8088
[metastore] 2015/09/01 23:21:09 adding new raft peer: nodeId=3 addr=10.2.28.1:8088
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x5e7793]

goroutine 352 [running]:
github.com/influxdb/influxdb/cluster.(*ShardMapper).CreateMapper(0xc20808fc40, 0x1, 0xc2081dffe0, 0x3, 0x4, 0x7f954037da80, 0xc2098a80c0, 0x2710, 0x0, 0x0, ...)
        /work/influxdb/go/src/github.com/influxdb/influxdb/cluster/shard_mapper.go:58 +0x4d3
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).PlanShowMeasurements(0xc20808fc80, 0xc2098a80c0, 0xc2098a804e, 0x7, 0x2710, 0x0, 0x0, 0x0, 0x0)
        /work/influxdb/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:569 +0x2fe
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeShowMeasurementsStatement(0xc20808fc80, 0x0, 0xc2098a80c0, 0xc2098a804e, 0x7, 0xc2088e4060, 0x2710, 0x0, 0x0)
        /work/influxdb/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:586 +0x7f
github.com/influxdb/influxdb/tsdb.func·008()
        /work/influxdb/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:159 +0x8e6
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
        /work/influxdb/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:199 +0x1f5

goroutine 1 [chan receive, 9 minutes]:
main.(*Main).Run(0xc20808fb00, 0xc20800a010, 0x1, 0x1, 0x0, 0x0)
        /work/influxdb/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0x777
main.main()
        /work/influxdb/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xdc

goroutine 6 [syscall, 9 minutes]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc2080104c0, 0x72, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080104c0, 0x0, 0x0)
net.(*netFD).accept(0xc208010460, 0x0, 0x7f9544bb5e30, 0xc2083f0028)
        /usr/src/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080372c0, 0x901d80, 0x0, 0x0)
        /usr/src/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080372c0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc208100a50, 0x7f9544bc4498, 0xc2080372c0, 0x0, 0x0)
        /work/influxdb/go/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
        /work/influxdb/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:313 +0x8f2

....
```

**Comment by otoolep** [comment]
What commit did you build? Do you mean you built the 0.9.3 branch? A fix went into master recently that may address this issue.

**Comment by atulguptaag** [comment]
I had built the 0.9.3 branch. Which fix may have addressed this issue? Are these the changes titled  "convert meta shard owners to objects" committed on Aug 31?

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/commit/f72fd247b5f1bb1b9374981c7bfcf1db1e073f46

Build master, or download a nightly build, and see if you still see the issue.

https://influxdb.com/download/index.html

**Comment by atulguptaag** [comment]
Got it. Will update after I try that out.

**Comment by atulguptaag** [comment]
I don't see the crash with the code in master at commit 0cb9618d6d6a8d139b4145a329d07223ea16d614.

**Comment by beckettsean** [comment]
Thanks for the additional testing, @atulguptaag. I'm closing this issue now, please re-open if the issue recurs.
