### ISSUE TITLE
[0.9.3] select * from df_value -> out of memory

### ISSUE THREAD

**Issue by szop85** [influxdb/influxdb#3972]
We are having trouble querying some data because our InfluxDB instance is crashing after a select query. We are using collectd 5.5 to put df data metrics into our InfluxDB.

```
> select * from df_value
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc21d140000, 0x100000, 0x77ae00, 0xb3ffd8)
        /root/.gvm/gos/go1.4.2/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0xb456c0, 0x100000, 0x436d62)
        /root/.gvm/gos/go1.4.2/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0xb456c0, 0x1, 0x10000000003, 0x41624e)
        /root/.gvm/gos/go1.4.2/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0xb4c358, 0x7fdb1eafdb88)
        /root/.gvm/gos/go1.4.2/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x7fdb264d4000, 0x7fdb00000003, 0x7fdb1eafdb88)
        /root/.gvm/gos/go1.4.2/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
        /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:198 fp=0xc2080eecd0 sp=0xc2080eecc8
runtime.mallocgc(0x20, 0x0, 0x7fdb00000003, 0xc21d13ed08)
        /root/.gvm/gos/go1.4.2/src/runtime/malloc.go:178 +0x849 fp=0xc2080eed80 sp=0xc2080eecd0
runtime.rawstring(0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/runtime/string.go:195 +0x93 fp=0xc2080eedb0 sp=0xc2080eed80
runtime.slicebytetostring(0xc217c28272, 0x16, 0x25cfb8e, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/runtime/string.go:69 +0x4b fp=0xc2080eee40 sp=0xc2080eedb0
encoding/json.(*decodeState).literalStore(0xc2080761a8, 0xc217c28272, 0x16, 0x25cfb8e, 0x77ae20, 0xc21d13cad0, 0xd4, 0x0)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:770 +0x1cc7 fp=0xc2080ef1f8 sp=0xc2080eee40
encoding/json.(*decodeState).literal(0xc2080761a8, 0x77ae20, 0xc21d13cad0, 0xd4)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:638 +0xf7 fp=0xc2080ef260 sp=0xc2080ef1f8
encoding/json.(*decodeState).value(0xc2080761a8, 0x77ae20, 0xc21d13cad0, 0xd4)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:291 +0x3a8 fp=0xc2080ef338 sp=0xc2080ef260
encoding/json.(*decodeState).array(0xc2080761a8, 0x76d5c0, 0xc21c916810, 0xd7)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:439 +0xa9b fp=0xc2080ef4e0 sp=0xc2080ef338
encoding/json.(*decodeState).value(0xc2080761a8, 0x76d5c0, 0xc21c916810, 0xd7)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:285 +0x3ee fp=0xc2080ef5b8 sp=0xc2080ef4e0
encoding/json.(*decodeState).array(0xc2080761a8, 0x76b940, 0xc20800c190, 0xd7)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:439 +0xa9b fp=0xc2080ef760 sp=0xc2080ef5b8
encoding/json.(*decodeState).value(0xc2080761a8, 0x76b940, 0xc20800c190, 0xd7)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:285 +0x3ee fp=0xc2080ef838 sp=0xc2080ef760
encoding/json.(*decodeState).object(0xc2080761a8, 0x879c60, 0xc20800c160, 0xd9)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:605 +0x1199 fp=0xc2080efb78 sp=0xc2080ef838
encoding/json.(*decodeState).value(0xc2080761a8, 0x879c60, 0xc20800c160, 0xd9)
encoding/json.(*decodeState).object(0xc2080761a8, 0x879c60, 0xc20800c160, 0xd9)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:605 +0x1199 fp=0xc2080efb78 sp=0xc2080ef838
encoding/json.(*decodeState).value(0xc2080761a8, 0x879c60, 0xc20800c160, 0xd9)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:288 +0x3ce fp=0xc2080efc50 sp=0xc2080efb78
encoding/json.(*decodeState).array(0xc2080761a8, 0x76cf60, 0xc20803af60, 0xd7)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:439 +0xa9b fp=0xc2080efdf8 sp=0xc2080efc50
encoding/json.(*decodeState).value(0xc2080761a8, 0x76cf60, 0xc20803af60, 0xd7)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:285 +0x3ee fp=0xc2080efed0 sp=0xc2080efdf8
encoding/json.(*decodeState).object(0xc2080761a8, 0x838100, 0xc20803af60, 0xd9)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:605 +0x1199 fp=0xc2080f0210 sp=0xc2080efed0
encoding/json.(*decodeState).value(0xc2080761a8, 0x767980, 0xc20803af60, 0x16)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:288 +0x3ce fp=0xc2080f02e8 sp=0xc2080f0210
encoding/json.(*decodeState).unmarshal(0xc2080761a8, 0x767980, 0xc20803af60, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:149 +0x1e7 fp=0xc2080f0388 sp=0xc2080f02e8
encoding/json.(*Decoder).Decode(0xc208076180, 0x767980, 0xc20803af60, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/encoding/json/stream.go:53 +0x18f fp=0xc2080f0428 sp=0xc2080f0388
github.com/influxdb/influxdb/client.(*Result).UnmarshalJSON(0xc2080580a0, 0xc2121f800c, 0x25895ec, 0x3fffdf4, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/client/influxdb.go:347 +0x1c0 fp=0xc2080f0500 sp=0xc2080f0428
encoding/json.(*decodeState).object(0xc208076028, 0x848440, 0xc2080580a0, 0xd9)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:481 +0x133 fp=0xc2080f0840 sp=0xc2080f0500
encoding/json.(*decodeState).value(0xc208076028, 0x848440, 0xc2080580a0, 0xd9)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:288 +0x3ce fp=0xc2080f0918 sp=0xc2080f0840
encoding/json.(*decodeState).array(0xc208076028, 0x76ce40, 0xc20803b020, 0xd7)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:439 +0xa9b fp=0xc2080f0ac0 sp=0xc2080f0918
encoding/json.(*decodeState).value(0xc208076028, 0x76ce40, 0xc20803b020, 0xd7)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:285 +0x3ee fp=0xc2080f0b98 sp=0xc2080f0ac0
encoding/json.(*decodeState).object(0xc208076028, 0x838040, 0xc20803b020, 0xd9)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:605 +0x1199 fp=0xc2080f0ed8 sp=0xc2080f0b98
encoding/json.(*decodeState).value(0xc208076028, 0x767920, 0xc20803b020, 0x16)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:288 +0x3ce fp=0xc2080f0fb0 sp=0xc2080f0ed8
encoding/json.(*decodeState).unmarshal(0xc208076028, 0x767920, 0xc20803b020, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:149 +0x1e7 fp=0xc2080f1050 sp=0xc2080f0fb0
encoding/json.(*Decoder).Decode(0xc208076000, 0x767920, 0xc20803b020, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/encoding/json/stream.go:53 +0x18f fp=0xc2080f10f0 sp=0xc2080f1050
github.com/influxdb/influxdb/client.(*Response).UnmarshalJSON(0xc2080d0d20, 0xc20c108000, 0x25895fa, 0x3fffe00, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/client/influxdb.go:390 +0x1c0 fp=0xc2080f11c8 sp=0xc2080f10f0
encoding/json.(*decodeState).object(0xc2080764a8, 0x863d60, 0xc2080d0d20, 0x16)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:481 +0x133 fp=0xc2080f1508 sp=0xc2080f11c8
encoding/json.(*decodeState).value(0xc2080764a8, 0x863d60, 0xc2080d0d20, 0x16)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:288 +0x3ce fp=0xc2080f15e0 sp=0xc2080f1508
encoding/json.(*decodeState).unmarshal(0xc2080764a8, 0x863d60, 0xc2080d0d20, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/encoding/json/decode.go:149 +0x1e7 fp=0xc2080f1680 sp=0xc2080f15e0
encoding/json.(*Decoder).Decode(0xc208076480, 0x863d60, 0xc2080d0d20, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/encoding/json/stream.go:53 +0x18f fp=0xc2080f1720 sp=0xc2080f1680
github.com/influxdb/influxdb/client.(*Client).Query(0xc208058000, 0xc2081005c0, 0x16, 0xc208068584, 0x8, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/client/influxdb.go:156 +0x629 fp=0xc2080f18c0 sp=0xc2080f1720
main.(*CommandLine).ExecuteQuery(0xc208033ee0, 0xc2081005c0, 0x16, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/cmd/influx/main.go:462 +0xaf fp=0xc2080f19b8 sp=0xc2080f18c0
main.(*CommandLine).ParseCommand(0xc208033ee0, 0xc2081005c0, 0x16, 0xc2081005c0)
        /root/go/src/github.com/influxdb/influxdb/cmd/influx/main.go:263 +0xa2c fp=0xc2080f1b98 sp=0xc2080f19b8
main.main()
        /root/go/src/github.com/influxdb/influxdb/cmd/influx/main.go:212 +0x15bc fp=0xc2080f1f98 sp=0xc2080f1b98
runtime.main()
        /root/.gvm/gos/go1.4.2/src/runtime/proc.go:63 +0xf3 fp=0xc2080f1fe0 sp=0xc2080f1f98
runtime.goexit()
        /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080f1fe8 sp=0xc2080f1fe0

goroutine 5 [syscall]:
os/signal.loop()
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 21 [select]:
net/http.(*persistConn).writeLoop(0xc208062420)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:661 +0xcbc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 20 [select]:
net/http.(*persistConn).readLoop(0xc208062420)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:660 +0xc9f
```

Cheers,
David

**Comment by otoolep** [comment]
How many points do you expect to come back? Do you know how many you have
written?

Philip

**Comment by szop85** [comment]
Round about 20000 points.

Cheers,
David

**Comment by otoolep** [comment]
Thanks @szop85 -- how many fields per points? 20K points is not many. We need much more detail about your system, such architecture, CPU cores, distro, and RAM.

**Comment by szop85** [comment]
Hello otoolep,

we can close this thread since we havn't experienced new crashes after a fresh reinstall. Sorry for bothering and thank you for your fast response!

Cheers
