### ISSUE TITLE
[0.9.4.1] RPM install failed, cannot start port

### ISSUE THREAD

**Issue by wyzssw** [influxdb/influxdb#4122]
```
wget https://s3.amazonaws.com/influxdb/influxdb-0.9.4.1-1.x86_64.rpm
sudo yum localinstall influxdb-0.9.4.1-1.x86_64.rpm
```

```
015/09/16 04:02:24 Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/09/16 04:02:24 Using data dir: /dev/me/opt/influxdb/meta
panic: close of nil channel

goroutine 1 [running]:
github.com/influxdb/influxdb/meta.(*localRaft).close(0xc82000b5e0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/meta/state.go:201 +0x35
github.com/influxdb/influxdb/meta.(*Store).close(0xc8200828c0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:462 +0x8f
github.com/influxdb/influxdb/meta.(*Store).Open(0xc8200828c0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:233 +0x2f8
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc820133200, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:348 +0xafe
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc820133200, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:307 +0x2d
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc820086300, 0xc82000a060, 0x4, 0x4, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:114 +0xd7e
main.(*Main).Run(0xc820103f00, 0xc82000a060, 0x4, 0x4, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x67e
main.main()
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [runnable]:
syscall.Syscall6(0x120, 0x4, 0xc82002cb70, 0xc82002cb6c, 0x80800, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0xb)
        /home/philip/.gvm/gos/go1.5/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.accept4(0x4, 0xc82002cb70, 0xc82002cb6c, 0x80800, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/syscall/zsyscall_linux_amd64.go:1593 +0x72
syscall.Accept4(0x4, 0x80800, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/syscall/syscall_linux.go:453 +0x91
net.accept(0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/sock_cloexec.go:54 +0x67
net.(*netFD).accept(0xc82005b490, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:400 +0x16b
net.(*TCPListener).AcceptTCP(0xc82002e138, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82002e138, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc820144a40, 0x7fd748d1db38, 0xc82002e138, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x4b
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:345 +0xae9
```

**Comment by beckettsean** [comment]
@wyzssw first install on this system? does this happen on other systems? `/dev/me/opt/influxdb/meta` us a non-standard location for the directory, is the volume available?

**Comment by wyzssw** [comment]
perhaps not first install，it's maybe my fault。
I find i  can just copy 'influx and influxd ' command to anywhere i want ，without  install in root。
