### ISSUE TITLE
[0.9.4] Influxdb server will crash while select from non-existenting measurements

### ISSUE THREAD

**Issue by maxone** [influxdb/influxdb#4143]
version: 0.9.X

select * from measurement1,measurement2,measurement3

The influxdb server will crash if any of measurement2 measurement3 does not exist.

**Comment by rkuchan** [comment]
Thank you for pointing this out, @maxone. I am able to repro.

```
panic: runtime error: index out of range

goroutine 3103 [running]:
github.com/influxdb/influxdb/tsdb.(*tagSetCursor).decodeRawPoint(0xc821585f90, 0xc8217405d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20150904-26264-q4cxjr/influxdb-0.9.3/src/github.com/influxdb/influxdb/tsdb/mapper.go:745 +0x4a8
github.com/influxdb/influxdb/tsdb.(*tagSetCursor).Next(0xc821585f90, 0x0, 0x1404d4aa6d2f06e5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8215f7a20, ...)
	/private/tmp/influxdb20150904-26264-q4cxjr/influxdb-0.9.3/src/github.com/influxdb/influxdb/tsdb/mapper.go:720 +0x2c7
github.com/influxdb/influxdb/tsdb.(*LocalMapper).nextChunkRaw(0xc820588900, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20150904-26264-q4cxjr/influxdb-0.9.3/src/github.com/influxdb/influxdb/tsdb/mapper.go:276 +0x123
github.com/influxdb/influxdb/tsdb.(*LocalMapper).NextChunk(0xc820588900, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20150904-26264-q4cxjr/influxdb-0.9.3/src/github.com/influxdb/influxdb/tsdb/mapper.go:259 +0x46
github.com/influxdb/influxdb/tsdb.(*StatefulMapper).NextChunk(0xc8215f7760, 0xbdec38, 0x0, 0x0)
	/private/tmp/influxdb20150904-26264-q4cxjr/influxdb-0.9.3/src/github.com/influxdb/influxdb/tsdb/executor.go:43 +0x4d
github.com/influxdb/influxdb/tsdb.(*Executor).executeRaw(0xc821740420, 0xc821314240)
	/private/tmp/influxdb20150904-26264-q4cxjr/influxdb-0.9.3/src/github.com/influxdb/influxdb/tsdb/executor.go:190 +0x137d
created by github.com/influxdb/influxdb/tsdb.(*Executor).Execute
	/private/tmp/influxdb20150904-26264-q4cxjr/influxdb-0.9.3/src/github.com/influxdb/influxdb/tsdb/executor.go:88 +0xa1
```

**Comment by otoolep** [comment]
I'll take this one.

**Comment by otoolep** [comment]
I cannot reproduce this.

```
InfluxDB shell 0.9
> create database test
> select * from measurement1
ERR: database name required
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> use test
Using database test
> select * from measurement1
> insert cpu value=1
> select * from cpu
name: cpu
---------
time                            value
2015-09-23T04:42:41.255327808Z  1

> select * from cpu,cpu2,cpu3
> show diagnostics
name: build
-----------
Branch  Commit  Version
unknown unknown 0.9


name: runtime
-------------
GOARCH  GOMAXPROCS      GOOS    version
amd64   8               linux   go1.5


name: network
-------------
hostname
marx
                                                                                                                                           
                                                                                                                                           
name: system                                                                                                                               
------------                                                                                                                               
PID     currentTime                     started                         uptime                                                             
2910    2015-09-23T04:43:12.5958965Z    2015-09-23T04:42:09.167699544Z  1m3.428197202s                                                     
                                                                                                                                           
>     
```

**Comment by rkuchan** [comment]
@mjdesa

**Comment by mjdesa** [comment]
@maxone cant repro on master.
