### ISSUE TITLE
[0.9.4.1] Panic when writing empty data points via Ruby 

### ISSUE THREAD

**Issue by sosedoff** [influxdb/influxdb#4248]
I've been experimenting with InfluxDb 0.9.4.1 and found a weird bug which i cant replicate via CURL.
What im doing is just writing an empty string to the write enpoint with ruby:

```ruby
require "faraday"
Faraday.post("http://127.0.0.1:8086/write?db=mydb", "\n")
```

Example above results in influxdb's panic:

```
2015/09/27 19:11:08 http: panic serving 192.168.99.1:55438: runtime error: index out of range
goroutine 1755 [running]:
net/http.(*conn).serve.func1(0xc8213484d0, 0x7f4e221fef18, 0xc820e17f58)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1287 +0xb5
github.com/influxdb/influxdb/services/httpd.(*Handler).serveWriteLine(0xc82007d080, 0x7f4e221ff570, 0xc8209b6480, 0xc821236000, 0xc820f9ec00, 0x1, 0x200, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:458 +0x1384
github.com/influxdb/influxdb/services/httpd.(*Handler).serveWrite(0xc82007d080, 0x7f4e221ff570, 0xc8209b6480, 0xc821236000, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:376 +0x79c
github.com/influxdb/influxdb/services/httpd.(*Handler).(github.com/influxdb/influxdb/services/httpd.serveWrite)-fm(0x7f4e221ff570, 0xc8209b6480, 0xc821236000, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:106 +0x48
github.com/influxdb/influxdb/services/httpd.authenticate.func1(0x7f4e221ff570, 0xc8209b6480, 0xc821236000)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:673 +0x70
net/http.HandlerFunc.ServeHTTP(0xc82012c4a0, 0x7f4e221ff570, 0xc8209b6480, 0xc821236000)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.gzipFilter.func1(0x7f4e221ff448, 0xc8209b6440, 0xc821236000)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:734 +0x2af
net/http.HandlerFunc.ServeHTTP(0xc82012c4c0, 0x7f4e221ff448, 0xc8209b6440, 0xc821236000)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.versionHeader.func1(0x7f4e221ff448, 0xc8209b6440, 0xc821236000)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:743 +0xc0
net/http.HandlerFunc.ServeHTTP(0xc82012c4e0, 0x7f4e221ff448, 0xc8209b6440, 0xc821236000)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.cors.func1(0x7f4e221ff448, 0xc8209b6440, 0xc821236000)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:776 +0x328
net/http.HandlerFunc.ServeHTTP(0xc82012c500, 0x7f4e221ff448, 0xc8209b6440, 0xc821236000)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.requestID.func1(0x7f4e221ff448, 0xc8209b6440, 0xc821236000)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:786 +0x15d
net/http.HandlerFunc.ServeHTTP(0xc82012c520, 0x7f4e221ff448, 0xc8209b6440, 0xc821236000)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.logging.func1(0x7f4e221ff448, 0xc8209b6420, 0xc821236000)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:794 +0x10b
net/http.HandlerFunc.ServeHTTP(0xc82012c540, 0x7f4e221ff448, 0xc8209b6420, 0xc821236000)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.recovery.func1(0x7f4e221ff3e8, 0xc821348790, 0xc821236000)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:804 +0x114
net/http.HandlerFunc.ServeHTTP(0xc82012c560, 0x7f4e221ff3e8, 0xc821348790, 0xc821236000)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc820022108, 0x7f4e221ff3e8, 0xc821348790, 0xc821236000)
	/tmp/build/src/github.com/bmizerany/pat/mux.go:109 +0x244
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc82007d080, 0x7f4e221ff3e8, 0xc821348790, 0xc821236000)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:172 +0x357
net/http.serverHandler.ServeHTTP(0xc8201784e0, 0x7f4e221ff3e8, 0xc821348790, 0xc821236000)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8213484d0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1910 +0x3f6
```
Panic also triggers `Farday::ConnectionError` in ruby code, which was unexpected behavior because server did not handle the connection properly. 

The reason why its happening is simple: when making a HTTP call with Faraday, it will set content-type header to `application/x-www-form-urlencoded` and set empty body (new line `\n`). This behavior is correct although data is not. 

Just wanted to bring this up.

**Comment by otoolep** [comment]
Someone with Ruby experience could repro the issue above, using the Faraday library, and perform the write above. Be sure to create the database `db` first. 

If the error occurs, then fix the panic.

**Comment by vwong** [comment]
Reproduced with curl as follows:

```sh
echo '' | curl -v "http://127.0.0.1:8086/write?db=mydb" --data-binary @-
```

**Comment by otoolep** [comment]
Thanks @vwong

**Comment by jademcgough** [comment]
I'm able to repro this with 0.9.4.2-1, happy to take a look into the panic.

**Comment by otoolep** [comment]
Go for it @jademcgough

**Comment by jademcgough** [comment]
I just built from master and can't repro the issue there:

```
[http] 2015/11/07 10:30:41 127.0.0.1 - - [07/Nov/2015:10:30:41 -0800] POST /write?db=mydb HTTP/1.1 204 0 - Faraday v0.9.2 a6541cf4-857d-11e5-8006-000000000000 68.875µs
```

```
irb(main):003:0> Faraday.post("http://localhost:8086/write?db=mydb", "\n")
=> #<Faraday::Response:0x007f8b8104e4d0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="" @url=#<URI::HTTP http://localhost:8086/write?db=mydb> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Faraday v0.9.2", "Content-Type"=>"application/x-www-form-urlencoded"} @ssl=#<Faraday::SSLOptions (empty)> @response=#<Faraday::Response:0x007f8b8104e4d0 ...> @response_headers={"content-encoding"=>"gzip", "request-id"=>"a6541cf4-857d-11e5-8006-000000000000", "x-influxdb-version"=>"0.9", "date"=>"Sat, 07 Nov 2015 18:30:41 GMT", "connection"=>"close"} @status=204>>
```

**Comment by otoolep** [comment]
Yeah, neither can I using the curl command shown above. 

Thanks for your help!

**Comment by otoolep** [comment]
```
$ echo '' | curl -v "http://127.0.0.1:8086/write?db=mydb" --data-binary @-
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8086 (#0)
> POST /write?db=mydb HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:8086
> Accept: */*
> Content-Length: 1
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 1 out of 1 bytes
< HTTP/1.1 204 No Content
< Request-Id: 99a9ad81-8581-11e5-8006-000000000000
< X-Influxdb-Version: 0.9
< Date: Sat, 07 Nov 2015 18:58:57 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by otoolep** [comment]
Fixed in master so closed.
