### ISSUE TITLE
[pd-storage-engine] inaccurate values when using mean and group by

### ISSUE THREAD

**Issue by parisholley** [influxdb/influxdb#4321]
when I do a mean() on all values in a measurement, seems fine. soon as I group by time(1m), i get some whacky numbers, but it seems to only happen on some of my data, not all.

i then tried to run a max() on the same query with no interval and it crashed the server with the same error i have seen before:

```
goroutine 2790 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.DecodeBlock(0x7f4bb22f9754, 0x4, 0xc13b8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/encoding.go:127 +0x37f
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*cursor).decodeBlock(0xc82669ad20, 0xe0040e748)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cursor.go:437 +0x152
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*cursor).seekAscending(0xc82669ad20, 0x140a0ff40ed3b614, 0x140a101e0040e463, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cursor.go:288 +0x485
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*cursor).SeekTo(0xc82669ad20, 0x140a0ff40ed3b614, 0xffffffffffffffff, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cursor.go:248 +0x390
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*combinedEngineCursor).SeekTo(0xc8349a3020, 0x140a0ff40ed3b614, 0x648, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cursor.go:29 +0xc0
github.com/influxdb/influxdb/tsdb.(*TagsCursor).SeekTo(0xc830228cd0, 0x140a0ff40ed3b614, 0x9cfcc0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/cursor.go:365 +0x85
github.com/influxdb/influxdb/tsdb.(*TagSetCursor).Init(0xc858a72d80, 0x140a0ff40ed3b614)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/cursor.go:193 +0xbd
github.com/influxdb/influxdb/tsdb.(*AggregateMapper).openMeasurement(0xc842aa2ff0, 0xc820316bd0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/mapper.go:479 +0x59d
github.com/influxdb/influxdb/tsdb.(*AggregateMapper).Open(0xc842aa2ff0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/mapper.go:433 +0x6de
github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeAggregate(0xc82a188db0, 0xc826354240)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/executor.go:372 +0x35c
created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/executor.go:64 +0xf2
```

**Comment by parisholley** [comment]
that fix while preventing crashes in some instances, doesn't solve the inaccuracies. this time, if i run max() on the measurement i get the value I expect, but when grouping by time(1m) the results are all over the place. i think the in memory cache is the issue:

```
panic: runtime error: slice bounds out of range

goroutine 109 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*cursor).decodeBlock(0xc8234cfc00, 0xe0041b36a)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cursor.go:436 +0x1e7
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*cursor).seekAscending(0xc8234cfc00, 0x140a110d73c1e800, 0x4023f3, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cursor.go:288 +0x485
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*cursor).SeekTo(0xc8234cfc00, 0x140a110d73c1e800, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cursor.go:248 +0x390
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*multiFieldCursor).SeekTo(0xc8234cfce0, 0x140a110d73c1e800, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/cursor.go:107 +0xcf
github.com/influxdb/influxdb/tsdb.(*TagsCursor).SeekTo(0xc8234c9cc0, 0x140a110d73c1e800, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/cursor.go:365 +0x85
github.com/influxdb/influxdb/tsdb.(*TagSetCursor).Init(0xc821bf79e0, 0x140a110d73c1e800)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/cursor.go:193 +0xbd
github.com/influxdb/influxdb/tsdb.(*AggregateMapper).openMeasurement(0xc820151590, 0xc8202504d0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/mapper.go:479 +0x59d
github.com/influxdb/influxdb/tsdb.(*AggregateMapper).Open(0xc820151590, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/mapper.go:433 +0x6de
github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeAggregate(0xc8228f2f30, 0xc8250983c0)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/executor.go:372 +0x35c
created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/executor.go:64 +0xf2
```

**Comment by pauldix** [comment]
We'll need more detail to troubleshoot this. Can you give repro steps using the CLI for what writes to do and what query shows the problem?

**Comment by parisholley** [comment]
@pauldix i am only able to reproduce this by ingesting data, not through cli. here is the problem:

![screen shot 2015-10-04 at 1 56 48 pm](https://cloud.githubusercontent.com/assets/399289/10270217/cb0c5b2c-6a9f-11e5-95b7-11a683f2ace2.png)

some how, data isn't writing to the correct fields and i suspect the numbers being added are based on sting length or some other calculated value. if i try to write to a field with a float, then follow up with a string, it is rejected "field type conflict: input field"

**Comment by parisholley** [comment]
@pauldix i think this is as close as I have gotten to reproduce

```
curl -G 'http://localhost:8086/query' --data-urlencode 'q=drop database test;'
curl -G 'http://localhost:8086/query' --data-urlencode 'q=create database test;'
curl -G 'http://localhost:8086/query' --data-urlencode 'q=CREATE RETENTION POLICY "default" ON test DURATION 1h REPLICATION 1 DEFAULT;'

curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'test,tag=a value=2.5 1443916800000000000'
curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'test value=3.5 1443916810000000000'
curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'test,tag=b value=6.5 1443916860000000000'
curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'test value=8.5 1443916861000000000'
```
select mean(value) from test where time > '2015-10-04T00:00:00Z' and  time < '2015-10-04T00:03:00Z' group by time(1m);
```
time	sum
2015-10-04T00:00:00Z	6
2015-10-04T00:01:00Z	23.5
2015-10-04T00:02:00Z
```

**Comment by parisholley** [comment]
@pauldix i tried running the queries above again, and it didn't reproduce. I think there is definitely a problem around internal state somewhere. while I produced that problem above, I had my prod data also streaming in (to a different database). i'll be more than happy to give you SSH access to the box i am using for you to test. all it takes is to wipe the data, and let the events come in, and the corrupt data eventually happens.

i suspect the underlying problem, is whatever causes this error to happen

```
panic: runtime error: index out of range

goroutine 974 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.DecodeBlock(0x7f0a424eaa70, 0x4, 0xc182c, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/encoding.go:127 +0x37f 
```

the code running is your last commit friday + my model point fix.

**Comment by parisholley** [comment]
@pauldix the above case i provided above on the cli does work, you just have to wait for an idle index flush on that db/shard. until that happens, it will return the correct data but after it writes, you will see the results i posted.

**Comment by parisholley** [comment]
@pauldix another helpful tip, when i turn on SkipCache in the engine code, it appears the problem disappears.

**Comment by otoolep** [comment]
For the record, I cannot repro this issue on master.
```
> use test
Using database test
> select sum(value) from test where time > '2015-10-04T00:00:00Z' and time < '2015-10-04T00:03:00Z' group by time(1m)
name: test
----------
time                    sum
2015-10-04T00:00:00Z    3.5
2015-10-04T00:01:00Z    15
2015-10-04T00:02:00Z

> select * from test
name: test
----------
time                    tag     value
2015-10-04T00:00:00Z    a       2.5
2015-10-04T00:00:10Z            3.5
2015-10-04T00:01:00Z    b       6.5
2015-10-04T00:01:01Z            8.5

> select * from test where time > '2015-10-04T00:00:00Z' and time < '2015-10-04T00:03:00Z'
name: test
----------
time                    tag     value
2015-10-04T00:00:10Z            3.5
2015-10-04T00:01:00Z    b       6.5
2015-10-04T00:01:01Z            8.5                                                                                                                                                                                
                                                                                                                                                                                                                   
>    
```

**Comment by parisholley** [comment]
@otoolep have you tried on the last branch of the new storage engine?

**Comment by pauldix** [comment]
I've got a test reproducing the problem. Will have a fix soon

**Comment by parisholley** [comment]
@pauldix you da man!

**Comment by pauldix** [comment]
just pushed a fix, let me know if everything looks good.

**Comment by parisholley** [comment]
@pauldix looks good so far! Only thing to dig into now is why some of my charts aren't showing data similar to before. Will investigate further and open additional issues when I find some information.

As a general FYI, here is what I am seeing for flush times at the moment (using default conf settings):

```
[tsm1] 2015/10/06 19:50:17 writing new index file /influxdb/data/mantis/default/2/0000024.tsm1
[tsm1wal] 2015/10/06 19:50:18 /influxdb/data/mantis/default/2 flush to index took 13.490626338s
```
