### ISSUE TITLE
panic starting the server

### ISSUE THREAD

**Issue by gilgamezh** [influxdb/influxdb#4424]
Hi! any idea what could be happening here?

Maybe related to #3994 ?

```
root@influxdb-dev:~# cat /etc/issue
Debian GNU/Linux 7 \n \l

root@influxdb-dev:~# /etc/init.d/influxdb restart
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
root@influxdb-dev:~# tail -f /var/log/influxdb/influxd.log
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc8202a20e0, 0xc8201a3440)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627
2015/10/13 11:19:21 InfluxDB starting, version 0.9.4.1, branch 0.9.4, commit c4f85f84765e27bfb5e58630d0dea38adeacf543
2015/10/13 11:19:21 Go version go1.5, GOMAXPROCS set to 4
2015/10/13 11:19:21 Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/10/13 11:19:21 Using data dir: /var/opt/influxdb/meta
[metastore] 2015/10/13 11:19:21 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2015/10/13 11:19:21 Node at localhost:8088 [Follower]
[metastore] 2015/10/13 11:19:23 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2015/10/13 11:19:23 Updated node id=1 hostname=localhost:8088
[monitor] 2015/10/13 11:19:23 Starting monitor system
[monitor] 2015/10/13 11:19:23 'build' registered for diagnostics monitoring
[monitor] 2015/10/13 11:19:23 'runtime' registered for diagnostics monitoring
[monitor] 2015/10/13 11:19:23 'network' registered for diagnostics monitoring
[monitor] 2015/10/13 11:19:23 'system' registered for diagnostics monitoring
[store] 2015/10/13 11:19:23 Using data dir: /var/opt/influxdb/data
[monitor] 2015/10/13 11:19:23 Storing statistics in database '_internal' retention policy '', at interval 10s
[wal] 2015/10/13 11:19:24 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/10/13 11:19:24 WAL writing to /var/opt/influxdb/wal/_internal/monitor/1
[wal] 2015/10/13 11:19:24 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/10/13 11:19:24 WAL writing to /var/opt/influxdb/wal/_internal/monitor/3
[wal] 2015/10/13 11:19:25 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/10/13 11:19:25 WAL writing to /var/opt/influxdb/wal/_internal/monitor/4
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x9050c0]

goroutine 1 [running]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).Close(0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:784 +0x120
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).close(0xc82030c000, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:569 +0x62
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Close(0xc82030c000, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:560 +0x105
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).Close(0xc82010b000, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:160 +0x9e
github.com/influxdb/influxdb/tsdb.(*Shard).close(0xc8202ecb40, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/shard.go:145 +0x4a
github.com/influxdb/influxdb/tsdb.(*Shard).Open(0xc8202ecb40, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/shard.go:129 +0x55
github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0xc82012e380, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/store.go:291 +0xd2c
github.com/influxdb/influxdb/tsdb.(*Store).Open(0xc82012e380, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/store.go:324 +0x35a
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc8201258c0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:361 +0xdea
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc8201258c0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:307 +0x2d
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc820118200, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:114 +0xd7e
main.(*Main).Run(0xc820105f00, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x67e
main.main()
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82000c460, 0xc820017800)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 19 [IO wait]:
net.runtime_pollWait(0x7f7436bfa238, 0x72, 0xc82000e190)
        /home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201285a0, 0x72, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201285a0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820128540, 0x0, 0x7f7436c38090, 0xc820108020)
        /home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8201140d8, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8201140d8, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc82010d440, 0x7f7436bfa3c0, 0xc8201140d8, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x4b
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:345 +0xae9

goroutine 20 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8201140e0, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc820175d40, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:2059 +0x51
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc8201285b0)
        /tmp/build/src/github.com/hashicorp/raft/net_transport.go:346 +0x79
created by github.com/hashicorp/raft.NewNetworkTransport
        /tmp/build/src/github.com/hashicorp/raft/net_transport.go:138 +0x284

goroutine 21 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc820196000)
        /tmp/build/src/github.com/hashicorp/raft/raft.go:849 +0xcce
github.com/hashicorp/raft.(*Raft).runLeader(0xc820196000)
        /tmp/build/src/github.com/hashicorp/raft/raft.go:821 +0x936
github.com/hashicorp/raft.(*Raft).run(0xc820196000)
        /tmp/build/src/github.com/hashicorp/raft/raft.go:602 +0xbb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
        /tmp/build/src/github.com/hashicorp/raft/raft.go:252 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc820196000, 0xc8201849e0)
        /tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 22 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc820196000)
        /tmp/build/src/github.com/hashicorp/raft/raft.go:509 +0x10eb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
        /tmp/build/src/github.com/hashicorp/raft/raft.go:253 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc820196000, 0xc8201849f0)
        /tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 23 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc820196000)
        /tmp/build/src/github.com/hashicorp/raft/raft.go:1636 +0x493
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
        /tmp/build/src/github.com/hashicorp/raft/raft.go:254 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc820196000, 0xc820184a00)
        /tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 24 [select]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc82010f040)
        /tmp/build/src/github.com/influxdb/influxdb/meta/state.go:187 +0x4f5
created by github.com/influxdb/influxdb/meta.(*localRaft).open
        /tmp/build/src/github.com/influxdb/influxdb/meta/state.go:177 +0x1344

goroutine 25 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8201140e8, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc82012c280)
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:622 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:239 +0x364

goroutine 26 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8201140f0, 0x0, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc82012c280)
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:726 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /tmp/build/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3b6

goroutine 34 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc8201258c0, 0xc82011e6c0)
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:491 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:351 +0xc67

goroutine 35 [select]:
github.com/influxdb/influxdb/monitor.(*Monitor).storeStatistics(0xc82011c750)
        /tmp/build/src/github.com/influxdb/influxdb/monitor/service.go:333 +0x187c
created by github.com/influxdb/influxdb/monitor.(*Monitor).Open
        /tmp/build/src/github.com/influxdb/influxdb/monitor/service.go:134 +0x30c

goroutine 36 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820230000, 0xc8201c7620)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 50 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc8202300e0, 0xc8202a66c0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

```

**Comment by otoolep** [comment]
I believe this was fixed in a later build. Can you try upgrade to 0.9.4.2?

**Comment by gilgamezh** [comment]
@otoolep ok! I'll test with 0.9.4.2 and let you know

**Comment by gilgamezh** [comment]
@otoolep it's working know. thanks! 
What was the issue? can you link me to the original one?

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/commit/5e991f1703b532cfd0283c31fd29ceb5b718417d

**Comment by gilgamezh** [comment]
thanks!
