### ISSUE TITLE
[0.9.5-nightly]: CLI panics before auth

### ISSUE THREAD

**Issue by iwinux** [influxdb/influxdb#4641]
Hi,

I've set up a new instance of InfluxDB 0.9.5-nightly-6682752, and encountered a crash when starting CLI `influx`.

Here's my config file:

```toml
reporting-disabled = true

[registration]
enabled = false

[http]
auth-enabled = true
```

I set `auth-enabled = true` **before** creating any user. I then restarted the server and launch `influx`, which crashed with this panic:

```
$ influx
panic: runtime error: index out of range

goroutine 1 [running]:
main.(*CommandLine).DatabaseToken(0xc820152000, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.wkkqd1PJBq/src/github.com/influxdb/influxdb/cmd/influx/main.go:552 +0x424
main.main()
        /tmp/tmp.wkkqd1PJBq/src/github.com/influxdb/influxdb/cmd/influx/main.go:172 +0xd77

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /root/.gvm/gos/go1.5.1/src/runtime/asm_amd64.s:1696 +0x1

goroutine 18 [syscall]:
os/signal.loop()
        /root/.gvm/gos/go1.5.1/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /root/.gvm/gos/go1.5.1/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [select, locked to thread]:
runtime.gopark(0xa89860, 0xc82003c728, 0x99f300, 0x6, 0x18, 0x2)
        /root/.gvm/gos/go1.5.1/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82003c728, 0x0, 0x18)
        /root/.gvm/gos/go1.5.1/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82003c728)
        /root/.gvm/gos/go1.5.1/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /root/.gvm/gos/go1.5.1/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /root/.gvm/gos/go1.5.1/src/runtime/asm_amd64.s:1696 +0x1

goroutine 24 [runnable]:
net/http.(*persistConn).writeLoop(0xc820166000)
        /root/.gvm/gos/go1.5.1/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /root/.gvm/gos/go1.5.1/src/net/http/transport.go:686 +0xc9d
```

And this is the server http log:

```
[http] 2015/11/03 16:09:12 192.168.2.2 - - [03/Nov/2015:16:09:12 +0800] GET /ping HTTP/1.1 204 0 - InfluxDBShell/0.9.5-nightly-6682752 2ae0ef79-8202-11e5-8001-000000000000 100.36µs

[http] 2015/11/03 16:09:12 192.168.2.2 - - [03/Nov/2015:16:09:12 +0800] GET /query?db=&epoch=ns&q=SHOW+DIAGNOSTICS+for+%27registration%27 HTTP/1.1 401 74 - InfluxDBShell/0.9.5-nightly-6682752 2ae10690-8202-11e5-8002-000000000000 1.432099ms
```

I guess this is caused by PR #4514, which attempts to execute query `SHOW DIAGNOSTICS for 'registration'` but fails without authentication.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/4644

Thanks for the report @iwinux
