### ISSUE TITLE
Restore functionality panics with Store.RPCListener not set (0.9.5-nightly)

### ISSUE THREAD

**Issue by simcap** [influxdb/influxdb#4642]
My configuration is: 

* 1 fresh install of a single InfluxDB instance version 0.9.5-nightly-6682752
* and therefore no clustering

After having a backup snapshot done successfully i run this command (with no InfluxDb process running):

`sudo /opt/influxdb/influxd restore -config /etc/opt/influxdb/influxdb.conf /tmp/latest-snapshot` 

I get the following stacktrace:

```
unpacking: _internal/monitor/10 (33890304 bytes)
unpacking: _internal/monitor/13 (42020864 bytes)
unpacking: _internal/monitor/17 (53149696 bytes)
unpacking: _internal/monitor/21 (62894080 bytes)
unpacking: _internal/monitor/25 (72585216 bytes)
unpacking: _internal/monitor/29 (32546816 bytes)
unpacking: _internal/monitor/4 (18874368 bytes)
unpacking: _internal/monitor/7 (26234880 bytes)
unpacking: meta (1499 bytes)
panic: Store.RPCListener not set

goroutine 1 [running]:
github.com/influxdb/influxdb/meta.(*Store).Open(0xc820080780, 0x0, 0x0)
	/tmp/tmp.NJgSjiDtZR/src/github.com/influxdb/influxdb/meta/store.go:191 +0x1a5
github.com/influxdb/influxdb/cmd/influxd/restore.(*Command).unpackMeta(0xc8200154a0, 0xc82000aeb0, 0xc820110a30, 0x4, 0x5db, 0xecdca77a8, 0x15d90e44, 0x10a01e0, 0xc8200f6000, 0x0, ...)
	/tmp/tmp.NJgSjiDtZR/src/github.com/influxdb/influxdb/cmd/influxd/restore/restore.go:177 +0x9c8
github.com/influxdb/influxdb/cmd/influxd/restore.(*Command).unpack(0xc8200154a0, 0xc82000aeb0, 0xc8200f6000, 0x0, 0x0)
	/tmp/tmp.NJgSjiDtZR/src/github.com/influxdb/influxdb/cmd/influxd/restore/restore.go:125 +0x547
github.com/influxdb/influxdb/cmd/influxd/restore.(*Command).Restore(0xc8200154a0, 0xc8200f6000, 0x7fff6a813941, 0x14, 0x0, 0x0)
	/tmp/tmp.NJgSjiDtZR/src/github.com/influxdb/influxdb/cmd/influxd/restore/restore.go:59 +0x4da
github.com/influxdb/influxdb/cmd/influxd/restore.(*Command).Run(0xc8200154a0, 0xc82000a0c0, 0x3, 0x3, 0x0, 0x0)
	/tmp/tmp.NJgSjiDtZR/src/github.com/influxdb/influxdb/cmd/influxd/restore/restore.go:40 +0xc0
main.(*Main).Run(0xc8200ebf00, 0xc82000a0c0, 0x3, 0x3, 0x0, 0x0)
	/tmp/tmp.NJgSjiDtZR/src/github.com/influxdb/influxdb/cmd/influxd/main.go:124 +0x1e0f
main.main()
	/tmp/tmp.NJgSjiDtZR/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0x29b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/root/.gvm/gos/go1.5.1/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/root/.gvm/gos/go1.5.1/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/root/.gvm/gos/go1.5.1/src/os/signal/signal_unix.go:28 +0x37
```

Anything I could be doing wrong ? Thanks in advance.

**Comment by otoolep** [comment]
Thanks for the report @simcap -- fixed by #4643
