### ISSUE TITLE
[0.9.5-rc2] influx_stress: 'panic: integer divide by zero'

### ISSUE THREAD

**Issue by yuokada** [influxdb/influxdb#4834]
OS: CentOS 6.7 x86_64
Influxdb ver:  v0.9.5-rc2
```
$ rpm -q influxdb
influxdb-0.9.5-0.1.rc2.x86_64
$ influxd version
InfluxDB v0.9.5-rc2 (git: 0.9.5 ca1fdfd4d7c978c5b9db0570d7eab7a7797a68a8, built 2015-11-13T03:17:19+0000)
```

```
$ /usr/bin/influx_stress  -test template.toml
Filling the Point Channel Buffer...
Test will begin in 0 seconds
Starting Stress...
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x401385 pc=0x401385]

goroutine 1 [running]:
main.main()
        /home/philip/repos/influxdb/src/github.com/influxdb/influxdb/cmd/influx_stress/influx_stress.go:88 +0x785

goroutine 8 [chan receive]:
github.com/influxdb/influxdb/stress.(*ConcurrencyLimiter).handleLimits(0xc208092140)
        /home/philip/repos/influxdb/src/github.com/influxdb/influxdb/stress/runner.go:352 +0x4a
created by github.com/influxdb/influxdb/stress.NewConcurrencyLimiter
        /home/philip/repos/influxdb/src/github.com/influxdb/influxdb/stress/runner.go:330 +0xf3

goroutine 33 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [runnable]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:280 +0x55
net.closesocket(0x3, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:510 +0x3a
net.(*netFD).destroy(0xc2080be000)
        /usr/local/go/src/net/fd_unix.go:135 +0x46
net.(*netFD).decref(0xc2080be000)
        /usr/local/go/src/net/fd_unix.go:153 +0x47
net.(*netFD).Close(0xc2080be000, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:202 +0xb7
net.(*conn).Close(0xc20802ebb0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:137 +0xb5
net/http.(*persistConn).closeLocked(0xc208096000)
        /usr/local/go/src/net/http/transport.go:1147 +0x55
net/http.(*persistConn).close(0xc208096000)
        /usr/local/go/src/net/http/transport.go:1141 +0x73
net/http.(*persistConn).readLoop(0xc208096000)
        /usr/local/go/src/net/http/transport.go:938 +0x963
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 7 [select]:
net/http.(*persistConn).writeLoop(0xc208096000)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc
```

```
$ cat template.toml
# This section cannot be commented out
# To prevent writes set `enabled=false`
# in [write.influx_client.basic]
[write]
  [write.point_generator]
    # The basic point generator will generate points of the form
    # `cpu,host=server-%v,location=us-west value=234 123456`
    [write.point_generator.basic]
      # number of points that will be written for each of the series
      point_count = 100
      # number of series
      series_count = 100000
      # How much time between each timestamp
      tick = "10s"
      # Randomize timestamp a bit (not functional)
      jitter = true
      # Precision of points that are being written
      precision = "n"
      # name of the measurement that will be written
      measurement = "cpu"
      # The date for the first point that is written into influx
      start_date = "2006-Jan-02"
      # Defines a tag for a series
      [[write.point_generator.basic.tag]]
        key = "host"
        value = "server"
      [[write.point_generator.basic.tag]]
        key = "location"
        value = "us-west"
      # Defines a field for a series
      [[write.point_generator.basic.field]]
        key = "value"
        value = "float64" # supported types: float64, int, bool


  [write.influx_client]
    [write.influx_client.basic]
      # If enabled the writer will actually write
      enabled = true
      # Address of the Influxdb instance
      address = "localhost:8086" # stress_test_server runs on port 1234
      # Database that is being written to
      database = "stress"
      # Precision of points that are being written
      precision = "n"
      # Size of batches that are sent to db
      batch_size = 10000
      # Interval between each batch
      batch_interval = "1s"
      # How many concurrent writers to the db
      concurrency = 10
      # ssl enabled?
      ssl = false
      # format of points that are written to influxdb
      format = "line_http" # line_udp (not supported yet), graphite_tcp (not supported yet), graphite_udp (not supported yet)
```

**Comment by otoolep** [comment]
@mjdesa

**Comment by mjdesa** [comment]
@yuokada looks like it you're using the old version of `influx_stress` with the new version of the config file.

Here's the config file for the old version

```
# Set the buffer size for the channel
# that sends points to the influxdb
# client
channel_buffer_size = 15000

# Configuration settings for the 
# stress test
[write]
  # How many concurrent writers to the db
  concurrency = 10
  # Size of batches that are sent to db
  batch_size = 10000
  # Interval between each batch
  batch_interval = "0s"
  # Database that is being written to
  database = "stress"
  # Precision of points that are being written
  precision = "n"
  # Address of the Influxdb instance
  address = "localhost:8086"
  # Drop and Create new DB
  reset_database = false
  # The date for the first point that is written into influx
  start_date = "2006-Jan-02"

# Describes the schema for series that will be
# written
[[series]]
  # How much time between each timestamp
  tick = "10s"
  # number of points that will be written for each of the series
  point_count = 100
  # name of the measurement that will be written
  measurement = "cpu"
  series_count = 100000

  # Defines a tag for a series
  [[series.tag]]
    key = "host"
    value = "server"

  [[series.tag]]
    key = "location"
    value = "us-west"

  # Defines a field for a series
  [[series.field]]
    key = "value"
    type = "float64"
```

Let me know if that works.

**Comment by yuokada** [comment]
`influx_stress` worked well with a new configfile.

Thanks @mjdesa and @otoolep.
