### ISSUE TITLE
crashed when executing a query

### ISSUE THREAD

**Issue by page31** [influxdb/influxdb#5028]
here is the log outputs:

[query] 2015/12/08 02:17:36 SELECT mean(value) / mean AS "value" FROM "system_info"."default".disk_free WHERE fstype
 = 'ext4' AND time > now() - 12h GROUP BY time(30s), host, path
panic: runtime error: index out of range

goroutine 138282 [running]:
github.com/influxdb/influxdb/influxql.func·005(0xc2082c8600, 0x2, 0x2, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/influxql/result.go:98 +0x4a
github.com/influxdb/influxdb/influxql.func·010(0xc2082c8600, 0x2, 0x2, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/influxql/result.go:147 +0xa8
github.com/influxdb/influxdb/tsdb.processForMath(0xc208202528, 0x1, 0x1, 0xc208652000, 0x5a1, 0x5a1, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/raw.go:652 +0x4ad
github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).execute(0xc20814e920, 0xc208672240)
        /root/go/src/github.com/influxdb/influxdb/tsdb/aggregate.go:156 +0x17bd
created by github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).Execute
        /root/go/src/github.com/influxdb/influxdb/tsdb/aggregate.go:48 +0x5a

**Comment by page31** [comment]
fixed in commit 5c63cca
