### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yuankui** [influxdb/influxdb#5032]
hello, my influxdb cannot start normally
every time I start influxdb with `service influxdb start`, the following log appears and influxdb crashes.
what's wrong with it,and how to fix it?

```
2015/12/08 14:48:08 InfluxDB starting, version 0.9.4.2, branch 0.9.4, commit da1b59e7d7764d36786253b2db13b97f42ed4e1d
2015/12/08 14:48:08 Go version go1.5, GOMAXPROCS set to 4
2015/12/08 14:48:08 Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/12/08 14:48:08 Using data dir: /var/opt/influxdb/meta
[metastore] 2015/12/08 14:48:08 Node at 0.0.0.0:8088 [Follower]
[metastore] 2015/12/08 14:48:08 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[0.0.0.0:8088]
[metastore] 2015/12/08 14:48:10 Node at 0.0.0.0:8088 [Leader]. peers=[0.0.0.0:8088]
[metastore] 2015/12/08 14:48:10 Updated node id=1 hostname=0.0.0.0:8088
[monitor] 2015/12/08 14:48:10 Starting monitor system
[monitor] 2015/12/08 14:48:10 'build' registered for diagnostics monitoring
[monitor] 2015/12/08 14:48:10 'runtime' registered for diagnostics monitoring
[monitor] 2015/12/08 14:48:10 'network' registered for diagnostics monitoring
[monitor] 2015/12/08 14:48:10 'system' registered for diagnostics monitoring
[store] 2015/12/08 14:48:10 Using data dir: /var/opt/influxdb/data
[monitor] 2015/12/08 14:48:10 Storing statistics in database '_internal' retention policy '', at interval 10s
[wal] 2015/12/08 14:48:10 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/12/08 14:48:10 WAL writing to /var/opt/influxdb/wal/mydb/default/143
[wal] 2015/12/08 14:48:10 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/12/08 14:48:10 WAL writing to /var/opt/influxdb/wal/testdb/default/142
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x905260]

goroutine 1 [running]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Partition).Close(0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:784 +0x120
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).close(0xc82009a2a0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:569 +0x62
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Close(0xc82009a2a0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:560 +0x105
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).Close(0xc820250840, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:160 +0x9e
github.com/influxdb/influxdb/tsdb.(*Shard).close(0xc8202ceea0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/shard.go:145 +0x4a
github.com/influxdb/influxdb/tsdb.(*Shard).Open(0xc8202ceea0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/shard.go:129 +0x55
github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0xc820178000, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/store.go:291 +0xd2c
github.com/influxdb/influxdb/tsdb.(*Store).Open(0xc820178000, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/store.go:324 +0x35a
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc82015d0e0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:362 +0xdea
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc82015d0e0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:308 +0x2d
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc820094200, 0xc82000a060, 0x4, 0x4, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:114 +0xd7e
main.(*Main).Run(0xc820363ec0, 0xc82000a060, 0x4, 0x4, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x67e
main.main()
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [IO wait]:
net.runtime_pollWait(0x7f375e4547b0, 0x72, 0xc82000e170)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820057170, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820057170, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820057110, 0x0, 0x7f3756bbe1c8, 0xc8201d0040)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820028100, 0xc820034ec8, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820028100, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc820170740, 0x7f375e453830, 0xc820028100, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x4b
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:346 +0xae9

goroutine 8 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820028108, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc8201769f0, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:2059 +0x51
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc820057180)
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:346 +0x79
created by github.com/hashicorp/raft.NewNetworkTransport
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:138 +0x284

goroutine 9 [runnable]:
syscall.Syscall(0x3, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0xf, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/syscall/zsyscall_linux_amd64.go:296 +0x4a
os.(*file).close(0xc8201f66c0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/os/file_unix.go:126 +0x61
os.(*File).Close(0xc8202cc058, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/os/file_unix.go:118 +0x54
io/ioutil.WriteFile(0xc820176a80, 0x21, 0xc8201f3214, 0x11, 0x40, 0xc8000001ed, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/io/ioutil/ioutil.go:85 +0x104
github.com/hashicorp/raft.(*JSONPeers).SetPeers(0xc820176ab0, 0xc8206058a0, 0x1, 0x1, 0x0, 0x0)
	/tmp/build/src/github.com/hashicorp/raft/peer.go:121 +0x41e
github.com/hashicorp/raft.(*Raft).processLog(0xc8200a01c0, 0xc8203af840, 0x0, 0x0)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:1159 +0x11ab
github.com/hashicorp/raft.(*Raft).processLogs(0xc8200a01c0, 0x136, 0xc8201b0000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:1117 +0x4a2
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc8200a01c0)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:867 +0x429
github.com/hashicorp/raft.(*Raft).runLeader(0xc8200a01c0)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:821 +0x936
github.com/hashicorp/raft.(*Raft).run(0xc8200a01c0)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:602 +0xbb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:252 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200a01c0, 0xc820173d00)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc8200a01c0)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:509 +0x10eb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:253 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200a01c0, 0xc820173d10)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 11 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc8200a01c0)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:1636 +0x493
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:254 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200a01c0, 0xc820173d20)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 12 [select]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc82000b4f0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/state.go:187 +0x4f5
created by github.com/influxdb/influxdb/meta.(*localRaft).open
	/tmp/build/src/github.com/influxdb/influxdb/meta/state.go:177 +0x1344

goroutine 13 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820028110, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc820090780)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:622 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:239 +0x364

goroutine 14 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820028118, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc820090780)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:726 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3b6

goroutine 51 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc82015d0e0, 0xc820016720)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:492 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:352 +0xc67

goroutine 34 [IO wait]:
net.runtime_pollWait(0x7f375e454630, 0x72, 0xc82000e170)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820057790, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820057790, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820057730, 0xc8201f4000, 0x1000, 0x1000, 0x0, 0x7f375e44e050, 0xc82000e170)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200281e8, 0xc8201f4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820017980)
	/home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadByte(0xc820017980, 0x53124d, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:229 +0x7a
github.com/hashicorp/go-msgpack/codec.(*ioDecReader).readn1(0xc820177e00, 0x57)
	/tmp/build/src/github.com/hashicorp/go-msgpack/codec/decode.go:90 +0x42
github.com/hashicorp/go-msgpack/codec.(*msgpackDecDriver).initReadNext(0xc82017e6a0)
	/tmp/build/src/github.com/hashicorp/go-msgpack/codec/msgpack.go:540 +0x41
github.com/hashicorp/go-msgpack/codec.(*Decoder).decode(0xc8200179e0, 0x998360, 0xc8201e63a0)
	/tmp/build/src/github.com/hashicorp/go-msgpack/codec/decode.go:635 +0x70
github.com/hashicorp/go-msgpack/codec.(*Decoder).Decode(0xc8200179e0, 0x998360, 0xc8201e63a0, 0x0, 0x0)
	/tmp/build/src/github.com/hashicorp/go-msgpack/codec/decode.go:630 +0x74
github.com/hashicorp/raft.decodeResponse(0xc820171500, 0x989ba0, 0xc82017e3e0, 0xc82000b900, 0x0, 0x0)
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:479 +0x70
github.com/hashicorp/raft.(*NetworkTransport).genericRPC(0xc820057180, 0xc82010a700, 0xe, 0x0, 0x989b40, 0xc82000b900, 0x989ba0, 0xc82017e3e0, 0x0, 0x0)
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:287 +0x235
github.com/hashicorp/raft.(*NetworkTransport).AppendEntries(0xc820057180, 0xc82010a700, 0xe, 0xc82000b900, 0xc82017e3e0, 0x0, 0x0)
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:260 +0x8c
github.com/hashicorp/raft.(*Raft).replicateTo(0xc8200a01c0, 0xc8201c00b0, 0x136, 0xc82010a100)
	/tmp/build/src/github.com/hashicorp/raft/replication.go:157 +0x4c0
github.com/hashicorp/raft.(*Raft).replicate(0xc8200a01c0, 0xc8201c00b0)
	/tmp/build/src/github.com/hashicorp/raft/replication.go:105 +0x28c
github.com/hashicorp/raft.(*Raft).startReplication.func1()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:840 +0x29
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200a01c0, 0xc82010e8e0)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 16 [select]:
github.com/hashicorp/raft.(*Raft).heartbeat(0xc8200a01c0, 0xc8201c00b0, 0xc8200176e0)
	/tmp/build/src/github.com/hashicorp/raft/replication.go:295 +0x72f
github.com/hashicorp/raft.(*Raft).replicate.func1()
	/tmp/build/src/github.com/hashicorp/raft/replication.go:92 +0x32
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200a01c0, 0xc82017e3a0)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 52 [select]:
github.com/hashicorp/raft.(*Raft).Apply(0xc8200a01c0, 0xc8202f6e20, 0x19, 0x20, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:296 +0x40c
github.com/influxdb/influxdb/meta.(*localRaft).apply(0xc82000b4f0, 0xc8202f6e20, 0x19, 0x20, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/state.go:250 +0x76
github.com/influxdb/influxdb/meta.(*Store).apply(0xc820090780, 0xc8202f6e20, 0x19, 0x20, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:1506 +0x64
github.com/influxdb/influxdb/meta.(*Store).exec(0xc820090780, 0xc800000007, 0xff2a80, 0xb46f40, 0xc820289080, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:1499 +0x3a2
github.com/influxdb/influxdb/meta.(*Store).SetDefaultRetentionPolicy(0xc820090780, 0xc82013d710, 0x9, 0xbd3e70, 0x7, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:1012 +0x14c
github.com/influxdb/influxdb/monitor.(*Monitor).storeStatistics(0xc8200aea90)
	/tmp/build/src/github.com/influxdb/influxdb/monitor/service.go:319 +0xe45
created by github.com/influxdb/influxdb/monitor.(*Monitor).Open
	/tmp/build/src/github.com/influxdb/influxdb/monitor/service.go:134 +0x30c

goroutine 66 [select]:
github.com/hashicorp/raft.(*NetworkTransport).handleCommand(0xc820057180, 0xc8201d20c0, 0xc8201d2120, 0xc8201f2000, 0x0, 0x0)
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:445 +0x68f
github.com/hashicorp/raft.(*NetworkTransport).handleConn(0xc820057180, 0x7f375e4551f0, 0xc82011c060)
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:370 +0x361
created by github.com/hashicorp/raft.(*NetworkTransport).listen
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:357 +0x3a9

goroutine 67 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc8202d0000, 0xc8201d2540)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 22 [IO wait]:
net.runtime_pollWait(0x7f375e4544b0, 0x72, 0xc82000e170)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82012c060, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82012c060, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82012c000, 0xc820628000, 0x1000, 0x1000, 0x0, 0x7f375e44e050, 0xc82000e170)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820028000, 0xc820628000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc8205a6420)
	/home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadByte(0xc8205a6420, 0x1, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:229 +0x7a
github.com/hashicorp/raft.(*NetworkTransport).handleCommand(0xc820057180, 0xc8205a6420, 0xc8205a6480, 0xc8201a01c0, 0x0, 0x0)
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:386 +0x45
github.com/hashicorp/raft.(*NetworkTransport).handleConn(0xc820057180, 0x7f375e4551f0, 0xc820028000)
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:370 +0x361
created by github.com/hashicorp/raft.(*NetworkTransport).listen
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:357 +0x3a9
```

**Comment by otoolep** [comment]
You should upgrade to 0.9.5.1. There have been a ton of fixes in the code
since 0.9.4.2.

**Comment by otoolep** [comment]
To be clear I don't know for a fact it will solve the issue but I highly
recommend it as a first step.

**Comment by yuankui** [comment]
@otoolep thx, this error disappears, and other appears.
I will create a new issue then.
