### ISSUE TITLE
0.9.4.1 Panic: assignment to entry in nil map + OOM

### ISSUE THREAD

**Issue by arussellsaw** [influxdb/influxdb#5094]
Last night we had a rather concerning panic + OOM crash
here's a memory graph for the instance running influxdb
![screen shot 2015-12-11 at 10 51 39](https://cloud.githubusercontent.com/assets/5236823/11742196/c7a638f0-9ff5-11e5-9a92-d1766bb13f96.png)

it's worth noting that influxdb and grafana are the only services this instance is used for.

here's the first 200 lines of a ~400MB log file of nearly exclusively stack trace:

if you want the full log file i can provide that, but as i said it's nearly 400MB, i've also stripped [query]
log lines from it in order to avoid disclosing application sensitive metrics.

```
panic: assignment to entry in nil map

goroutine 99892526 [running]:
github.com/influxdb/influxdb/tsdb.(*Store).CreateShard(0xc82011e380, 0xc822813c9c, 0x7, 0xc82038e990, 0x7, 0x6f, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/store.go:97 +0x7a1
github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard.func1(0xc820126f00, 0xc822813c9c, 0x7, 0xc82038e990, 0x7, 0xc82d94be60, 0x1, 0x6f, 0x1, 0xc824c04000, ...)
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x1d5
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:299 +0x1c5

goroutine 1 [select]:
main.(*Main).Run(0xc82031bf10, 0xc82000a060, 0x4, 0x4, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:101 +0x1082
main.main()
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, 76628 minutes, locked to thread]:
runtime.goexit()
	/home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 21 [runnable]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc820178000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:849 +0xcce
github.com/hashicorp/raft.(*Raft).runLeader(0xc820178000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:821 +0x936
github.com/hashicorp/raft.(*Raft).run(0xc820178000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:602 +0xbb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:252 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc820178000, 0xc820161150)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 22 [runnable]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc820178000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:509 +0x10eb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:253 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc820178000, 0xc820161160)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 23 [runnable]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc820178000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:1636 +0x493
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:254 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc820178000, 0xc820161170)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 99743684 [chan send, 89 minutes]:
github.com/influxdb/influxdb/tsdb.(*ShowMeasurementsMapper).Open.func1(0xc8d6054000, 0x294a, 0x294a, 0xc94bccbaa0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/show_measurements.go:166 +0x83
created by github.com/influxdb/influxdb/tsdb.(*ShowMeasurementsMapper).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/show_measurements.go:169 +0x215

goroutine 10 [select, 76628 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc8201158c0, 0xc82010e6c0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:491 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:351 +0xc67

goroutine 99892523 [select]:
github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard(0xc820126f00, 0xc8377e5c40, 0xc8228139dc, 0x7, 0xc82038e990, 0x7, 0x1, 0xc8302e7000, 0x100, 0x100, ...)
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:306 +0x8f8
github.com/influxdb/influxdb/cluster.(*PointsWriter).WritePoints.func1(0xc82d94b740, 0xc820126f00, 0xc822813a80, 0xc8377e5c40, 0xc8228139dc, 0x7, 0xc82038e990, 0x7, 0xc8302e7000, 0x100, ...)
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:225 +0x97
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).WritePoints
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:226 +0x3ab

goroutine 99892524 [runnable]:
sync.runtime_Semacquire(0xc82011e384)
	/home/philip/.gvm/gos/go1.5/src/runtime/sema.go:43 +0x26
sync.(*Mutex).Lock(0xc82011e380)
	/home/philip/.gvm/gos/go1.5/src/sync/mutex.go:82 +0x1c4
sync.(*RWMutex).Lock(0xc82011e380)
	/home/philip/.gvm/gos/go1.5/src/sync/rwmutex.go:82 +0x30
github.com/influxdb/influxdb/tsdb.(*Store).CreateShard(0xc82011e380, 0xc8228139dc, 0x7, 0xc82038e990, 0x7, 0x6f, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/store.go:68 +0x50
github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard.func1(0xc820126f00, 0xc8228139dc, 0x7, 0xc82038e990, 0x7, 0xc82d94b9e0, 0x1, 0x6f, 0x1, 0xc8302e7000, ...)
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x1d5
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
	/tmp/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:299 +0x1c5

goroutine 40 [chan receive, 309 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc8201158c0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:442 +0x1eb
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:378 +0x1265

goroutine 42 [select, 76628 minutes, locked to thread]:
runtime.gopark(0xd19ec8, 0xc82019df28, 0xbd5940, 0x6, 0x18, 0x2)
	/home/philip/.gvm/gos/go1.5/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82019df28, 0x0, 0x18)
	/home/philip/.gvm/gos/go1.5/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82019df28)
	/home/philip/.gvm/gos/go1.5/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/home/philip/.gvm/gos/go1.5/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 99743639 [chan send, 89 minutes]:
github.com/influxdb/influxdb/tsdb.(*ShowMeasurementsMapper).Open.func1(0xc8c5e04000, 0x294a, 0x294a, 0xc993121980)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/show_measurements.go:166 +0x83
created by github.com/influxdb/influxdb/tsdb.(*ShowMeasurementsMapper).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/show_measurements.go:169 +0x215

goroutine 69325838 [IO wait, 12936 minutes]:
net.runtime_pollWait(0x7fc323478960, 0x72, 0xc820010140)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc826fa9020, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc826fa9020, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc826fa8fc0, 0xc828aa8000, 0x1000, 0x1000, 0x0, 0x7fc3262c5050, 0xc820010140)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8398624d0, 0xc828aa8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc821af1b18, 0xc828aa8000, 0x1000, 0x1000, 0xc828aa9000, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc880ae5560, 0xc828aa8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc825f8f620)
	/home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc825f8f620, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:132 +0xcc
net/http.(*conn).readRequest(0xc821af1ad0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:629 +0x2bb
net/http.(*conn).serve(0xc821af1ad0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1910 +0x3f6

goroutine 99741484 [chan send, 91 minutes]:
github.com/influxdb/influxdb/tsdb.(*ShowMeasurementsMapper).Open.func1(0xc82dfd2000, 0x294a, 0x294a, 0xc869ee2780)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/show_measurements.go:166 +0x83
created by github.com/influxdb/influxdb/tsdb.(*ShowMeasurementsMapper).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/show_measurements.go:169 +0x215

goroutine 36984360 [IO wait, 45963 minutes]:
net.runtime_pollWait(0x7fc323478360, 0x72, 0xc820010140)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8292df8e0, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8292df8e0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8292df880, 0xc824bb8000, 0x1000, 0x1000, 0x0, 0x7fc3262c5050, 0xc820010140)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82875bc98, 0xc824bb8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc8283eae08, 0xc824bb8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82a34b1a0, 0xc824bb8000, 0x1000, 0x1000, 0x11, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc822647740)
	/home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc822647740, 0xc81fc29d0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc822647740, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc824a5a750, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc824a5a750, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc822647740, 0xc827ac4000, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc8283eadc0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc8283eadc0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1910 +0x3f6

goroutine 65118931 [IO wait]:
net.runtime_pollWait(0x7fc323478de0, 0x72, 0xc820010140)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82bed6990, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82bed6990, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82bed6930, 0xc893aa9000, 0x1000, 0x1000, 0x0, 0x7fc3262c5050, 0xc820010140)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc821ad88e8, 0xc893aa9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc828d13018, 0xc893aa9000, 0x1000, 0x1000, 0xc8872d8000, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc823be6f80, 0xc893aa9000, 0x1000, 0x1000, 0xc8201d01a8, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc838005140)
```

**Comment by pauldix** [comment]
Can you update to 0.9.6.1? There have been quite a few fixes since that release. Going to close this for now since I don't think this exists in the current release.

**Comment by arussellsaw** [comment]
We plan to, however this is almost certainly a race condition, so no guarantees on seeing this again. the instance had been running for a few months.
